### ISSUE TITLE
mobile is not supported

### ISSUE THREAD

**Issue by adteven** [Bilibili/flv.js#10]

**Comment by xqq** [comment]
Safari for iOS doesn't support `Media Source Extensions`

See http://caniuse.com/#feat=mediasource

**Comment by adteven** [comment]
android xiaomi  os 5.1.1   charome 53 can just show one frame

**Comment by adteven** [comment]
http live flv dos not can play in PC chrome

**Comment by xqq** [comment]
Please provide your stream details or url, or provide `chrome://media-internals` logcat
