### ISSUE TITLE
疑似不支持 Firefox 硬解码

### ISSUE THREAD

**Issue by dfc643** [Bilibili/flv.js#101]
B 站上有一段 4K 120FPS 的视频：
http://www.bilibili.com/video/av1382278/

使用 Flash 播放器可以硬解码，
但是使用 H5 播放器疑似无法硬解码。

测试浏览器：
Chrome 58 正常
Firefox 51 不正常
IE 11 正常

暂且不知道是浏览器问题还是 flv.js 的问题先反馈一下

**Comment by dfc643** [comment]
已确认是 Firefox 将显卡驱动列入黑名单导致，非 flv.js 所致

**Comment by xqq** [comment]
农企用户？

**Comment by dfc643** [comment]
@xqq  不不，牙膏厂用户

**Comment by dfc643** [comment]
@xqq 刚刚通过重装显卡驱动把 Firefox 的显卡问题解决了，但是还是存在播放这个视频卡的问题，这位 UP 的 MP4 源文件我丢在 Firefox 里面试过了不卡，应该能排除浏览器对显卡的支持问题了。（解决显卡驱动之前很卡）

(*＾-＾*)

显卡是 CPU 核显：Intel HD 610
更换显卡驱动之后，Firefox 报告的信息正常，之前 H264 D2D DW 是不正常的
```
合成	Direct3D 11
异步平移/缩放	无
WebGL 渲染器	Google Inc. -- ANGLE (Intel(R) HD Graphics 610 Direct3D11 vs_5_0 ps_5_0)
WebGL2 渲染器	Google Inc. -- ANGLE (Intel(R) HD Graphics 610 Direct3D11 vs_5_0 ps_5_0)
H264 硬件解码	Yes; Using D3D11 API
音频后端	wasapi
Direct2D	true
DirectWrite	true (10.0.14393.351)
```

**Comment by songguangyu** [comment]
![image](https://cloud.githubusercontent.com/assets/6869168/23696844/67a5703e-0420-11e7-815c-ef5882497a4c.png)


我也在firefox 中无法解码 请教一下 是什么问题呢？

我的电脑是mac pro firefox 版本 52.0
