### ISSUE TITLE
 low speed video playback for flv

### ISSUE THREAD

**Issue by adelejalaee** [Bilibili/flv.js#102]
hi , i have a problem with low speed video playback between flv & mp4.
when i click on the titles,playback speed is too low.
Can you help me?
http://kdscctv.com/video/t-video/demo/index-c.html

tip: you shoud click on titles of video for play.

**Comment by xqq** [comment]
[TransmuxingController] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported audio codec idx: 2

Unsupported mp3 audio codec, still in development and have no plan of release.
