### ISSUE TITLE
Safari不支持

### ISSUE THREAD

**Issue by tenglongwentian** [Bilibili/flv.js#103]
经过测试发现，对Safari不支持

**Comment by xqq** [comment]
Mac Safari 支持
iOS Safari 不支持 Media Source Extensions，不是我的锅，问苹果

**Comment by songguangyu** [comment]
MAC safari 10.1 才支持fetch 如果没有websocket 怎么做直播拉流呢？

**Comment by songguangyu** [comment]
9.2 的safari 不支持直播 作者已经回答我了 谢谢qq
