### ISSUE TITLE
How to get duration in flv.js

### ISSUE THREAD

**Issue by babymaychen** [Bilibili/flv.js#104]
if (flvjs.isSupported()) {

        let videoElement = this.$refs.video

        flvPlayer = flvjs.createPlayer({
              type: 'flv',
              url: '/flv'
        })

        flvPlayer.attachMediaElement(videoElement)

        flvPlayer.load()

        console.log(flvPlayer.duration)
}
but the result is NaN

**Comment by mengshixing** [comment]
I have same question, Would you give me some suggestions, please?

**Comment by scottMan1001** [comment]
> 我有同样的问题，请你给我一些建议吗？

这个问题你解决了么。
