### ISSUE TITLE
有办法让flvjs支持vp6编码的flv吗

### ISSUE THREAD

**Issue by wuhecong** [Bilibili/flv.js#105]
因为有些视频站比较老，所以他们的flv是vp6编码的，最新版的chrome不支持flash了，我也不想用flash播放，有办法解决吗？尝试过用videoconverter.js转码再播放，但效率太低😂

**Comment by xqq** [comment]
浏览器和MSE不支持，在无法走浏览器解码的情况下，不考虑做支持

**Comment by wuhecong** [comment]
看样子我只能弄转码了，谢谢大神回答☺

**Comment by xqq** [comment]
js解码库有好几个，魔改一下能实现js中软解
