### ISSUE TITLE
缓冲时可能的bug

### ISSUE THREAD

**Issue by Derek-Gong** [Bilibili/flv.js#106]
在使用B站html5播放器时，碰到了下述问题：
几乎所有视频只能快速缓存开始的几十秒到若干分钟，等到视频进度进行到缓存的末尾时，视频卡住。
手动拖拽进度条视频立马加载到相应进度，并在持续几秒的时间内，缓存速度达到下载带宽限制。之后缓存维持在接近0的速度，直到下一次拖拽。

试着在chrome上调试播放器，发现自动缓存进度一直达不到lazyload的阈值，因而_suspendTransmuxer不会被调用，_checkProgressAndResume也就不会被触发。
看起来_checkProgressAndResume的触发是保证视频正常播放中不断维持缓存速度的唯一机制，可当初始的缓存进度没有达到调用_suspendTransmuxer的条件的话，这一机制就不会被触发。之后只能不断拖拽进度条去手动触发seek。

**Comment by DieMoe233** [comment]
这个问题我也遇到，不过我不拖拽进度条，因为那样会改变进度，我直接点清晰度切换。

**Comment by Derek-Gong** [comment]
@DieMoe233 嗯 但要是几十秒就卡一次的话，相信我，你是不会有心情去好好看的。

**Comment by xqq** [comment]
以及大致的重现条件、avid、浏览器

**Comment by Derek-Gong** [comment]
额 这个问题我没办法稳定复现。我现在暂时没有这个问题。
当时教育网看B站视频根本没速度，被迫挂vpn的上海线路。
北京教育网挂vpn到上海

运营商： 上海市阿里
当时的统计信息：Stream Host：ws.acgvideo.com
浏览器： chrome

用chrome调试播放器时发现TransmuxingEvents.MEDIA_SEGMENT仍持续被触发。
B站播放器救援群说，“可能跟服务端限流策略有关”。
其他的就不清楚了。

**Comment by zccicy** [comment]
关掉阿里代理试试
