### ISSUE TITLE
demo 不能运行啊

### ISSUE THREAD

**Issue by haowenjiang** [Bilibili/flv.js#11]
demo 不能运行啊

**Comment by hevily** [comment]
确实不能运行  为啥一直有人转发....

**Comment by bulesky520** [comment]
可以运行的，主要看你提示什么？demo 上是要提供一个json 文件访问。json包含的基本内容如下：{	
	"type":"mp4",
	"url":"http://www.zk888.net/sp/%E5%BA%93%E5%AD%98%E7%AE%A1%E7%90%86/%E4%B8%B2%E7%A0%81%E8%BF%BD%E6%BA%AF.mp4"
}
或者你也可以直接按主页上的Demo 创建更简单

**Comment by xqq** [comment]
You may need to configure `Access-Control-Allow-Origin` header according to CORS policy

See (cors.md)[docs/cors.md]

**Comment by haowenjiang** [comment]
按说明编译一下的确是可以运行了。
还有个问题，直播怎么做？用 httpflv 还是 websocket，特别是 websocket 怎么做？

**Comment by xqq** [comment]
httpflv，配置CORS头即可
websocket 需要自己写服务端支持

**Comment by ZoroZdd** [comment]
运行demo flvjs这个对象报错 import也报错?  莫非是我打开方式不对？

**Comment by xqq** [comment]
@ZoroZdd 从 https://github.com/Bilibili/flv.js/releases 下载编译好的js或自行编译引入

**Comment by ZoroZdd** [comment]
谢作者  我试试

**Comment by tenglongwentian** [comment]
求能够运行的demo，江湖救急

**Comment by yangzhencheng** [comment]
mp4 可以运行，但 flv 是不能运行的！不知道为什么……关键是，我要播放 flv 文件！
