### ISSUE TITLE
请教下播放flv出现了问题

### ISSUE THREAD

**Issue by Lirui072037** [Bilibili/flv.js#110]
![image](https://cloud.githubusercontent.com/assets/13636368/24036822/52cc8838-0b36-11e7-89a7-6bd2033c1fb9.png)
请问下播放flv出现这种报错  是由于什么原因引起的？

**Comment by xqq** [comment]
Non FLV

**Comment by Lirui072037** [comment]
播放的是flv地址  flash也可以播放的，但是不知道flv地址出了什么原因  导致报这样错误了 可以说详细点吗？谢谢

**Comment by xqq** [comment]
不是flv文件，可能是mp4

**Comment by Lirui072037** [comment]
我播放的是这个地址  http://61.185.46.87/demo/variety.flv   我用ffprobe.exe 看了下 是flv格式的，

**Comment by xqq** [comment]
FLV Header 里 TypeFlagsAudio 和 TypeFlagsVideo 都为 0，表示没有音频轨没有视频轨
我放宽一下 probe 检测，你可以修下文件或者自己改代码

**Comment by xqq** [comment]
Fixed https://github.com/Bilibili/flv.js/compare/0baa41eaed...0f06f5b9e0

**Comment by Lirui072037** [comment]
好的 谢谢你呀，
