### ISSUE TITLE
B站的直播切换到H5播放白屏，无法切回，没有切换按钮。

### ISSUE THREAD

**Issue by zkh90644** [Bilibili/flv.js#111]
发客服不回，只能在这里提了。

**Comment by xqq** [comment]
浏览器？

**Comment by zkh90644** [comment]
对的
 chrome Version 57.0.2987.98 (64-bit)
Mac OS X 10.12.3 (16D32)

**Comment by xqq** [comment]
F12 console 有啥报错么？
https模式？手动切回http

**Comment by zkh90644** [comment]
![image](https://cloud.githubusercontent.com/assets/12930558/24080599/cb4c88dc-0cdd-11e7-9838-1b9aa2923c54.png)
感觉是浏览器插件冲突了。我用隐私模式打开没问题。
http没问题。
https就白了

**Comment by xqq** [comment]
是https问题。。
