### ISSUE TITLE
flv-demuxer.js 中的parseChunks方法有一处逻辑错误

### ISSUE THREAD

**Issue by notejs** [Bilibili/flv.js#114]
贴代码如下，如果是一个文件分片的开头会执行。
```javascript
if (byteStart === 0) {  // buffer with FLV header
	if (chunk.byteLength > 13) {
		let probeData = FLVDemuxer.probe(chunk);
		offset = probeData.dataOffset;
		byteStart = probeData.dataOffset;
	} else {
		return 0;
	}
}
```
在后续执行_parseVideoData方法时以byteStart + offset作为作为当前tag在文件中的偏移。
因为
```javascript
offset = probeData.dataOffset;
byteStart = probeData.dataOffset;
```
所以 FLV header的长度会被重复计算，计算所得偏移会比实际偏移多出FLV header的长度（一般9个字节）。
不知道到我提的是否有道理？
ps: 看大家全用中文我也就中文了

**Comment by xqq** [comment]
bingo. 这是个问题，此时求得的 tagPosition 值是错误的。
不过 tagPosition -> fileposition 这个值最终没有被用到，所以没有造成运行上的 bug。

**Comment by notejs** [comment]
嗯，确实是没用到，keyframe相关信息是从scriptData中获取的
