### ISSUE TITLE
可以播放rtsp的视频么？

### ISSUE THREAD

**Issue by maxdylan** [Bilibili/flv.js#115]
大神，我现在满世界在找能播放rtsp视频的js，这个支持rtsp不？多谢多谢

**Comment by xqq** [comment]
**浏览器中不支持裸TCP/UDP，浏览器只支持HTTP和WebSocket**
**浏览器中不支持裸TCP/UDP，浏览器只支持HTTP和WebSocket**
**浏览器中不支持裸TCP/UDP，浏览器只支持HTTP和WebSocket**

**Comment by maxdylan** [comment]
~(～￣▽￣)～~(～￣▽￣)～
