### ISSUE TITLE
问个代码相关的问题

### ISSUE THREAD

**Issue by wwzaaa** [Bilibili/flv.js#117]
在remuxmp4的时候 为什么不直接用flv 的dts和pts 又算了一个dtsCorrection，来计算一个新的dts和pts

**Comment by wwzaaa** [comment]
能科普下为什么吗

**Comment by xqq** [comment]
fragmented mp4 记录每帧的 sample duration 而不是 dts，而每次打包 fmp4 最后一帧的 duration 会直接取上一帧的值。因此会造成一定的误差，为了保证下个 fmp4 时间戳能完全接上（MSE要求），需要做修正。

**Comment by wwzaaa** [comment]
多谢 去掉以后发现音频会哒哒哒的响，应该是时间戳没有对上。额有了dts，还要sample duration，这个是mp4封装的要求么？

**Comment by xqq** [comment]
每个 fmp4 片段记录一个 baseMediaDecodeTime 即起始 dts，后面记录每帧的 sample duration
哒哒哒是啥浏览器？

**Comment by wwzaaa** [comment]
chrome 我说把那段dtsCorrection的代码去掉会哒哒哒，正常么有问题
