### ISSUE TITLE
使用flv.js实现直播，可以加载，但是没声音是怎么回事，希望帮忙解决一下，有点急！！！

### ISSUE THREAD

**Issue by OwnGhy** [Bilibili/flv.js#118]
var player;
    var element = document.getElementsByName('videoElement')[0];
    player = flvjs.createPlayer({
        type: 'flv',
        isLive:'true',
        url: $('.urlInput').val()
    });
    player.attachMediaElement(element);
    player.load();
    player.play();

**Comment by xqq** [comment]
信息不足无法判断

**Comment by 332065255** [comment]
= =建议你先分析下你的flv直播音频是否是正常的

**Comment by gcaaaaaa** [comment]
..

**Comment by budingts** [comment]
我也遇到了，vlc播放没有问题，但是flvjs 去播放的时候就没有声音

**Comment by h0730303779** [comment]
> 我也遇到了，vlc播放没有问题，但是flvjs 去播放的时候就没有声音

请问 后来怎么解决的?  一样
