### ISSUE TITLE
问个问题 ，可以设置用软解解码么 

### ISSUE THREAD

**Issue by wwzaaa** [Bilibili/flv.js#119]
问个问题 ，可以设置用软解解码音频么？

**Comment by xqq** [comment]
解码方式是浏览器决定的，flv.js无权干涉。
音频正常都是软解，pc端没有支持音频硬解的dsp

**Comment by wwzaaa** [comment]
发现一部分三星手机在app webview里 音频硬解 he aac 会出错 会嘟嘟嘟嘟嘟嘟嘟

**Comment by wwzaaa** [comment]
能加个qq不

**Comment by xqq** [comment]
android带aac的OMX，应该是会走硬解的

**Comment by wwzaaa** [comment]
是呀，走硬解了，同一个视频流 直接用video 标签播hls 没问题，播flv音频就出错，看了下app log貌似直接播hls没走硬解，用flv,js播flv走硬解了，我就想是不是硬解芯片的问题，音频都是he aac。

**Comment by xqq** [comment]
视频源是HE-AAC?

**Comment by wwzaaa** [comment]
是的

**Comment by wwzaaa** [comment]
只有三星的部分手机有问题

**Comment by wwzaaa** [comment]
是不是lc aac的解码器 也能解 he aac

**Comment by xqq** [comment]
理论上能解出SBR的一半，是能正常播的

**Comment by xqq** [comment]
试下hls.js能不能正常播？

**Comment by wwzaaa** [comment]
android上的chrome可以播 唉

**Comment by xqq** [comment]
webview chromium版本多少？

**Comment by wwzaaa** [comment]
chrome/46.0.2490.76 好像是lc aac的解码器 解不了he aac

**Comment by xqq** [comment]
https://github.com/Bilibili/flv.js/blob/master/src/demux/flv-demuxer.js#L643

把这个android策略去掉试试

**Comment by wwzaaa** [comment]
hls.js也音频出错，去掉你说的那里，音频就播不了了，不知道是我的音频编码有问题 还是浏览器解码兼容性有问题，只有部分三星手机内置webview有这个问题。

**Comment by xqq** [comment]
换个新一点的三星设备试试。

**Comment by wwzaaa** [comment]
可能是我的直播流有问题

**Comment by xqq** [comment]
砍掉HE-AAC统一用LC吧。

最好先以FFmpeg输出的流为准进行测试。
另外HE-AAC有好几种格式，都可以试试
