### ISSUE TITLE
为什么有流进入但是无法播放？

### ISSUE THREAD

**Issue by ycylswing** [Bilibili/flv.js#121]
logger.js:99 [MSEController] > MediaSource onSourceOpen
flv.min.js:5 [FLVDemuxer] > Parsed onMetaData
flv.min.js:5 [FLVDemuxer] > Parsed AVCDecoderConfigurationRecord
flv.min.js:5 [MSEController] > Received Initialization Segment, mimeType: video/mp4;codecs=avc1.4d4032

**Comment by xqq** [comment]
没音频？

**Comment by ycylswing** [comment]
是的，流上只有视频没有音频

**Comment by xqq** [comment]
已改进 #135 
用 master 上最新代码，在 `MediaDataSource` 中指定 `hasAudio: false`

**Comment by ycylswing** [comment]
和我想法差不多，但是我一直用safari，这样还是没有根本解决问题，第一次在Safari下打开，会在第一帧停住，刷新后流量才来，一直还以为是autoplay的原因，ie和edge直接不出来，chrome和Firefox完全没问题
