### ISSUE TITLE
ffmpeg 實時桌面串流，影音不同步

### ISSUE THREAD

**Issue by fcwu** [Bilibili/flv.js#122]
**[Steps to reproduce]**
1. 使用 ffmpeg 串流 Ubuntu 桌面，開桌面上 Firefox 播 youtube
2. 使用另一電腦開啟 Chrome and Firefox 開 flvjs 網頁
3. 在 step1 的桌面不斷 pause and play youtube

**[expected result]**
影音順暢播放

**[actual result]**
發現音影(avsync)會差距愈來愈大，並隨著 step3, pause 的數量成正比成長

**[notes]**
1. chrome://media-internals/ 會發現
```
00:00:03 181	error	Large timestamp gap detected; may cause AV sync to drift. time:853000us expected:905358us delta:-52358us
00:00:03 181	error	Large timestamp gap detected; may cause AV sync to drift. time:864000us expected:928578us delta:-64578us
00:00:03 282	error	Large timestamp gap detected; may cause AV sync to drift. time:875000us expected:951798us delta:-76798us
00:00:03 282	error	Large timestamp gap detected; may cause AV sync to drift. time:898000us expected:975018us delta:-77018us
00:00:03 485	error	Large timestamp gap detected; may cause AV sync to drift. time:1121000us expected:1207217us delta:-86217us
00:00:03 486	error	Large timestamp gap detected; may cause AV sync to drift. time:1122000us expected:1230437us delta:-108437us
00:00:03 486	error	Large timestamp gap detected; may cause AV sync to drift. time:1122000us expected:1253657us delta:-131657us
```
2. Player Properties from Chrome: https://paste.ubuntu.com/24372463/
3. Log from Chrome: https://paste.ubuntu.com/24372478/
4. Firefox and Chrome 都有一樣的問題
5. 使用 ffplay 直接播放並無問題

Any suggestion?

**Comment by xqq** [comment]
如果不进行 step3，音视频同步是否保持正常?
ffmpeg 录制和串流参数？是否非恒定帧率，并根据桌面状态动态变化?

**Comment by fcwu** [comment]
不進行 step3 幾乎是正常，有小機率性的 (< 20%) 感受到有不同步

以下是錄制參數
/usr/bin/ffmpeg -f pulse -i default -video_size 1280x720 -framerate 20 -f x11grab -i :0 -r 20 -g 20 -flags:v +global_header -vcodec libx264 -preset ultrafast -b_strategy 0 -pix_fmt yuv420p -bsf:v dump_extra=freq=e -maxrate 3477k -bufsize 1159k -ar 44100 -c:a aac -f flv pipe:1

此命令會將影片串流 stdout, stdout 由 Python Flask 接收再傳出

**Comment by fcwu** [comment]
Close because resoled by 74845e621a552e008ee8c912b09cfb46d39f4ac6

The latest mater branch is not stable enough, but it's find due to not a formal release
