### ISSUE TITLE
内存溢出，不段增长直到chrome报错

### ISSUE THREAD

**Issue by tshug** [Bilibili/flv.js#123]
环境：
播放9路720P实时视频，http flv,islive=true
windows 10 chrome,8G内存

播放时，内存不断增长，最高到2GB，直到挂掉。

用的是 flv.js tag 1.1

**Comment by xqq** [comment]
9个实例？

**Comment by tshug** [comment]
在同一个屏幕上播放9路视频，相当于9个 flvPlayer






2017年4月14日
------------------------------------------ 
 

在 2017-04-14 13:16:43，"xqq" <notifications@github.com> 写道：


9个实例？

**Comment by dongyang03** [comment]
@xqq 我也遇到这个问题，在mac chorme上内存不断增长，直到浏览器奔溃。希望能和你qq交流。

**Comment by xqq** [comment]
@dongyang03 私我联系方式 xqq@xqq.im

**Comment by dongyang03** [comment]
@xqq 已经通过google 邮箱发送了我的微信账号，google的邮箱发出去的邮件有可能会跑到垃圾箱。麻烦查看下。

**Comment by hj009** [comment]
我也遇到同样的问题，浏览器缓存堆积直到崩溃。有谁解决了吗？求顺带

**Comment by xqq** [comment]
新增MSE内存清理：

https://github.com/Bilibili/flv.js/commit/43534eb8f143cfe27fe624d4a1d1f03ee7ef3aa3
