### ISSUE TITLE
Fail in playing flv live stream published by Monaserver

### ISSUE THREAD

**Issue by WangJi** [Bilibili/flv.js#128]
尝试搭建一个本地的直播测试，使用`OBS Studio`->`MonaServer`->`flv.js`的方式。

代码很简单:
```javascript
if (flvjs.isSupported()) {
    var videoElement = document.getElementById('player');
    var flvPlayer = flvjs.createPlayer({
        type: 'flv',
        isLive: true,
        cors: true,
        url: 'http://localhost:2000/live/test.flv' //直播地址没有问题，已用Flash测试过。
    });
    flvPlayer.attachMediaElement(videoElement);
    flvPlayer.load();
    flvPlayer.play();
}
```

**错误如下**：

![image](https://cloud.githubusercontent.com/assets/5742670/25064451/a1660c8c-222c-11e7-9f82-47a9387eae8d.png)

本人对协议一窍不通，请问一下可能的错误原因是什么，OBS还是MonaServer里配置是否有没弄对的地方，如何解决。

**Comment by xqq** [comment]
onMetaData里有错误/标准中没有的type=17变量，导致onMetaData解析失败

**Comment by WangJi** [comment]
活马当死马医，尝试了一下
在`src\demux\amf-parser.js`里`219`行，改成如下：
```javascript
case 12: 
case 17:
    {  // Long string type
        let amfLongStr = AMF.parseString(arrayBuffer, dataOffset + 1, dataSize - 1);
        value = amfLongStr.data;
        offset += amfLongStr.size;
        break;
    }
```
现在可以跑了显示了，声音也没什么问题。
不管怎样，解决了。。。。

**Comment by xqq** [comment]
所以type=17是定义在哪个标准里的？

**Comment by WangJi** [comment]
@xqq  那你可难倒我了，我本来就对协议一点都不懂。
搜了一下，0x11可能是[AMF3](http://wwwimages.adobe.com/www.adobe.com/content/dam/Adobe/en/devnet/amf/pdf/amf-file-format-spec.pdf)的。

从13-17目前都有定义:
> VectorInt - 0x0D
VectorUInt - 0x0E
VectorDouble - 0x0F
VectorObject - 0x10
Dictionary - 0x11

**Comment by xqq** [comment]
果然是AMF3

**Comment by WangJi** [comment]
那么现在`flv.js`支持AMF3吗？

**Comment by xqq** [comment]
不支持。AMF3应该只用在了rtmp里，flv onMetaData我从没遇到过超出AMF0的。
回去再调查下
