### ISSUE TITLE
手機裝置 Chrome 瀏灠器載入flv後僅顯示視頻畫面後, 便無法持續播放視頻

### ISSUE THREAD

**Issue by janyo1201** [Bilibili/flv.js#129]
flv.js 版本v1.2.0 
手機版本chrome version 57.0 在載入flv後僅顯示視頻畫面後, 便無法持續播放視頻。
使用 Iphone safari 僅顯示播放的按鈕，無法播放視頻
使用 手機版本 Firefox 52.0.2，可以正常播放
請問有什麼地方可以設定調整？

os -> ubuntu 16.04.2
http server -> nginx 1.5
Node.js ->v7

**Comment by janyo1201** [comment]
我透过vediojs-flvjs plugin 目前可以在手机版chrome(version 57.0.2987.132), firefox(version 52.0.2) 执行播放了，但在iphone 6s safari 上还是出现" no compatible source was found for this media " , 这个错误讯息.

**Comment by xqq** [comment]
ios不支持Media Source Extensions，故无解
