### ISSUE TITLE
[TransmuxingController] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 2

### ISSUE THREAD

**Issue by xxfaxy** [Bilibili/flv.js#132]
![1](https://cloud.githubusercontent.com/assets/3325895/25304487/d6006e7e-279a-11e7-8d29-faa4d4d81ad5.png)
![Uploading 1.png…]()

**Comment by xqq** [comment]
unsupported h263 codec
duplicated #37 #47

**Comment by KrisRoofe** [comment]
Not H264+AAC
