### ISSUE TITLE
Can video-only streams be played by flv.js?

### ISSUE THREAD

**Issue by hxl-dy** [Bilibili/flv.js#133]
i have a video-only stream, flv.js can get it but cannot play it.

**Comment by xqq** [comment]
Audio only or video only stream is supported,
But you need explicitly indicate `hasAudio: false` in onMetaData structure or in FLV header.

**Comment by hxl-dy** [comment]
do you mean: if i use ffmpeg to push a stream to srs, i should add `-metadata "hasAudio=false"` option?

**Comment by xqq** [comment]
its worth to try

**Comment by xqq** [comment]
Improved in #135 
Now Indicates `hasAudio: false` in `MediaDataSource` structure should got it works

**Comment by hxl-dy** [comment]
thanks, it works.

**Comment by zhatongning** [comment]
@xqq  I indicated `hasVideo: false, hasAudio: true` in `MediaDataSource` structure, it worked. But It took more than ten second to play. Is it possible to shorten the time?
