### ISSUE TITLE
请问是否可以在播放视频的时候关闭音频

### ISSUE THREAD

**Issue by Yingkaixiang** [Bilibili/flv.js#139]
我在api文档里没有找到相关的关闭或开启音频的接口

**Comment by xqq** [comment]
三种方法
1. 静音
2. attach到HTMLAudioElement
3. MediaDataSource里指定hasAudio: false

**Comment by Yingkaixiang** [comment]
您好，我指定了hasAudio: false但是依然有声音是不是和我的流有关系

2017-04-26 18:18 GMT+08:00 xqq <notifications@github.com>:

**Comment by xqq** [comment]
用master上最新代码

**Comment by Yingkaixiang** [comment]
谢谢，已解决

**Comment by Yingkaixiang** [comment]
您好，请问是否我初始化播放器时将hasAudio参数设置为false后，就没有办法再打开音频了，必须要销毁当前的播放器重新初始化一个新的播放器。我在文档中没有找到开关音频的方法。

2017-04-27 17:11 GMT+08:00 xqq <notifications@github.com>:

**Comment by xqq** [comment]
静音不行吗？

**Comment by Yingkaixiang** [comment]
了解了，多谢。
