### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by codehehe** [Bilibili/flv.js#14]
I create player like this:
```
flvjs.createPlayer(mediaDataSource, {
    enableWorker: false,
    lazyLoadMaxDuration: 3 * 60,
    seekType: 'range',
    cors: true,
    isLive: true
});
```
but when i load flv stream, an error log print in console:
`No 'Access-Control-Allow-Origin' header is present on the requested resource.`
what can i do for this error?

**Comment by KiritoCheng** [comment]
跨域问题，添加response.setHeader("Access-Control-Allow-Origin", "*")

**Comment by xqq** [comment]
See cors.md
https://github.com/Bilibili/flv.js/blob/master/docs/cors.md
