### ISSUE TITLE
怎么在视频结束的时候回调方法,进行结束的处理

### ISSUE THREAD

**Issue by WEBSFAN** [Bilibili/flv.js#144]
视频结束的时候控制台会打印消息MediaSource onSourceEnded，请问一下这个是怎么调用那个方法的

**Comment by xqq** [comment]
这是缓冲到末尾并且 append 完毕，不是播放结束.

缓冲完毕有 `flvjs.Events.LOADING_COMPLETE` 事件，通过 on 方法把回调绑在 flvplayer 实例上.

**Comment by aimeiyijia** [comment]
未正常触发怎么办
