### ISSUE TITLE
是否支持可以外挂srt字幕

### ISSUE THREAD

**Issue by An0nymous0** [Bilibili/flv.js#145]
是否支持可以外挂srt字幕

**Comment by xqq** [comment]
自己写引擎吧

**Comment by yushih** [comment]
我正好做过一个，在浏览器窗口输入
`javascript:var script=document.createElement("script");script.src="http://yushi.bitbucket.io/subtitle.dist.js",document.body.appendChild(script);void(0)`
就可以了。希望对楼主有用。
