### ISSUE TITLE
mp4 h264 按关键帧导入数据没有画面

### ISSUE THREAD

**Issue by yu305306** [Bilibili/flv.js#151]
pps sps 都正确 用网页的查找型号 对应，按关键帧 _remuxVideo 进去，没有导入声音。 一直给onSourceBufferUpdateEnd，没有看到抛出 error错误，但是没有看到第一帧画面 在buffered 里面看到  end 有数据。 求教在哪个位置可能出现的问题比较大。

**Comment by xqq** [comment]
buffered.start()多少？

起始时间戳距0太远了吧，手工把currentTime打过去试试

**Comment by yu305306** [comment]
start 为0     curtime 也为0   第一帧的dts 为0 有ctts box 的cdt

**Comment by yu305306** [comment]
感谢作者的分享，mp4 .h264格式的转封装 成功，不是currentTime 问题 。是 我把 sound 的 _mediaSource.addSourceBuffer  加进去没有添加声音数据导致  不能播，谢谢
