### ISSUE TITLE
Load a new FLV

### ISSUE THREAD

**Issue by rafa8626** [Bilibili/flv.js#155]
Currently, I have a FLV that loads initially on my page, but the user has the ability to select another FLV clicking a button. How can I achieve this, since the `attachMediaElement` and `load` methods have been called? I tried to use the following sequence on my button callback but no luck:
```javascript
button.addEventListener('click', function() {
     var video = document.querySelector('video');
     video.src = '[MY FLV].flv';
     flvPlayer.unload();
     flvPlayer.detachMediaElement();
     flvPlayer.attachMediaElement(video);						
     flvPlayer.load();
     setTimeout(function() {
         flvPlayer.play();
     }, 250);
});
```
Thanks for any hints

**Comment by xqq** [comment]
A new flvPlayer instance should be created with another FLV url.
You can destroy the previous flvPlayer, create a new instance, then attach to the same video element.

BTW, it's better to call play() in video's first `canplay` event fired.

**Comment by rafa8626** [comment]
Thanks a lot. It worked!
