### ISSUE TITLE
windows chrome/火狐都无法支持http2.0协议 flv流

### ISSUE THREAD

**Issue by dongyang03** [Bilibili/flv.js#156]
如题，在windows上 http2.0 flv的流被转为http1.1。mac 正常。

**Comment by xqq** [comment]
转成1.1是啥意思

**Comment by dongyang03** [comment]
流的地址 https://xxx.com/xxx/stream-6423974505114241794_250.flv 是一个http2.0的协议。
在mac上 chrome 58 版本 同时生成10个播放器，同时播放，没有问题，并且 浏览器network的 protocol里显示http2.0。

在windows 10 系统上，用chrome58， http2.0并没有生效。浏览器network里protocol变成了 http1.1。这样就只能同时播放6个视频，无法并发多个视频。

**Comment by dongyang03** [comment]
@xqq 
mac 上效果
[https://img.yzcdn.cn/upload_files/2017/05/25/Fkb2rCX1NW1lOTIMOwzziY0lXr3_.png?imageView2/2/w/730/h/0/q/75/format/webp](url)

window上效果，请求被挂起，flv流被降级到http1.1，jquery cnd的http2.0就生效着

[https://img.yzcdn.cn/upload_files/2017/05/25/FqvDh3g7rMPlZPVdSzLqORw4KxPp.png?imageView2/2/w/730/h/0/q/75/format/webp](url)

**Comment by dongyang03** [comment]
@xqq 上面是图片地址，需要复制出来再打开

**Comment by xqq** [comment]
原因不明，不过肯定和 flv.js 没关系

**Comment by dongyang03** [comment]
可以关闭了，是流厂商提供的http2.0基于NPN 协议，而NPN协议在高版本的chrome浏览器被放弃了。
