### ISSUE TITLE
More than one instance of the player in the same page?

### ISSUE THREAD

**Issue by rafa8626** [Bilibili/flv.js#157]
I've tried to add 2 FLV videos on the same page; however, seems that it renders the last video on both instances. This is what I'm doing:
```javascript
var mediaElements = document.querySelectorAll('video'), i, total = mediaElements.length;
for (i = 0; i < total; i++) {
     flvjs.LoggingControl.enableDebug = false;
     flvjs.LoggingControl.enableVerbose = false;
     var player = flvjs.createPlayer({
         type: 'flv',
         url: mediaElements[i].src
     });
     player.attachMediaElement(mediaElements[i]);
     player.load();
}
```
Any hints to solve my issue? Thanks in advance

**Comment by xqq** [comment]
Seems that you have attached 2 flvplayer instance to the same `node`?

**Comment by rafa8626** [comment]
Sorry I fixed that typo, but still no luck

**Comment by rafa8626** [comment]
Nevermind, I figured what happened. There was another piece of Javascript modifying the sources. I removed that and it works now. Thanks

**Comment by xqq** [comment]
flv.js supports multiple instance. There's no limitations on instance count.

**Comment by jiankafei** [comment]
I can not speak English. But i konw this.
for (var i = 0; i < 2; i++) {
	var a = i;
}
console.log(a);  // 1

**Comment by jiankafei** [comment]
Only ES6 has a block-level scope

**Comment by Adtechmd** [comment]
It's a little bit of a problem when it comes to logging. I can not seem to find to which player refers the error message in case i have multiple instances.
