### ISSUE TITLE
websoket flv直播怎么监听是否断线？

### ISSUE THREAD

**Issue by Panhaiwei** [Bilibili/flv.js#158]
怎么监测是否断线？

**Comment by xqq** [comment]
先观察断线时会触发什么错误，然后做对应的错误处理

**Comment by Panhaiwei** [comment]
@xqq webscoket flv直播流断线之后，没有打印错误也没有触发错误，但是使用未压缩的版本（flv.js）时，日志打印会停止，重新连接设备后自动重连继续打印日志。

**Comment by Panhaiwei** [comment]
@xqq 监听什么事件可以得到错误信息

**Comment by xqq** [comment]
flvplayer.on(flvjs.Events.ERROR, listener)
