### ISSUE TITLE
快进播放，出现跨越问题

### ISSUE THREAD

**Issue by babymaychen** [Bilibili/flv.js#159]
**Fetch API cannot load http://XXX:8880/jxwyV07-metadata.flv. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8181' is therefore not allowed access. The response had HTTP status code 405. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.**

拖动进度条快进，就会出现上述问题，但是正常播放就没有跨域问题，而且server端也添加了配置项
![qq 20170531092016](https://cloud.githubusercontent.com/assets/6678609/26611697/7434510e-45e2-11e7-97f9-2e42686f144e.png)

**Comment by xqq** [comment]
405是nginx没配置OPTIONS请求，参考cors.md

**Comment by babymaychen** [comment]
Access-Control-Allow-Methods: OPTIONS 
这个有啊

**Comment by xqq** [comment]
OPTIONS请求，相对GET POST

**Comment by babymaychen** [comment]
ok，好用了

**Comment by melodysummer** [comment]
那是需要server上配置options吗 @xqq 
怎么配？

**Comment by melodysummer** [comment]
@xqq 
我用chrome插件对response header设置了必要的头
 {name: 'Access-Control-Allow-Methods', value: 'GET, OPTIONS'},
{name: 'Access-Control-Request-Headers', value: 'range'},
 {name: 'Access-Control-Allow-Origin', value: '*'}
并且statusCode设置了200.

但是flv.js接收后还是报错
self.fetch(seekConfig.url, params).then(function (res) {})
.catch(e)
catch捕获到e.message "Failed to fetch".

难道它不是获取的我修改过的响应头吗 为什么还会报错呢

**Comment by melodysummer** [comment]
![a](https://user-images.githubusercontent.com/25784493/40225422-8da78eb4-5abb-11e8-905a-1f7c685fda70.png)
@xqq  错误如上，虽然我设置了必要的响应头 还是会提示http code 405. 好像是设置了但是无效

**Comment by xqq** [comment]
因为 405 意思是服务端不支持这个 Method 于是没有正确响应啊

**Comment by StartAt24** [comment]
```
location ~ \.flv {
            root   record;                                  # 标识文件的根目录
            flv;
      
            # 解决跨域问题
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain charset=UTF-8';
                add_header 'Content-Length' 0;
                return 204;
            }

            if ($request_method = 'POST') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
            }

            if ($request_method = 'GET') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
            }  
        } 
```
nginx如上配置可以解决拖动跨域问题。
