### ISSUE TITLE
Support for Airplay control

### ISSUE THREAD

**Issue by xiao99xiao** [Bilibili/flv.js#16]
Currently the player provides no support for Airplay control. I suggest display an airplay button when there is a Airplay device detected, like what dailymotion's player does.

Safari provides a event called `WebKitPlaybackTargetAvailabilityEvent` and it's easy to use.

Documents:
https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_9_0.html#//apple_ref/doc/uid/TP40014305-CH9-SW16

**Comment by xqq** [comment]
This is not a duty of a player engine which should be done in business/UI logic.

You can write your own playback page to implement this feature.
