### ISSUE TITLE
flv延时问题

### ISSUE THREAD

**Issue by Lirui072037** [Bilibili/flv.js#160]
@xqq  可以告诉我下 flv可以设置控制延时吗？

**Comment by xqq** [comment]
没有。要低延迟可以开enableStashBuffer: false

**Comment by Lirui072037** [comment]
好的 谢谢！后面有方法可以让它控制在几秒之内延时吗？

**Comment by xqq** [comment]
没有

**Comment by Lirui072037** [comment]
哦，那设置了这个enableStashBuffer: false  之后最低能控制在几秒之内？

**Comment by xqq** [comment]
不知道

**Comment by neoedmund** [comment]
Hi, 我加了enableStashBuffer: false 没有太大改变, 延迟在5秒左右. 有点大. 
不知道怎么回事?
