### ISSUE TITLE
Edge浏览器无法播放直播流

### ISSUE THREAD

**Issue by dongyang03** [Bilibili/flv.js#161]
1.edge版本 Microsoft Edge 38.14393.1066.0
2.现象： 流被挂起 ，在chrome上没有问题
[http://kityminder-img.gz.bcebos.com/9f4a772b6391a11a21041bd8c941f5fceb0b6cf4](url)

**Comment by dongyang03** [comment]
上面的截图地址需要复制打开

**Comment by xqq** [comment]
需要 15048+，也就是 Creator Update
原因是 fetch API 损坏  https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8196907/

**Comment by dongyang03** [comment]
感谢 @xqq

Edge需要和win10 一起更新，+win10更新方法 [https://www.microsoft.com/zh-cn/software-download/windows10](url)

**Comment by xqq** [comment]
如果要全平台支持那只有走websocket了

**Comment by Erik5169** [comment]
1. win10 edge版本 Microsoft Edge 44.18362.387.0
2. 播放器能创建， 但是不能播放视频，显示一直在加载， 其它浏览器都正常
