### ISSUE TITLE
appendBuffer 的相关问题

### ISSUE THREAD

**Issue by yu305306** [Bilibili/flv.js#162]
请问，如果比较大的视频，加载时候  如果 视频比较大 在appendBuffer 一定的数量级的时候 就不能放进去，有没有什么方法可以清一部分 buffer 的数据 再放入 appendBuffer 的方法么。或者思路之类的，占时没有考虑把视频分片切。

**Comment by xqq** [comment]
那只能把一开始append进去的先清掉，SourceBuffer.remove()
