### ISSUE TITLE
求助qwq，只能播放mp4格式，不能播放flv格式

### ISSUE THREAD

**Issue by chengyu2333** [Bilibili/flv.js#171]
http://233.213.name/flv/index.html
http://233.213.name/flv/sim.html
编译成功后，第一个demo只能播放mp4格式，不能播放flv格式，而第二个各种报错。折腾好久还是不知道哪的问题QAQ

**Comment by chengyu2333** [comment]
CORS头也配置好了的，是flv格式不标准么？这个flv是用as3生成的

**Comment by xqq** [comment]
demo里那个文本框填的是MediaDataSource json地址

**Comment by chengyu2333** [comment]
我觉得不是地址填错的问题
if (flvjs.isSupported()) {
        var videoElement = document.getElementById('videoElement');
        var flvPlayer = flvjs.createPlayer({
            type: 'mp4',
            url: 'test1.mp4'
        });
        flvPlayer.attachMediaElement(videoElement);
        flvPlayer.load();
        flvPlayer.play();
    }
↑↑↑这样是可以播放mp4的
if (flvjs.isSupported()) {
        var videoElement = document.getElementById('videoElement');
        var flvPlayer = flvjs.createPlayer({
            type: 'flv',
            url: 'test1.flv'
        });
        flvPlayer.attachMediaElement(videoElement);
        flvPlayer.load();
        flvPlayer.play();
    }
↑↑↑这样写播放不了flv，报很多类似这样的错误
logger.js:32 [TransmuxingController] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 4
events.js:62 Uncaught (in promise) Error: Uncaught, unspecified "error" event. (MediaError)
    at EventEmitter.emit (events.js:62)
    at EventEmitter.<anonymous> (flv-player.js:239)
    at EventEmitter.emit (events.js:84)
    at transmuxer.js:181

**Comment by xqq** [comment]
字面意思啊，不受支持的音视频编码，仅支持H264+AAC/MP3

**Comment by chengyu2333** [comment]
还真是视频格式问题...看来只能在后端直接编码成MP4格式了，谢谢大佬指点=3=
