### ISSUE TITLE
es6 里面如何使用 worker 

### ISSUE THREAD

**Issue by yu305306** [Bilibili/flv.js#172]
es6 里面如何使用 worker ，我用传统的 worker 发现 后面的 不进行webpack 打包，报错了。 如果放到深点的文件夹 worker 在用import 指向的地址文件夹地址少了几层。  在 webworkify npm 那个例子又跑不通。
请问有什么资料或者插件可以了解的么

**Comment by xqq** [comment]
看说明 webworkify 是专门针对 browserify 做的，不支持 webpack
