### ISSUE TITLE
直播延时随时间的增长而增长

### ISSUE THREAD

**Issue by joastonish** [Bilibili/flv.js#173]
我用flv.js +livego+chrome测试，显示结果是第一次打开延时1s ，开2个小时以后延时10s。。。本来以为是livego的问题，但是我把chrome关闭再打开延时就是1s，所以应该是flv.js的问题。有遇到过的小伙伴么？

**Comment by xqq** [comment]
先不要disable stash buffer

**Comment by joastonish** [comment]
var element = document.getElementsByName('videoElement')[0];
    console.log('isSupported: ' + flvjs.isSupported());
    player = flvjs.createPlayer({
        type: 'flv',
        url:  'http://192.168.35.178:7001/live/NVR02/1.flv'
    });
    player.attachMediaElement(element);
    player.load();

我用的demo的代码。啥都没改

**Comment by xqq** [comment]
检查f12 logcat，检查chrome://media-internals

**Comment by joastonish** [comment]
Large timestamp gap detected; may cause AV sync to drift. time:207734000us expected:207670000us delta:64000us..很多这个错误。如何解决啊大神

**Comment by xqq** [comment]
音频轨时间戳不正确，以及你用最新版本了么

**Comment by joastonish** [comment]
可以了。用了最新版的就好了。非常感谢
