### ISSUE TITLE
清除已经缓冲的buffered

### ISSUE THREAD

**Issue by songguangyu** [Bilibili/flv.js#177]
@xqq 请问在buffer full 的情况下 怎么清除已经缓存在mse里的缓存呢？谢谢

**Comment by xqq** [comment]
https://github.com/Bilibili/flv.js/commit/43534eb8f143cfe27fe624d4a1d1f03ee7ef3aa3

**Comment by songguangyu** [comment]
感谢！

**Comment by songguangyu** [comment]
@xqq  qq好：
我看 needCleanupSourceBuffer
buffered.length >= 1  才会清楚 buffer
但是如果 一个buffered 的length非常长，把buffer沾满了 
这种情况是不是没有考虑？

**Comment by xqq** [comment]
length是区间个数 正常是一个

**Comment by songguangyu** [comment]
sorry 是我理解错了 thk
