### ISSUE TITLE
无法直播，求帮助

### ISSUE THREAD

**Issue by arashilan** [Bilibili/flv.js#178]
以下我用别人的DEMO，但无法播放直播，请帮助：
`<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8" />
<script src="http://cdn.bootcss.com/flv.js/1.3.0/flv.min.js"></script>
<title>flv.js测试</title>
<script type="text/javascript">
			window.onload = function () {
				if (flvjs.isSupported()) {
					var videoElement = document.getElementById('flv_test_div');
					var flvPlayer = flvjs.createPlayer({
							type : 'flv',
							url : 'http://fms.cntv.lxdns.com/live/flv/channel50.flv'
						}, {
							enableWorker : true,
							isLive : true
						}); 
					flvPlayer.attachMediaElement(videoElement);
					flvPlayer.load();
					flvPlayer.play();
				}
			}
</script>			
</head>
<body>
<div id="tdiv" style="width:600px;height:400px">
<h4>DEMO-FLV直播流</h4>
<video id="flv_test_div" style="width:100%;height:100%"></video>
</div>
</body>
</html>`

**Comment by xqq** [comment]
need more info

**Comment by arashilan** [comment]
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8" />
<script src="http://cdn.bootcss.com/flv.js/1.3.0/flv.min.js"></script>
<title>flv.js测试</title>
<script type="text/javascript">
			window.onload = function () {
				if (flvjs.isSupported()) {
					var videoElement = document.getElementById('flv_test_div');
					var flvPlayer = flvjs.createPlayer({
							type : 'flv',
							url : 'http://fms.cntv.lxdns.com/live/flv/channel50.flv'
						}, {
							enableWorker : true,
							isLive : true
						}); 
					flvPlayer.attachMediaElement(videoElement);
					flvPlayer.load();
					flvPlayer.play();
				}
			}
</script>			
</head>
<body>
<div id="tdiv" style="width:600px;height:400px">
<h4>DEMO-FLV直播流</h4>
<video id="flv_test_div" style="width:100%;height:100%"></video>
</div>
</body>
</html>

**Comment by arashilan** [comment]
前端页面引用flv.js 来播放例如CCTV的直播流：

!DOCTYPE html
html lang="zh-CN"
head
meta charset="utf-8" /
script src="http://cdn.bootcss.com/flv.js/1.3.0/flv.min.js" </script>
title>flv.js Test </title>
script type="text/javascript"
			window.onload = function () {
				if (flvjs.isSupported()) {
					var videoElement = document.getElementById('flv_test_div');
					var flvPlayer = flvjs.createPlayer({
							type : 'flv',
							url : 'http://fms.cntv.lxdns.com/live/flv/channel50.flv'
						}, {
							enableWorker : true,
							isLive : true
						}); 
					flvPlayer.attachMediaElement(videoElement);
					flvPlayer.play();
				}
			}
/script			
/head
body
div id="tdiv" style="width:600px;height:400px"
h4>DEMO-FLV?-Test</h4
video id="flv_test_div" style="width:100%;height:100%" </video>
/div
/body
/html

**Comment by xqq** [comment]
你倒是给错误信息啊

**Comment by arashilan** [comment]
问题是没错误信息，就是白屏

**Comment by xqq** [comment]
缺少 'Access-Control-Allow-Origin' 头

**Comment by arashilan** [comment]
是对方直播流服务器禁止远程访问吗？

**Comment by xqq** [comment]
仔细读 README

**Comment by arashilan** [comment]
[MSEController] > MediaSource onSourceOpen  flv.js:11233:13
[IOController] > Loader error, code = -1, msg = ProgressEvent error  flv.js:11166:17
	e http://cdn.bootcss.com/flv.js/1.3.0/flv.js:11166:17
	_onLoaderError http://cdn.bootcss.com/flv.js/1.3.0/flv.js:6791:13
	_onXhrError http://cdn.bootcss.com/flv.js/1.3.0/flv.js:7808:17
[TransmuxingController] > IOException: type = Exception, code = -1, msg = ProgressEvent error  flv.js:11166:17
	e http://cdn.bootcss.com/flv.js/1.3.0/flv.js:11166:17
	_onIOException http://cdn.bootcss.com/flv.js/1.3.0/flv.js:3560:13
	_onLoaderError http://cdn.bootcss.com/flv.js/1.3.0/flv.js:6829:17
	_onXhrError http://cdn.bootcss.com/flv.js/1.3.0/flv.js:7808:17

**Comment by zhengrenzhe** [comment]
这个label厉害了

**Comment by SkyHarute** [comment]
厉害了,我的哥

**Comment by zhuweiyou** [comment]
围观

**Comment by deatil** [comment]
围观，同源策略吧

**Comment by ChuanyuXue** [comment]
知乎观光团

**Comment by GravityMsc** [comment]
知乎观光团···

**Comment by fansmc** [comment]
好惨...

**Comment by BYChoo** [comment]
知乎观光团

**Comment by gogoatomdev** [comment]
~

**Comment by mumukun** [comment]
围观

**Comment by ToiletCommander** [comment]
知乎观光团

**Comment by cnds** [comment]
我是来围观的

**Comment by ChaoSBYNN** [comment]
围观

**Comment by HankXV** [comment]
知乎观光团

**Comment by KKKits** [comment]
知乎观光团

**Comment by adu4862** [comment]
知乎观光团

**Comment by Lynnliness** [comment]
知乎观光团

**Comment by arashilan** [comment]
我不懂开发，我尊敬程序员，既然不想回答小白问题就不必回答，我用videojs实现了直播，至少有很多js的使用手册写的要完整。谢谢；

**Comment by yangzuwei** [comment]
知乎观光团到此一游

**Comment by BDZNH** [comment]
这样是不是不太好😑
不过好搞笑

**Comment by cdll** [comment]
前排～

**Comment by xqq** [comment]
CORS有专门写一份文档，README里也强调过了要配CORS头
