### ISSUE TITLE
无法播放视频直播流，看报错似乎是转码失败了，求大神帮忙看看，谢谢。

### ISSUE THREAD

**Issue by 469376974** [Bilibili/flv.js#181]
![qq](https://user-images.githubusercontent.com/17610895/28002083-61655aa4-6564-11e7-8281-dfee2f6870c2.png)

**Comment by 469376974** [comment]
用视频播放器是能够直接播放的

**Comment by xqq** [comment]
Unsupported H263

**Comment by 469376974** [comment]
ok，thank you

**Comment by 469376974** [comment]
@xqq flv.js  support h265？

**Comment by xqq** [comment]
浏览器不支持

**Comment by nanguantong** [comment]
已经支持flv h265，移步至：https://github.com/nanguantong/flv-h265.js
