### ISSUE TITLE
flv不能播放，求解。。

### ISSUE THREAD

**Issue by wjw-gavin** [bilibili/flv.js#182]
下面是我的代码
![image](https://user-images.githubusercontent.com/19986739/28062193-b6c54cce-665f-11e7-9f11-4d8ec39ad16d.png)

运行后报错：
![image](https://user-images.githubusercontent.com/19986739/28062011-2bc03e40-665f-11e7-83a1-a402189d9468.png)

**Comment by xqq** [comment]
chrome://media-internals 贴logcat

**Comment by SweetJun** [comment]
![image](https://user-images.githubusercontent.com/19986739/28064015-b4ac105c-6665-11e7-82a4-bec28c437c66.png)

**Comment by xqq** [comment]
自己检查流，可以用ffmpeg

**Comment by SweetJun** [comment]
好的，谢谢！

**Comment by h371535926** [comment]
![tim 20180329151522](https://user-images.githubusercontent.com/22046412/38075236-43fa9e4c-3364-11e8-983c-b5b6779589c7.png)
@xqq 大神，为什么这个解析用的是GPU，有的电脑可以播放，有的电脑不行呢？

**Comment by xqq** [comment]
流有问题，和什么电脑无关吧
