### ISSUE TITLE
如何获取视频播放完毕信息

### ISSUE THREAD

**Issue by yu305306** [Bilibili/flv.js#185]
如何获取视频播放完毕信息，我看video.onended       MediaSource.sourceclose          MediaSource.abort在播放结束都不会弹的， 还发现 在大视频下dts 偏大情况下 的cruttenTime不太准 可能我做了偏移量偏差导致 最后时间有时候会差一点点。   _(:з」∠)_

**Comment by xqq** [comment]
video标签ended事件

**Comment by yu305306** [comment]
找到不会触发原因了是MediaSource 要触发停止才会回调 ended=》true
