### ISSUE TITLE
请问flv.js在高版本的chrome是如何做到组装FMP4提交时没有IDR帧而不黑屏？

### ISSUE THREAD

**Issue by wenRC** [Bilibili/flv.js#187]
在chrome 59中，提交的fmp4没有IDR帧也能正常播放，但一旦网络不好，比如前面提交的FMP4有IDR帧，但延迟三秒后，下一个没有IDR帧的FMP4才提交，就会造成黑屏。
而且seek到上面没有IDR帧的fmp4时也会黑屏。
这个问题只在chrome中出现，firefox没有问题。
粗略的看了下hls.js，没找到相关代码。

用的是hls.js，ts转fmp4播放，但最终都是把H.264编码的fmp4提交，所以这里应该是没区别的吧。
谢谢

**Comment by xqq** [comment]
建议检查 hls.js 是否为了保证每个 fmp4 都以 IDR 帧开始而做了填充黑色空白帧之类的 workaround。
原则上讲 MSE 是不要求每个 fmp4 里一定要有 IDR/I 帧的，只要和前后的 fmp4 连贯起来是正常的流

而 chrome 对于 fmp4 中要有 IDR 的限制是在 chrome 50 以前，要求每个 fmp4 必须以 IDR 开始
flv.js 绕过了这一限制 https://github.com/Bilibili/flv.js/blob/master/src/remux/mp4-remuxer.js#L610

**Comment by xqq** [comment]
或者是延迟3秒之前m3u8里出现了流结束标记？

**Comment by wenRC** [comment]
@xqq 感谢大神，原因找到了，hls.js对chrome的任何版本都认为要IDR帧提交，没有像flv.js那样对版本进行判断就直接加了这两行代码。
        flags.dependsOn = 2;
        flags.isNonSync = 0;
十分感谢！

**Comment by wenRC** [comment]
这两行代码应该是让浏览器的播放器认为每次提交的一定是IDR帧开头的，进行一下版本判定就OK了

**Comment by xqq** [comment]
```js
this._forceFirstIDR = (Browser.chrome &&
                      (Browser.version.major < 50 ||
                      (Browser.version.major === 50 && Browser.version.build < 2661))) ? true : false;
```

以这个版本为分界就ok

**Comment by wenRC** [comment]
是的 谢谢~
