### ISSUE TITLE
推flv流偶尔成功

### ISSUE THREAD

**Issue by FingerRec** [Bilibili/flv.js#189]
请问怎么给flv.js推flv流，用RMTP提示不支持，看了md说明用websocket转发了之后也不播放。 测试了很多次只有一次成功推流，非常纳闷。 其它时候都提示

#  **Non-FLV, Unsupported media type!**
而用ffmpeg确实是从摄像头推的flv流，具体过程如下：

STEP1:开启 8081端口：监听fvi流 

STEP2:开启8082端口： 等待websocket链接 ，转发到html

STEP3:bash推流：
`ffmpeg -f avfoundation  -framerate 30 -i "0" -vcodec h264 -acodec aac -f flv http://localhost:8081/supersecret`

STEP4:
开启http-server,用来访问本地html界面，如下

代码：
`
<script src="../dist/flv.min.js"></script>
<video id="videoElement"></video>
<script>
    if (flvjs.isSupported()) {
        var videoElement = document.getElementById('videoElement');
        var flvPlayer = flvjs.createPlayer({
            type: 'flv',
            "isLive": true,
          //  url: 'rtmp://192.168.2.100/myapp/test1'
             url: ('ws://127.0.0.1:8082/')
        });
        flvPlayer.attachMediaElement(videoElement);
        flvPlayer.load();
        flvPlayer.play();
    }
</script>
`

**Comment by xqq** [comment]
流里收到的含有其它数据，不是纯flv流

**Comment by FingerRec** [comment]
你好！ 请问如果ffmpeg推流不纯的话，要用什么方式才能得到纯flv流呢。

**Comment by xqq** [comment]
我是指你websocket流里似乎有rtmp握手的各种包？

**Comment by ondev** [comment]
杂关闭了，都还没有解决方法呢。
