### ISSUE TITLE
不支持直播吗?

### ISSUE THREAD

**Issue by ccallcn** [Bilibili/flv.js#19]
测试了一下,点播flv一切正常,直播时用srs做服务器,obs推流一直没有成功,原因不详;
代码如下:
    if (flvjs.isSupported()) {
        var videoElement = document.getElementById('my-video');
        var flvPlayer = flvjs.createPlayer({
            type: 'flv',
            isLive: true,
            url: 'http://127.0.0.1:8088/hls/111111.flv'
        });
        flvPlayer.attachMediaElement(videoElement);
        flvPlayer.load();
        flvPlayer.play();
    }

**Comment by xqq** [comment]
检查F12 Console输出是否有错误信息
