### ISSUE TITLE
为什么不支持在移动端播放呢？

### ISSUE THREAD

**Issue by spfan** [Bilibili/flv.js#192]

**Comment by Anduin2017** [comment]
By my test it was really supported to play any flv video on any phone which supports HTML5. Well you have any detail about your device and browser?

**Comment by xqq** [comment]
iOS Safari 不支持 MSE
腾讯X5不支持 MSE
等等等等

**Comment by spfan** [comment]
需要移动端支持MSE才可以，目前只有安卓4.4.4以后支持。
http://caniuse.com/#search=mse
