### ISSUE TITLE
A minor problem about flv.d.ts

### ISSUE THREAD

**Issue by plantain-00** [Bilibili/flv.js#2]
It should be in package.json, like:
```
"types": "./d.ts/flv.d.ts"
```
After that, typescript compiler can recognise the type definition file.

Doc link: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/declaration%20files/Publishing.md#including-declarations-in-your-npm-package

**Comment by xqq** [comment]
Added https://github.com/Bilibili/flv.js/commit/382b26771325c69cb068cc5a40a93600bcb679c0
