### ISSUE TITLE
加速后可能会音画不同步

### ISSUE THREAD

**Issue by qiansen1386** [Bilibili/flv.js#20]
请问 H5 播放器现在用的是flv.js么？

我用了 Video Speed Control 对视频进行小幅加速之后 可能会出现音画不同步问题？声音快于画面。推测是硬件太羸弱导致掉帧。但是貌似B站的视频源的校对也不足。油管没有这个问题

**Comment by xqq** [comment]
请提供avid及你的系统平台信息（操作系统和浏览器版本）

另：bilibili主站播放器问题请走主站反馈渠道
