### ISSUE TITLE
self is not defined

### ISSUE THREAD

**Issue by haoguo** [Bilibili/flv.js#202]
similar with https://github.com/Bilibili/flv.js/issues/143
integrate with react and using server render.
it would raise 'self is not defined' at dist/src/utils/polyfill.js.

any idea of this?

**Comment by haoguo** [comment]
it works when i disabled server rendering.
I mean, is there any way to ignore this other than work around by disable server rendering

**Comment by xqq** [comment]
I know few about react.
The point is that flv.js is an front-end library, which is used for working inside a web browser.
