### ISSUE TITLE
Reading FLV continuously

### ISSUE THREAD

**Issue by sloosh** [Bilibili/flv.js#204]
Hi,

I have a server writing a FLV file continuously for live streaming. For example I can set the server to write up to 20 frames (or any other value) to the file, then it writes the file again with the 20 next frames, and so on....
I would like this FLV file to be consumed by flv.js in order to play live content.
But it seems the flv.js player stops to read the file once it reaches the end of has read the initial file size.

Is there a way to read such file continuously without interruption so I could read the FLV as live content ?
Otherwise, I could slit the FLV into multiple segments, but is there a way to define multiple segments without knowing how much segments there will be (because it is live content and segments are produced live) ?

Thanks for your help.

**Comment by xqq** [comment]
For http-flv live stream, the http response should be a continuous stream, which should not specify a length.
In other words the `Content-Length` header should not appear. Then pass all the data through the same http response.

**Comment by sloosh** [comment]
Alright thanks for your answer, I will try it.
