### ISSUE TITLE
How to use isLive configuration?

### ISSUE THREAD

**Issue by dbussert** [Bilibili/flv.js#205]
I'm testing with `Node-Media-Server` and `flv.js` plays live FLV and websocket with low latency without issue. The `flv.js` documentation says ```Indicates whether the data source is a **live stream**``` but from my testing I cannot see any difference when using isLive `true` or `false`.  Looking at the code, it doesn't appear this configuration is used anywhere, does it do anything?

**Comment by xqq** [comment]
![image](https://user-images.githubusercontent.com/4645762/30603530-bdf9fefc-9da2-11e7-9582-9910fbb047b1.png)
