### ISSUE TITLE
flv.js是否支持RTMP协议，如何从flv请求red5服务器上的视频流？

### ISSUE THREAD

**Issue by beigailiyang** [Bilibili/flv.js#207]
1.flv.js是否支持RTMP协议
2.flv.js是否支持Red5
3.flv.js如何请求red5视频服务器上的视频流

**Comment by ThreeFat** [comment]
flv.js并不支持RTMP，
flv.js只是通过获取流地址上的flv进行投喂，不区分媒体服务器，
flv.js只支持HTTP FLV协议。
