### ISSUE TITLE
websocket直播延迟非常大,而且不断积累.

### ISSUE THREAD

**Issue by xietianduo** [Bilibili/flv.js#215]
你好,

我写了个投屏的app,用flv.js显示.
两个问题:
1.websocket直播延迟非常大,而且不断积累.当flv tag发送比较频繁时候,延迟越来越大不断积累.
2.播放速度非常慢,1s只能处理100ms的画面.视频信息( Stream #0:0: Video: h264 (Baseline), yuv420p(progressive), 540x960, 5183 kb/s, 25 fps, 1k tbr, 1k tbn) PTS没有错误,换了几个浏览器跟PC都发生.

可能帮助分析的信息:
1.我确定app端发送的flv视频是没有问题的,我在PC接收app用ws传来的flv数据并将其保存成文件,文件正常播放.
2.将第一步保存的flv文件给flv.js播放也没有任何卡顿或者播放速度变慢

所以我怀疑可能是flv.js的bug,如果需要更多信息我会及时给你.
谢谢.

**Comment by ThreeFat** [comment]
是的,我在使用中也发现了,我的解决方式是将每当`bufferd.end(0) - currentTime > 3`, 把当前的`bufferd.end(0)`缓存时间秒,直接赋值给`currentTime`,来解决视频延迟越来越大的问题.不过这样做的坏处是,当延迟很频繁的超出你能容忍的时间时,画面回频繁的跳帧.

**Comment by xietianduo** [comment]
我发现最新v1.3.3似乎已经fix了

**Comment by BeiKeJieDeLiuLangMao** [comment]
我好像也遇到这个问题
我在直播视频中打开秒表，直播中要过2-3秒才能看到秒表过去1秒
你们是怎么设置player参数的呀

**Comment by Lilinjie01** [comment]
> 



> 你好,
> 
> 我写了个投屏的app,用flv.js显示. 两个问题: 1.websocket直播延迟非常大,而且不断积累.当flv tag发送比较频繁时候,延迟越来越大不断积累. 2.播放速度非常慢,1s只能处理100ms的画面.视频信息( Stream #0:0: Video: h264 (Baseline), yuv420p(progressive), 540x960, 5183 kb/s, 25 fps, 1k tbr, 1k tbn) PTS没有错误,换了几个浏览器跟PC都发生.
> 
> 可能帮助分析的信息: 1.我确定app端发送的flv视频是没有问题的,我在PC接收app用ws传来的flv数据并将其保存成文件,文件正常播放. 2.将第一步保存的flv文件给flv.js播放也没有任何卡顿或者播放速度变慢
> 
> 所以我怀疑可能是flv.js的bug,如果需要更多信息我会及时给你. 谢谢.

不一定是，我自己用mse api开发的播放器，也遇到了这样的问题，看了好多flv.js的issue也没有找到解决方案，目前就只能重置播放器才能消灭这些延时问题
