### ISSUE TITLE
播放器能暴露自定义设置HTTP Header的接口吗？

### ISSUE THREAD

**Issue by geniuszhou** [Bilibili/flv.js#219]
有些视频播放源有限制请求的header ,比如 User-Agent , HTTP-REFFER 等， 是否能暴露自定义设置http header的接口呢？

**Comment by xqq** [comment]
xhr和fetch确实可以加自定义header，但是UserAgent Referer这些属于被锁定的基本header，仅可由浏览器决定，js层无权干涉

**Comment by geniuszhou** [comment]
确实，之前用的vlc播放器也是锁定了user-agent 和 Referer ， 不过有时间话还是希望能够支持上自定义header的设置 😝😝

**Comment by xqq** [comment]
建议先了解CORS Preflight，前端加header会搞出一堆麻烦事

**Comment by jojolin** [comment]
我用的是chrome，通过插件扩展可以解决referer的问题
