### ISSUE TITLE
Can't play in Safari browser

### ISSUE THREAD

**Issue by jianwu** [Bilibili/flv.js#22]
When play in Safari, the player controller will always display "Loading". From the Network panel, we can see the flv file is continue downloading, but no video is displayed.

**Comment by xqq** [comment]
Minimum required Safari version is 10.0. The MSE implementation on Safari 9.x is complete broken.
HTTP FLV live stream is not supported on Safari because of the lost of stream IO.

**Comment by jianwu** [comment]
OK. Got it. Seems I face the problem because I'm using live stream.

**Comment by xqq** [comment]
You can test flv live stream under `Safari Technology Preview` which supports fetch + stream API.
https://developer.apple.com/safari/technology-preview/
But It cannot be considered completely stable for now.
