### ISSUE TITLE
没有音频的flv视频文件加载成功，但是无法播放

### ISSUE THREAD

**Issue by canglongxiang** [Bilibili/flv.js#224]
我传入了一个flv视频文件，并且加载成功，能够一直fetch视频流。但是因为这个视频源本身是没有音频输入的，所以flv.js就无法播放这个视频。

**Comment by xqq** [comment]
MediaDataSource.hasAudio = false

**Comment by canglongxiang** [comment]
这个设置是针对flv.js进行的吗？

**Comment by xqq** [comment]
yep
