### ISSUE TITLE
阿里云flv流跨域

### ISSUE THREAD

**Issue by jzqiu** [Bilibili/flv.js#225]
直播页面 http://ruhengai.com/live.html

Failed to load http://live.ruhengai.com/tcly/zww.flv?auth_key=1510066680-0-0-da6fadcc8fb1736f1905a21f6efe7179: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://ruhengai.com' is therefore not allowed access

crossdomain.xml 已放入
http://ruhengai.com/crossdomain.xml
http://live.ruhengai.com/crossdomain.xml

求大神指点下

**Comment by xqq** [comment]
crossdomain.xml是Flash的协议，不是一码事，自己看cors.md

**Comment by jzqiu** [comment]
阿里云 cors 配置，参见
https://help.aliyun.com/knowledge_detail/40183.html
