### ISSUE TITLE
firefox最新版本 用flv.js播放不了

### ISSUE THREAD

**Issue by QingshanLuoyue** [Bilibili/flv.js#229]
chrome和safari都可以播放，就ff不行，ff55版本和更新后的ff56都不行
![image](https://user-images.githubusercontent.com/19339834/32649740-c8c90936-c5c0-11e7-8944-2deda9576dce.png)
![image](https://user-images.githubusercontent.com/19339834/32649761-e032fff0-c5c0-11e7-97e6-fb08f749cd3a.png)

**Comment by xqq** [comment]
目前最新版firefox无此问题
