### ISSUE TITLE
通过npm引用flv.js,webpack打包之后包含ES6语法，并且未被压缩

### ISSUE THREAD

**Issue by BeiKeJieDeLiuLangMao** [Bilibili/flv.js#232]
因为WebPack中babel-loader一般的配置是不将/node_modules中的代码进行ES6->ES5转码，
而flv.js的package中"main": "./dist/flv.js",这个文件中包含ES6语法，
这就导致了项目转码之后仍然后ES6语法，并在之后的压缩过程中抛出“语法不支持”的异常，
其最终结果就是打包之后的vendor.js中既包含ES6语法的代码，而且没有进行压缩。
于是我将引用的方式由import flvjs from 'flv.js'变为 import flvjs from 'flv.js/dist/flv.min',这个问题就解决了。

**Comment by xqq** [comment]
```"main": "./dist/flv.js"```
这个是过了 babel 后经 browserify 打包出来的，纯 ES5

```"module": "./src/flv.js"```
这个才是 ES6 源文件入口

**Comment by dolphin-wood** [comment]
webpack 2+ 会优先使用 [pkg.module](https://github.com/rollup/rollup/wiki/pkg.module) 入口，你可能需要在 babel-loader 的配置里加上：

```js
{
  ...
  include: [
    // more accurate regex: /(node_modules\/[^\/]+)(?:.(?!node_modules))*$/
    require.resolve('flv.js').replace(/(node_modules\/[^\/]+).*/, '$1'),
  ],
}
```

其实比较建议 `pkg.module` 指向转译后的模块：https://github.com/jsforum/jsforum/issues/5

**Comment by BeiKeJieDeLiuLangMao** [comment]
看来是我搞错了，但是我提这个issue的目的也是想让，import引用的内容默认是ES5的代码，换句话说我也希望pkg.module 指向半编译后的模块，要不还会有别人踩到坑。

**Comment by XmYellow** [comment]
× Webpack compiler encountered errors.
6.dcf97c3a4e8467a6a459.js from UglifyJs
Unexpected token: name (MediaInfo) [./~/.1.3.4@flv.js/src/core/media-info.js:19,0][6.dcf97c3a4e8467a6a459.js:131,6]
× Compiler encountered errors. Error: Webpack compiler encountered errors
改成import flvjs from 'flv.js/dist/flv.min'可以了

**Comment by asypost** [comment]
如果是Vue的项目，可以在webpack.base.conf.js加上一句flv.js的配置：

```javascript
resolve: {  
    extensions: ['.js', '.vue', '.json'],  
    alias: {  
      'vue$': 'vue/dist/vue.esm.js',  
      '@': resolve('src'),
      'flv.js$':'flv.js/dist/flv.min.js'
    }
  }
```

**Comment by jianzhou520** [comment]
被坑了，估计都会被摆一道。建议遵循一般的依赖引入的内容构建

**Comment by driver1998** [comment]
被坑了+1 建议issue置顶

**Comment by xqq** [comment]
Should be fixed in new version v1.6.0

**Comment by tommytroylin** [comment]
> Should be fixed in new version v1.6.0

1.6.0 没有修复。
https://unpkg.com/flv.js@1.6.0/dist/flv.js 第11行就是一个箭头函数

在升级 webpack5 的时候需要额外配置 `output.environment`
否则打包产物中 webpack 初始化的代码就会直接使用箭头函数等 es6+ 语法

文档
https://webpack.js.org/configuration/output/#outputenvironment

**Comment by xqq** [comment]
@tommytroylin 感谢指正，稍等

**Comment by xqq** [comment]
@tommytroylin Fixed in https://github.com/bilibili/flv.js/releases/tag/v1.6.1
