### ISSUE TITLE
flv.d.ts is not a module.

### ISSUE THREAD

**Issue by jackesdavid** [Bilibili/flv.js#233]
Hi friends, 

First over all, thanks for this wonderful lib.

We need to be sure that flv.d.ts has a export of flvjs var.

we need to append in the end of the file

\\flv.d.ts
`export = flvjs;`

Will be more ease to build out of box with tsconfig + webpack

**Comment by xqq** [comment]
yes you're right
```export default flvjs;```

**Comment by jackesdavid** [comment]
thanks!
