### ISSUE TITLE
切换Chrome的Tab出现的问题

### ISSUE THREAD

**Issue by BeiKeJieDeLiuLangMao** [Bilibili/flv.js#236]
我的Chrome版本是62（Mac）
发现如果打开播放器之后切换tab再切换回来，图像从离开的时间点开始播放。有时候视频内容会快速追赶到最新的图像数据，有时候会中断。
chrome://media-internals/中最后的日志也表示当我切换tab时发生了event | PAUSE

00:00:15 546 | pipeline_buffering_state | BUFFERING_HAVE_ENOUGH
-- | -- | --
00:00:15 569 | event | PAUSE
00:00:30 666 | pipeline_state | kSuspending
00:00:30 666 | pipeline_state | kSuspended
00:01:09 40 | event | PLAY
00:01:09 40 | pipeline_state | kResuming
00:01:09 40 | debug | Video rendering in low delay mode.
00:01:09 49 | video_dds | false
00:01:09 49 | video_decoder | GpuVideoDecoder
00:01:09 49 | pipeline_state | kPlaying
00:01:09 202 | video_buffering_state | BUFFERING_HAVE_ENOUGH
00:01:09 202 | height | 850
00:01:09 202 | width | 478
00:01:09 202 | pipeline_buffering_state | BUFFERING_HAVE_ENOUGH
00:01:09 215 | video_buffering_state | BUFFERING_HAVE_NOTHING
00:01:09 215 | pipeline_buffering_state | BUFFERING_HAVE_NOTHING
00:01:09 215 | video_buffering_state | BUFFERING_HAVE_ENOUGH
00:01:09 215 | pipeline_buffering_state | BUFFERING_HAVE_ENOUGH
00:01:18 705 | video_buffering_state | BUFFERING_HAVE_NOTHING
00:01:18 705 | pipeline_buffering_state | BUFFERING_HAVE_NOTHING
00:01:18 707 | video_buffering_state | BUFFERING_HAVE_ENOUGH
00:01:18 707 | pipeline_buffering_state | BUFFERING_HAVE_ENOUGH
00:01:18 875 | event | PAUSE
00:01:33 945 | pipeline_state | kSuspending
00:01:33 945 | pipeline_state | kSuspended

我传入的参数：
      {
          type: 'flv',
          isLive: true,
          url:‘’
        }, {
          isLive: true,
          enableStashBuffer: false,
          lazyLoad: false,
          deferLoadAfterSourceOpen: false
        }

**Comment by xqq** [comment]
enableStashBuffer建议开
另外用Canary通道装个最新的chrome试试，chrome的解码器后台挂起策略好像有问题。

**Comment by BeiKeJieDeLiuLangMao** [comment]
我发现如果开了enableStashBuffer，会一直存在延时，如果不开的话可能会有延时，但是会快速追赶上最新的图像

**Comment by BeiKeJieDeLiuLangMao** [comment]
我的chrome是最新版本
Google Chrome 已是最新版本
版本 62.0.3202.94（正式版本） （64 位）

**Comment by xqq** [comment]
Google Chrome | 64.0.3269.3 (正式版本) canary （64 位） (cohort: Clang-64)
-- | --
修订版本 | 1d74d56f7fb838be3c05549bc5e11cdf665f1990-refs/branch-heads/3269@{#3}
操作系统 | Windows
JavaScript | V8 6.4.299
Flash | 26.0.0.131

**Comment by BeiKeJieDeLiuLangMao** [comment]
我去下载一个canary试一试

**Comment by BeiKeJieDeLiuLangMao** [comment]
能不能有一个超过x个帧的数据缓存之后，就丢弃老旧数据的策略呢

**Comment by BeiKeJieDeLiuLangMao** [comment]
我看了一下chrome的更新说明，“If the video doesn't contain any audio tracks, the video will be automatically paused when played in the background”，我的视频流碰巧就属于这种情况=。=
我给后台的ffmpeg添加了一个音频输入之后，发现播放器在快进播放到最新的视频数据之后，会卡顿数秒

**Comment by BeiKeJieDeLiuLangMao** [comment]
chrome://media-internals/中的log数据显示，是因为audio的数据缺失导致的卡顿，而且每次都会卡顿3秒左右

Timestamp | Property | Value
-- | -- | --
00:03:29 458 | audio_buffering_state | BUFFERING_HAVE_NOTHING
00:03:29 458 | pipeline_buffering_state | BUFFERING_HAVE_NOTHING
00:03:32 753 | audio_buffering_state | BUFFERING_HAVE_ENOUGH

后端ffmpeg的音频输入我是用了一个空白音
-f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100

**Comment by BeiKeJieDeLiuLangMao** [comment]
最后是在tab切换回来的时候将buffered.currentTime设成buffered.end了

**Comment by jkuri** [comment]
@BeiKeJieDeLiuLangMao where do you set `buffered.currentTime` to `buffered.end`? 
I am also experiencing delays when tab is not active.

**Comment by BeiKeJieDeLiuLangMao** [comment]
```
let video = document.getElementById('video')
let buffered = video.buffered
if (buffered.length > 0) {
   let end = buffered.end(0)
   if (end - video.currentTime > 0.15) {
      video.currentTime = end - 0.1
   }
}
```

**Comment by jkuri** [comment]
thanks man!
