### ISSUE TITLE
[求助]谦谦，安卓浏览器兼容性问题

### ISSUE THREAD

**Issue by tonystack03** [Bilibili/flv.js#237]
我使用ffmpeg推流直播,测试flv.js在PC上chrome， firefox， Opera都可以完美使用.
但是在安卓手机浏览器下，基于Chrome内核，支持MSE的。 
经过调整流的MIME types ，仅仅可以在安卓Chrome62版浏览器播放。
其他安卓手机浏览器均无法播放。
请问如何让 安卓5.0+的默认浏览器都支持flv.js. 谢谢谢谢！

**Comment by jackywei1228** [comment]
不支持MSE

**Comment by xqq** [comment]
检查 `flvjs.getFeatureList()`

**Comment by tonystack03** [comment]
我在手机测试浏览器flvjs.getFeatureList().mseLiveFlvPlayback为true的 ，并且html5test.com查当前浏览器也是支持MSE(H264 to mp4)的。
但是推流过来的直播流却无法播放。 会不会和profile的设置有关系？

**Comment by xqq** [comment]
有更具体的现象描述么？
如果是原版 chrome，可以检查 chrome://media-internals
另外 player.mediaInfo 也可一并贴出来（PC 取即可）

Android 上的 MSE 支持是 4.4.4+

**Comment by tonystack03** [comment]
仅仅在手机浏览器会播放不了， 比如我从bilibili.com 直播h5模式获取下来的flv链接地址。 放到部分安卓默认的手机浏览器下 只有一个安卓(android 6.0 chrome)浏览器支持，其他(android 6.0 默认浏览器，android 7.0 下大部分流量)都无法播放。
 player.mediaInfo 是指  Received Initialization Segment, mimeType: video/mp4;codecs=avc1.f40034 这个吗

**Comment by xqq** [comment]
对象属性 FlvPlayer.mediaInfo

**Comment by tonystack03** [comment]
<img width="771" alt="flvjs" src="https://user-images.githubusercontent.com/28807028/33021168-d934ed20-ce3b-11e7-8ece-39cb3a39f05b.png">

**Comment by xqq** [comment]
嗯？没有音频流的关系？而且H264是YUV 4:4:4 这个既不能硬解，也没有环境能保证支持的
metadata展开再看看

**Comment by tonystack03** [comment]
嗯嗯，不需要音频的的， 我ffmpeg 3.3.2  macos系统下
<img width="764" alt="flvjs2" src="https://user-images.githubusercontent.com/28807028/33021431-cf51415e-ce3c-11e7-83f9-a960e607835f.png">

**Comment by tonystack03** [comment]
后面我换profile的设置，如下图， 发现在大部分安卓手机浏览器下还是无法播放，谦谦看看哪里不对
<img width="775" alt="flvjs3" src="https://user-images.githubusercontent.com/28807028/33021735-d3c0a454-ce3d-11e7-8dd7-8b0d12a16d0b.png">

**Comment by tonystack03** [comment]
ffmpeg -f avfoundation -framerate 15  -i 0 -vcodec libx264 -preset ultrafast  -vf "crop=1920:1080:0:60,transpose=2"  -s 640x480 -b:v 800k -r 25  -pix_fmt yuva420p -profile:v baseline  -f flv  -g 5 rtmp://x.x.x.x:1935/live/test
我看了x264默认是8bit yuv。 在手机浏览器的兼容性依旧不好，请问是 哪里参数设置有问题吗

**Comment by xqq** [comment]
`MediaDataSource` 里指定 `hasAudio: false` 试试？

**Comment by tonystack03** [comment]
var flvPlayer = flvjs.createPlayer({
            type: 'flv',
            url: 'ws://127.0.0.1:8000/live/test.flv',
            hasAudio: false,
            enableWorker: true,
            enableStashBuffer: false,
            stashInitialSize: 128,
            isLive: true,
            
        });
设置如上：服务端用的srs和Node-RTMP-Server， 在安卓浏览器下还是无法播放的。
