### ISSUE TITLE
为什么 stashSize 默认是 384KB 呢？

### ISSUE THREAD

**Issue by zcoding** [Bilibili/flv.js#239]
为什么是这个值？`stashInitialSize ` 这个配置有什么影响？是否可以理解为“最小缓存”，就是已加载的数据量必须达到这个值才开始解析，所以这个值越小，理论上解析会更快，直播延时会更小？

**Comment by xqq** [comment]
嗯，影响启动速度。但调太小的话会在秒出画面后立刻卡顿

**Comment by zcoding** [comment]
原来如此。另外想问一下 flv.js 是否有针对直播做追帧处理？

**Comment by xqq** [comment]
没有

**Comment by bigy6241** [comment]
@xqq 很抱歉在下面追问这个问题,但是确实有个棘手的问题 ， 公司有直播的业务，为了加强监管，头说要做一个视频墙，同一窗口中要播放30-40路直播视频，但是我测试flv的流之后显示都已经开始播放，但是在不同的机器上的表现不同，比如我的本子最多播放5路，其他黑屏，台式有1060的显卡最多20路左右，其他黑屏...请问这个限制和机器有关还是本身flv.js 的限制...怎么处理这个问题...我的实现比较简单...就是循环实例话30次

**Comment by xqq** [comment]
视频流上http2了吗，http1.1浏览器最多允许5个并发请求

**Comment by bigy6241** [comment]
这个协议我没有注意看...是网宿提供的推拉流服务...但是我在不同的机器上测试过...结果是似乎和机器性能有关...我的mac-pro就是i5的版本...同时6路,
台式机有1060卡的最多15到20路左右 ，我自己的台式i7集显最多10路，不过无论播放多少路，直播都是极为流畅和清晰的，在这点上比video.js
使用的rtmp要好很多（rtmp虽然可以全部显示但是卡顿严重），非常感谢您的回复，接下来我会检查下协议问题。

2017-12-04 18:24 GMT+08:00 xqq <notifications@github.com>:

**Comment by bigy6241** [comment]
今天检查了chrome和qq浏览器我发现这个可能是设置问题，( 比如同样的机器chrome播放7个但是qq浏览器就是20个，这让人很不理解 ) ,
但是我依然不知道在哪里可以设置，在使用DevTools中profile记录的时候在memory这一栏中Node和listences
的一直是100%；如果可以增大listence的数量是不是就可以让最大播放数量提高了


在 2017年12月5日 上午10:22，袁晔 <bigy6241@gmail.com>写道：

**Comment by bigy6241** [comment]
@xqq 你的结论是正确的，这是来自chrome的现在在一个页面 同一域名下最大并发数是6，而且是被写死的不可设置的，我使用Firefox设置到最大并发数256正常，非常感谢你的建议.
