### ISSUE TITLE
Support rtmp?

### ISSUE THREAD

**Issue by nkanpet** [Bilibili/flv.js#24]
It support rtmp protocal ?
if support how to config mediaDataSource ?
and i test file .flv in local get error 
...............................................................
[e] > MediaSource onSourceOpen
[e] > Parsed onMetaData
[e] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported audio codec idx: 2
[e] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 2
..................
what happen?

**Comment by xqq** [comment]
1. No. HTML5 doesn't support TCP.

2. Only H.264+AAC codec is supported. It seems that your stream contains H.263 + MP3 which is not supported by the browser.

**Comment by nkanpet** [comment]
1. i have a video in local file type flv for test.
this my config file json
{
  "type" : "flv",
  "url" : "small.flv"
}
error console is ...............................................................
[e] > MediaSource onSourceOpen
[e] > Parsed onMetaData
[e] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported audio codec idx: 2
[e] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 2
..........................................................................................
2. can i play video from stream such as
{
  "type": "flv",
  "url" : "rtmp://example.com/chanel1_hi"
}
can i do it?

**Comment by xqq** [comment]
1. Only H.264+AAC codec is supported. It seems that your stream contains H.263 + MP3 which is not supported by the browser.

2. No. HTML5 doesn't support TCP.
