### ISSUE TITLE
live stream is not live after 1 hour play

### ISSUE THREAD

**Issue by vdalex25** [Bilibili/flv.js#242]
i have live stream from camera and play it in one page in flash over RTMP and in flvplayer over WS.
on start camera time is the same in both player. For example 19:00:00. After 1 hour playing. time on flash player is 20:00:00, in flvplayer time is 19:55:00. If restart flvplayer time is same again

**Comment by hxl-dy** [comment]
it seems like that `isLive` option has no effect.

**Comment by xqq** [comment]
Have you ever set `enableStashBuffer` to false?

**Comment by hxl-dy** [comment]
`autoCleanupSourceBuffer`
`autoCleanupMaxBackwardDuration`
`autoCleanupMinBackwardDuration`
can these three option fix it?

**Comment by xqq** [comment]
Nope

**Comment by vdalex25** [comment]
if set enableStashBuffer to false, playback rate looks like 0.5 * real rate

**Comment by vdalex25** [comment]
i think trouble is in audio. If i disable audio on stream it's work fine.  I am try fix it with  #166 commit, but it`s not working

**Comment by xqq** [comment]
try branch `accurate-sample-duration`

**Comment by xqq** [comment]
ADTS is completely unaccept
