### ISSUE TITLE
Play a recording video ,It stoped after 5 minute

### ISSUE THREAD

**Issue by jianging2009** [Bilibili/flv.js#244]
When I play a recording video ,it stopped after 5 minute. I have set isLive:true.

**Comment by jianging2009** [comment]
Because the loading  speed > playing spend。

**Comment by jianging2009** [comment]
Because the loading speed > playing spend，How to change the SourceBuffer or cache ？

**Comment by xqq** [comment]
Maybe caused by `lazyLoad` mechanism and failed to recover loading from paused position.

Have your server configured Range seek correctly?  See cors.md

https://github.com/Bilibili/flv.js/blob/master/docs/cors.md

**Comment by jianging2009** [comment]
It's a static FLV file,I have set:
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Allow-Headers: range
Access-Control-Expose-Headers: Content-Length

**Comment by jianging2009** [comment]
[MSEController] > MediaSource onSourceOpen
flv.min.js:6 [FLVDemuxer] > Parsed onMetaData
flv.min.js:6 [FLVDemuxer] > Parsed AVCDecoderConfigurationRecord
flv.min.js:6 [MSEController] > Received Initialization Segment, mimeType: video/mp4;codecs=avc1.64002a
flv.min.js:6 [FlvPlayer] > MSE SourceBuffer is full, suspend transmuxing task
flv.min.js:3 Fetch failed loading: GET "https://192.168.3.212:8443/video/e223d1437ffd4bcfbfef5f2a76e3b62b.flv".
value @ flv.min.js:3
value @ flv.min.js:3
value @ flv.min.js:2
value @ flv.min.js:2
value @ flv.min.js:2
value @ flv.min.js:4
(anonymous) @ flv.min.js:4
i.emit @ flv.min.js:1
value @ flv.min.js:1

**Comment by jianging2009** [comment]
Continue loading from paused position
2flv.min.js:3 OPTIONS https://192.168.3.212:8443/video/e223d1437ffd4bcfbfef5f2a76e3b62b.flv net::ERR_ABORTED
value @ flv.min.js:3
value @ flv.min.js:3
value @ flv.min.js:3
value @ flv.min.js:2
value @ flv.min.js:2
value @ flv.min.js:5
value @ flv.min.js:5
main.jsp:1 Failed to load https://192.168.3.212:8443/video/e223d1437ffd4bcfbfef5f2a76e3b62b.flv: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://192.168.3.212' is therefore not allowed access. The response had HTTP status code 405. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS

**Comment by jianging2009** [comment]
The Continue loading Request Method:OPTIONS,but i have set:Access-Control-Allow-Methods: GET, OPTIONS,maybe my server doesn't suport OPTIONS....

**Comment by jianging2009** [comment]
my nginx sever :
if ($request_method = OPTIONS ) {
...
add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,HEAD,PUT';
add_header 'Access-Control-Expose-Headers' 'Content-Length';
...
return 200;
                }
**Thanks！**#

**Comment by xqq** [comment]
Yep, handle `OPTIONS` request is necessary
