### ISSUE TITLE
用了HTML5后，一直出bug

### ISSUE THREAD

**Issue by MeCKodo** [Bilibili/flv.js#25]
![image](https://cloud.githubusercontent.com/assets/10184444/19962924/05e86dca-a1f5-11e6-9f6e-4575218dd287.png)

如上，经常加载不出来。

然后视频经常会花屏，用FLASH的版本网速也很差，经常加载不出来。心累

**Comment by xqq** [comment]
bilibili主站播放器问题请走主站反馈渠道，与本项目无关
