### ISSUE TITLE
请教关于IDR帧的问题

### ISSUE THREAD

**Issue by iamgqb** [Bilibili/flv.js#251]
查了半天都只是说 IDR 会清掉 DPB 且 确保之后的帧不会依赖此之前的帧；如果这样的话 I 帧不就可以代替了么？

那 IDR 被真正设计的原因是什么呢？

是因为在 H264 中的 B帧 P帧会跨越当前 GOP 依赖之前 GOP 中的帧吗？

读源码读到 https://github.com/Bilibili/flv.js/blob/master/src/player/flv-player.js#L82 这句判断，不知 IDR 为何物，所以想了解下。

**Comment by xqq** [comment]
Instantaneous Decoding Refresh, 解码器遇到 IDR 可清空之前所有的帧缓冲. 因为在此 IDR 之后的帧不可能再依赖之前的帧

GOP 边界就是以 IDR 界定的，B/P 依赖当然不会跨越 GOP

**Comment by iamgqb** [comment]
emmmm... 还是没明白

wiki 上说两个 I 帧之间就是 GOP 的长度，如果是这样 I 帧不就可以代替 IDR 了么？
还是说一个GOP 中可以存在多个 I 帧，而这里的 “two full images (I-frames)” 是指 IDR？

> The GOP structure is often referred by two numbers, for example, M=3, N=12. The first number tells the distance between two anchor frames (I or P). The second one tells the distance between two full images (I-frames): it is the GOP size. For the example M=3, N=12, the GOP structure is IBBPBBPBBPBBI. Instead of the M parameter the maximal count of B-frames between two consecutive anchor frames can be used.

**Comment by xqq** [comment]
一个GOP中可以存在多个I帧，他说的 I-Frames 肯定指IDR

**Comment by iamgqb** [comment]
这样的话那就通顺了 🙏

感谢解答！新年快乐～
