### ISSUE TITLE
暂停之后怎么获取最新的流

### ISSUE THREAD

**Issue by linlvping** [Bilibili/flv.js#253]
暂停或是切换浏览器（只要焦点不在当前页面），再回来的时候视频会从上次停止的地方继续播放，但我想要再回来的时候播放最新的画面，这个要怎么解决

**Comment by xqq** [comment]
seek，把video.currentTime调到video.buffered.end(0)附近

**Comment by linlvping** [comment]
非常感谢~

**Comment by webstermobile** [comment]
有时候会报错

> seek，把video.currentTime调到video.buffered.end(0)附近
