### ISSUE TITLE
error file flv type

### ISSUE THREAD

**Issue by nkanpet** [Bilibili/flv.js#26]
i use video type flv H.264+AAC and get error ....
![screenshot from 2016-11-04 11-47-33](https://cloud.githubusercontent.com/assets/13941759/19994859/d05dd84e-a284-11e6-88cd-8ccf75835159.png)

**Comment by xqq** [comment]
A decode error may occurred.
Please provide the related logcat in `chrome://media-internals`

**Comment by nkanpet** [comment]
error Append: stream parsing failed. Data size=131072 append_window_start=0 append_window_end=inf

**Comment by xqq** [comment]
Can you provide your stream file for test?

**Comment by nkanpet** [comment]
You can download video demo test https://drive.google.com/file/d/0B9IY9Jqs0bRDQURQN2Q2ZE5jaGs/view?usp=sharing
Thank you

**Comment by xqq** [comment]
There're errors in the video track. If you remux it into an mp4 file, the video is complete black in the browser or Apple QuickTime player.
