### ISSUE TITLE
求助：在一个页面中使用多个播放器播放多个flv流，为什么只有前6个正常播放

### ISSUE THREAD

**Issue by jyl-xypt** [Bilibili/flv.js#260]
`<!DOCTYPE html>
<html>

<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <script type="text/javascript" src="./js/flv.js"></script>
    <title>flv.js demo</title>
    <style>
        .mainContainer {
            display: block;
            width: 1024px;
            
        }

        .urlInput {
            display: block;
            width: 100%;
            margin-left: auto;
            margin-right: auto;
            margin-top: 8px;
            margin-bottom: 8px;
        }

        .centeredVideo {
            display: inline-block;
            width:  300px;
            height: 300px;
         
        }

        .controls {
            display: block;
            width: 100%;
            text-align: left;
            margin-left: auto;
            margin-right: auto;
        }
    </style>
</head>
<body>
    <div class="mainContainer">
        <video id="videoElement"  class="centeredVideo"  autoplay>Your browser is too old which doesn't support HTML5 video.</video>
        <video id="videoElement2" class="centeredVideo"  autoplay>Your browser is too old which doesn't support HTML5 video.</video>
        <video id="videoElement3" class="centeredVideo"  autoplay>Your browser is too old which doesn't support HTML5 video.</video>
        <video id="videoElement4" class="centeredVideo"  autoplay>Your browser is too old which doesn't support HTML5 video.</video>
        <video id="videoElement5" class="centeredVideo"  autoplay>Your browser is too old which doesn't support HTML5 video.</video>
        <video id="videoElement6" class="centeredVideo"  autoplay>Your browser is too old which doesn't support HTML5 video.</video>
        <video id="videoElement7" class="centeredVideo"  autoplay>Your browser is too old which doesn't support HTML5 video.</video>
        <video id="videoElement8" class="centeredVideo"  autoplay>Your browser is too old which doesn't support HTML5 video.</video>
        <video id="videoElement9" class="centeredVideo"  autoplay>Your browser is too old which doesn't support HTML5 video.</video>
    </div>
    <script src="./js/flv.js"></script>
    <script>
        var player  = document.getElementById('videoElement');
        var player2 = document.getElementById('videoElement2');
        var player3 = document.getElementById('videoElement3');
        var player4 = document.getElementById('videoElement4');
        var player5 = document.getElementById('videoElement5');
        var player6 = document.getElementById('videoElement6');
        var player7 = document.getElementById('videoElement7');
        var player8 = document.getElementById('videoElement8');
        var player9 = document.getElementById('videoElement9');

        if (flvjs.isSupported()) {
            var flvPlayer = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改
            });
            flvPlayer.attachMediaElement(videoElement);
            flvPlayer.load(); //加载
 

	        var flvPlayer2 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改
            });
            flvPlayer2.attachMediaElement(videoElement2);
            flvPlayer2.load(); //加载

	        var flvPlayer3 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改
            });
            flvPlayer3.attachMediaElement(videoElement3);
            flvPlayer3.load(); //加载

	        var flvPlayer4 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改
            });
            flvPlayer4.attachMediaElement(videoElement4);
            flvPlayer4.load(); //加载
	    

	        var flvPlayer5 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改

            });
            flvPlayer5.attachMediaElement(videoElement5);
            flvPlayer5.load(); //加载

	    
	        var flvPlayer6 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改

            });
            flvPlayer6.attachMediaElement(videoElement6);
            flvPlayer6.load(); //加载
            

	        var flvPlayer7 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改

            });
            flvPlayer7.attachMediaElement(videoElement7);
            flvPlayer7.load(); //加载

            
	        var flvPlayer8 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改

            });
            flvPlayer8.attachMediaElement(videoElement8);
            flvPlayer8.load(); //加载

	        var flvPlayer9 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改

            });
            flvPlayer9.attachMediaElement(videoElement9);
            flvPlayer9.load(); //加载

            flv_start();
        }

        function flv_start() {
            player.play();
            player2.play();
            player3.play();
            player4.play();
            player5.play();
            player6.play();
            player7.play();
            player8.play();
            player9.play();
        }

    </script>
</body>

</html>

`

**Comment by jyl-xypt** [comment]
代码补充   
<div class="mainContainer">
        <video id="videoElement"  class="centeredVideo"  autoplay>Your browser is too old which doesn't support HTML5 video.</video>
        <video id="videoElement2" class="centeredVideo"  autoplay>Your browser is too old which doesn't support HTML5 video.</video>
        <video id="videoElement3" class="centeredVideo"  autoplay>Your browser is too old which doesn't support HTML5 video.</video>
        <video id="videoElement4" class="centeredVideo"  autoplay>Your browser is too old which doesn't support HTML5 video.</video>
        <video id="videoElement5" class="centeredVideo"  autoplay>Your browser is too old which doesn't support HTML5 video.</video>
        <video id="videoElement6" class="centeredVideo"  autoplay>Your browser is too old which doesn't support HTML5 video.</video>
        <video id="videoElement7" class="centeredVideo"  autoplay>Your browser is too old which doesn't support HTML5 video.</video>
        <video id="videoElement8" class="centeredVideo"  autoplay>Your browser is too old which doesn't support HTML5 video.</video>
        <video id="videoElement9" class="centeredVideo"  autoplay>Your browser is too old which doesn't support HTML5 video.</video>
    </div>



<script>
        var player  = document.getElementById('videoElement');
        var player2 = document.getElementById('videoElement2');
        var player3 = document.getElementById('videoElement3');
        var player4 = document.getElementById('videoElement4');
        var player5 = document.getElementById('videoElement5');
        var player6 = document.getElementById('videoElement6');
        var player7 = document.getElementById('videoElement7');
        var player8 = document.getElementById('videoElement8');
        var player9 = document.getElementById('videoElement9');

        if (flvjs.isSupported()) {
            var flvPlayer = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改
            });
            flvPlayer.attachMediaElement(videoElement);
            flvPlayer.load(); //加载
 

	        var flvPlayer2 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改
            });
            flvPlayer2.attachMediaElement(videoElement2);
            flvPlayer2.load(); //加载


	        var flvPlayer3 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改
            });
            flvPlayer3.attachMediaElement(videoElement3);
            flvPlayer3.load(); //加载


	        var flvPlayer4 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改
            });
            flvPlayer4.attachMediaElement(videoElement4);
            flvPlayer4.load(); //加载
	    

	        var flvPlayer5 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改

            });
            flvPlayer5.attachMediaElement(videoElement5);
            flvPlayer5.load(); //加载

	    
	        var flvPlayer6 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改

            });
            flvPlayer6.attachMediaElement(videoElement6);
            flvPlayer6.load(); //加载
            

	        var flvPlayer7 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改

            });
            flvPlayer7.attachMediaElement(videoElement7);
            flvPlayer7.load(); //加载

            
	        var flvPlayer8 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改

            });
            flvPlayer8.attachMediaElement(videoElement8);
            flvPlayer8.load(); //加载


	        var flvPlayer9 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改

            });
            flvPlayer9.attachMediaElement(videoElement9);
            flvPlayer9.load(); //加载

            flv_start();
        }

        function flv_start() {
            player.play();
            player2.play();
            player3.play();
            player4.play();
            player5.play();
            player6.play();
            player7.play();
            player8.play();
            player9.play();
        }

**Comment by xqq** [comment]
http1.1浏览器有并发请求数限制，允许5~6个，以外的都会强制pending
