### ISSUE TITLE
求助:在一个页面中使用多个播放器同是播放多个视频，只有前6个是正常的

### ISSUE THREAD

**Issue by jyl-xypt** [Bilibili/flv.js#261]
......
      `var player  = document.getElementById('videoElement');
        var player2 = document.getElementById('videoElement2');
        var player3 = document.getElementById('videoElement3');
        var player4 = document.getElementById('videoElement4');
        var player5 = document.getElementById('videoElement5');
        var player6 = document.getElementById('videoElement6');
        var player7 = document.getElementById('videoElement7');
        var player8 = document.getElementById('videoElement8');
        var player9 = document.getElementById('videoElement9');`

         ` if (flvjs.isSupported()) {
            var flvPlayer = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改
            });
            flvPlayer.attachMediaElement(videoElement);
            flvPlayer.load(); //加载
 

	        var flvPlayer2 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改
            });
            flvPlayer2.attachMediaElement(videoElement2);
            flvPlayer2.load(); //加载

	        var flvPlayer3 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改
            });
            flvPlayer3.attachMediaElement(videoElement3);
            flvPlayer3.load(); //加载

	        var flvPlayer4 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改
            });
            flvPlayer4.attachMediaElement(videoElement4);
            flvPlayer4.load(); //加载
	    

	        var flvPlayer5 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改

            });
            flvPlayer5.attachMediaElement(videoElement5);
            flvPlayer5.load(); //加载

	    
	        var flvPlayer6 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改

            });
            flvPlayer6.attachMediaElement(videoElement6);
            flvPlayer6.load(); //加载
            

	        var flvPlayer7 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改

            });
            flvPlayer7.attachMediaElement(videoElement7);
            flvPlayer7.load(); //加载

            
	        var flvPlayer8 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改

            });
            flvPlayer8.attachMediaElement(videoElement8);
            flvPlayer8.load(); //加载

	        var flvPlayer9 = flvjs.createPlayer({
                type: 'flv',
                "isLive": true,//<====加个这个 
                url: 'http://192.168.177.137:8080/live/test1.flv',//<==自行修改

            });
            flvPlayer9.attachMediaElement(videoElement9);
            flvPlayer9.load(); //加载

            flv_start();
        }
`

**Comment by xqq** [comment]
#260
