### ISSUE TITLE
AMF parse issue

### ISSUE THREAD

**Issue by invalidtask** [Bilibili/flv.js#263]
[AMF] > Unsupported AMF value type 5
[AMF] > IllegalStateException: Data not enough when parse Value

This happens with live FLV playback. Metadata exists with RTMP playback. Any idea?

**Comment by xqq** [comment]
Try `ffprobe` to check whether the stream has error in the onMetaData structure

**Comment by invalidtask** [comment]
Here is the ffprobe result: 

`Metadata:
  width                 1280.00
  height                720.00
  displayWidth          1280.00
  displayHeight         720.00
  duration              0.00
  framerate             30.00
  fps                   30.00
  videodatarate         2500.00
  videocodecid          0.00
  audiodatarate         160.00
  audiocodecid          0.00`

**Comment by xqq** [comment]
hmmm... The key point is that whether `ffprobe` has output some warnings (in yellow or red) into stderr

**Comment by xqq** [comment]
I cannot location the problem. Will be better if you can provide a simple sample file (just contains the onMetaData)

**Comment by invalidtask** [comment]
Try this http://66.90.93.44:801/live?port=2935&app=live&stream=live_newzviewz

**Comment by wony-zheng** [comment]
相同的问题，我是用[nginx-http-flv](https://github.com/winshining/nginx-http-flv-module)直播的，会报错。但是接着能正常播放

**Comment by mengshixing** [comment]
@xqq i have the same question  'Unsupported AMF value type 5' ,and can't get the keyframes info . 
here is my onMetaData  export from wireshark
[onmetedata.zip](https://github.com/Bilibili/flv.js/files/1867839/onmetedata.zip)

**Comment by andade1996** [comment]
有报错但是不影响播放不知道是为什么
