### ISSUE TITLE
chrome浏览器花屏问题

### ISSUE THREAD

**Issue by fengminxuan** [Bilibili/flv.js#268]
谦谦，我自己封装的flv视频使用http_flv方式直播，在chrome下出现花屏情况，但是我用qt的QtWebEngineWidgets组件播放没有问题。SEI这种类型的NALU我是没有封装进flv的，不知道有没有影响。

**Comment by xqq** [comment]
没影响
FireFox Safari Edge 如何？

**Comment by xqq** [comment]
如果是macOS换windows试试

**Comment by fengminxuan** [comment]
可能是解码器的问题吧，我用的windows。

**Comment by fengminxuan** [comment]
还有一点特殊的情况，就是我图转换方便，使用的yuv444格式喂给x264编码器

**Comment by fengminxuan** [comment]
谦谦 问题找到了，就是因为yuv444格式的问题，我换成了yuv420p就不会花屏了。
