### ISSUE TITLE
有关解析的问题

### ISSUE THREAD

**Issue by dlpuzhangyue** [Bilibili/flv.js#269]
@xqq 经过测试  播放已经录制好的.flv格式视频 如图所示：
![image](https://user-images.githubusercontent.com/29819173/35313877-b3c08e42-00fd-11e8-8cee-cd23a946e3d7.png)
在视频时间大于2分钟的时候，每次页面先渲染两个视频，10s左右后第3,4个才出现，页面明显卡顿

请问该如何解决

**Comment by xqq** [comment]
开enableWorker试试，还有为什么禁用stashBuffer，缓存都关了怎么可能不影响性能

**Comment by dlpuzhangyue** [comment]
试过了 还是没有明显的改善  根据观察 好像它会等到前两个视频缓存结束播放后  才会解析第3,4个

**Comment by dlpuzhangyue** [comment]
![image](https://user-images.githubusercontent.com/29819173/35314164-47053b3e-00ff-11e8-8630-8e9bac745ece.png)

**Comment by xqq** [comment]
好好看文档，flvjs.createPlayer传参完全是错的

**Comment by dlpuzhangyue** [comment]
@xqq  。。。 这个改过来了  卡到鼠标无法移动  请问这块实在哪里做限制了么？  小于两分钟的4个瞬间解析

**Comment by xqq** [comment]
没有
