### ISSUE TITLE
部分window系统的chrome画面显示不全

### ISSUE THREAD

**Issue by linlvping** [Bilibili/flv.js#275]
同一个直播源，分别用flash和flv通过chrome浏览器播放，发现在部分window系统下，chrome只能展现视频左上角约1/8的画面，flash是正常的，mac版本的chrome也是正常的
另外对比了几个不同的系统和浏览器
1. 同样的电脑，chrome有问题，uc没问题
2. 同样的chrome浏览器版本，电脑A可以，电脑B不行
window系统分别试过win7和win10，都存在这样的问题，部分机器可以，部分机器不可以

**Comment by xqq** [comment]
看一下 `player.mediaInfo` 里的 `width` `height` `sarDen` `sarNum`
系统版本，显卡及驱动信息也提供一下

**Comment by linlvping** [comment]
width=352 height=288 sarDen=1 sarNum=1

系统信息：
版次：Windows 10专业版
版本：1709
OS内部版本：16299.192

显卡：
AMD Radeon(TM) R9 M375
Intel(R) HD Graphics 5500

**Comment by linlvping** [comment]
width=352 height=288 sarDen=1 sarNum=1
这个值在正常播放的电脑上，也是一样的

**Comment by linlvping** [comment]
@xqq 能帮忙看下么

**Comment by xqq** [comment]
提供可重现的sample

**Comment by linlvping** [comment]
感谢，刚才用ffmpeg改了下参数，貌似已经好了
