### ISSUE TITLE
The play() request was interrupted by a call to pause()

### ISSUE THREAD

**Issue by mburger81** [Bilibili/flv.js#278]
If there are some problems with the video and the player was not able to start the video, if we leave the page where we call also .destroy() we get this error

`Error: Uncaught (in promise): AbortError: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22`

As you can see this is probably a problem only on chrome, have a look on this link https://goo.gl/LdLk22

**Comment by falstack** [comment]
this not flv.js`s bug, <video> in chrome have this problems

because your play() and pause() call too fast

**Comment by mburger81** [comment]
hi @falstack, thx and sorry for my late response.

I know this, but the question is, all players has this problem with chrome, my question is more, how can we avoid this?

We can not catch the error, also .destroy() does not return a a Promise, so no why to omit exception message.

```
private stopPlay() {

        if (this.flvjsPlayer) {
            try {
                console.log('=> pause:', this.flvjsPlayer.pause());
                console.log('=> unload:', this.flvjsPlayer.unload());
                console.log('=> detachMediaElement:', this.flvjsPlayer.detachMediaElement());
                console.log('=> destroy:', this.flvjsPlayer.destroy());
            } catch (e) {
                console.log(e);
            }
            this.flvjsPlayer = null;
        }
    }
```
so how can we handle this? Some ideas?

**Comment by falstack** [comment]
@mburger81 maybe this repo：https://github.com/videojs/video.js will help you

**Comment by mburger81** [comment]
So, I try to catch error on the wrong point, the catch is firing on `play()` **Promise**. So doing this, is catching and silencing the exception:

```
this.flvjsPlayer.play()
                    .then(
                        () => {               
                        }
                    )
                    .catch(
                        (error) => {
                            if (error && error.toString().toLowerCase().includes('the play() request was interrupted by a call to pause()')) {
                                // do nothing, we catch only this exception https://developers.google.com/web/updates/2017/06/play-request-was-interrupted                    
                            } else {
                                throw error
                            }

                        }
                    );
```
On the other side, we had a look on **video.js** and they silent the exception by there own, so others have do not do this.
@xqq Have a look to this https://github.com/videojs/video.js/pull/3518/commits

**Comment by xqq** [comment]
I think it's better to let the user to handle this.

**Comment by mburger81** [comment]
Okay so for everyone, catch the exception in `play()` promise like I do in the post above https://github.com/Bilibili/flv.js/issues/278#issuecomment-380020300
