### ISSUE TITLE
【新增事件】触发自定义事件，监听事件需执行的方法未执行

### ISSUE THREAD

**Issue by xujiujiu** [Bilibili/flv.js#279]
在使用该项目做一个视频裁剪的功能。
1、在flv-player中新建函数，该函数只为了触发事件startRecord。
startRecord(type) {
        this._emitter.emit('startRecord');
}
2、在transmuxer.js的constructor函数中新增监听事件,去触发transmuxer-controler.js中的_startRecord方法
this._emitter.addListener('startRecord', () => {
                ctl._startRecord();
 });

触发事件执行了，但是触发事件后，监听事件执行的方法未执行

有木有人帮忙看看，我这样写是不是有问题的？

**Comment by xqq** [comment]
emitter不是全局的，是每个模块各自的，事件都是局部事件而非全局广播
