### ISSUE TITLE
360浏览器的坑

### ISSUE THREAD

**Issue by yu305306** [Bilibili/flv.js#287]
请问有遇到 360 浏览器，用mse 导入video 视频，在开始播放2~20s 视频会自动被暂停。然后就不能播放了。 seek时间又可以播放 几s 然后又停止。只会在360 出问题。 QQ chrome 猎豹 都没有问题，完美播放,还是这个360 吃相难看需要给保护费

**Comment by xqq** [comment]
内核类型，内核版本，UserAgent

**Comment by yu305306** [comment]
官网下载的 9    版本号 9.1.0.410   内核 55.0.2883.87     navigator.userAgent:  "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"

**Comment by yu305306** [comment]
发现问题源， buffered.length 被创建了多个
