### ISSUE TITLE
Failed to minify

### ISSUE THREAD

**Issue by mohsalsaleem** [Bilibili/flv.js#288]
Hi, I'm using this module with react js.
The react app was created using create-react-app
I'm getting the following error while building

Failed to minify the code from this file: 
 	./node_modules/flv.js/src/utils/logger.js:21

My node version is 8.9.1

**Comment by elon-hu** [comment]
I with the same issues, U can import the minified file. like this:
`import flvjs from 'flv.js/dist/flv.min.js';`
