### ISSUE TITLE
Stream sometimes doesn't retrieve AAC sequence header

### ISSUE THREAD

**Issue by bryjch** [Bilibili/flv.js#293]
Hello, thank you for this package it's been very cool so far. I am encountering an unusual problem with livestream MSE/demuxer - sometimes when trying to load a src, the `AudioSpecificConfig` never gets parsed - so MSEController never receives audio initialization segment.

Below, I added some logs in `flv-demuxer.js` to track which calls are being fired in `_parseAudioData()`:

**Problem: AudioSpecificConfig never parsed**
![image](https://user-images.githubusercontent.com/9291779/38256663-6382178c-3791-11e8-908d-d9204cfef89f.png)

**Success:**
![image](https://user-images.githubusercontent.com/9291779/38256626-4b10e5fc-3791-11e8-97db-e416ed5f0476.png)

I have used `ffprobe` to test for metadata structure, it seems okay:

![image](https://user-images.githubusercontent.com/9291779/38256771-a6eaecec-3791-11e8-9110-28d7c927cd73.png)

**Notes:**
- I am using `flv.js` livestream feature `isLive: true`.
- I am using additional configs `fixAudioTimestampGap: false` and `enableStashBuffer: false`.
- The http/flv livestream will sometimes have mimeType change (video codec changes depending on network quality of broadcaster [auto upgrade/downgrade output resolution]). MSEController handles this well, and this actually triggers `AudioSpecificConfig` to be parsed.

It seems there may be some problem with my livestream metadata, have you encountered something like this? Appreciate any help!

**Comment by bryjch** [comment]
Indeed, seems like the video codec change on our server is messing with the sequence header somewhere.

Wanted to ask in case you had encountered it before.

Thanks for the quick reply, will look into the flv stream provider.

**Comment by xqq** [comment]
No I haven’t meet such case
