### ISSUE TITLE
浏览器限制flv.js的数量

### ISSUE THREAD

**Issue by winshining** [Bilibili/flv.js#295]
@xqq 
Hi，感谢开源这么优秀的软件！
看了下issues列表，好像还没人提到过这个问题。
昨天上午有网友反馈说使用我开源的nginx-http-flv-module作为直播服务器，flv.js播放不了推过来的流，晚上再反馈说是Chrome浏览器对flv.js的加载数量有限制，限制数量为6个，我的机器上没有Chrome，所以今天我使用Firefox测试了一下，也是开6个后就无法播放了，不管这6个flv.js播放的流是不是一样，开第7个就一直显示转圈，然后关闭前面的6个中的其中1个，新开的这个就能播放了。我也测试过开了第7个flv.js后，用VLC请求相同的直播流，是可以正常播放的，证明不是直播服务器的问题。所以我想请教一下是浏览器限制了flv.js的加载数量还是flv.js本身限制了加载数量？如果是，可以自定义加载数量么？谢谢！

**Comment by winshining** [comment]
抱歉，问题重复了，我在Closed问题列表里找到相关的问题了。

**Comment by xqq** [comment]
同目标服务器http1.1连接数限制
