### ISSUE TITLE
请教一下：使用flv.js在浏览器中播放被限制只能播放6个在B站没有这种问题

### ISSUE THREAD

**Issue by gitmiao949710612** [Bilibili/flv.js#298]
在前端使用flv.js播放http-flv格式的视频
一个浏览器只能播放6个，第7个就播放不了
关闭掉其中一个，第7个马上就能播放了
这是什么原因造成的？
没有在网上搜索到相关线索,很头疼
B站的直播不会出现这种问题啊

**Comment by xqq** [comment]
issue区很多人问过

**Comment by gitmiao949710612** [comment]
我没有找到答案，但是我把视频地址 http 改成了  ws就可以了

**Comment by gitmiao949710612** [comment]
NICE  非常感谢大神的解惑！！！

**Comment by ddcouples** [comment]
有好的解决方案吗

**Comment by gitmiao949710612** [comment]
把http协议改成ws协议，这个也是我好久之前的解决方案了。

**Comment by Scholar-g** [comment]
把http协议改成ws协议怎么改，视频服务不是自己的，萤石告诉我找谷歌服务。。。

**Comment by wing-cen** [comment]
> 在前端使用flv.js播放http-flv格式的视频
> 一个浏览器只能播放6个，第7个就播放不了
> 关闭掉其中一个，第7个马上就能播放了
> 这是什么原因造成的？
> 没有在网上搜索到相关线索,很头疼
> B站的直播不会出现这种问题啊

浏览器对同一域名http请求并发数有限制导致的，使用websocket可以突破并发限制

**Comment by Scholar-g** [comment]
浏览器的并发限制------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月29日(星期二) 下午5:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bilibili/flv.js] 请教一下：使用flv.js在浏览器中播放被限制只能播放6个在B站没有这种问题 (#298)
