### ISSUE TITLE
点播flv文件自定义seekhandler，拖动播放条seek总是会缓存区满60s才播放

### ISSUE THREAD

**Issue by mengshixing** [Bilibili/flv.js#300]
点播 我自定义跳转之后只有缓存够60秒视频才开始播放

**Comment by mengshixing** [comment]
please closed sorry

**Comment by xqq** [comment]
1. 确认 onMetaData 结构中有 keyframes 表
2. 检查服务器是否按要求返回数据

**Comment by mengshixing** [comment]
thanks
1.初次加载onMetaData 结构中有 keyframes 表,seek时候设置的通过关键帧跳转
2.seek之后服务器这块我直接发的FLV音视频包.是可以解析的
问题是seek之后,点播会卡顿好几秒才开始播放, 我的log发现 可播放时缓存buffer总是跳转点往后加60s,

**Comment by mengshixing** [comment]
i used  CustomSeekHandler  since sever need 4 param
paramSeekfilepositions,paramSeeksecond,paramPrevpositions,paramNextpositions

after customseek i set this._stashByteStart=0 in IOController  /_onLoaderChunkArrival

**Comment by mengshixing** [comment]
if i don't set  ByteStart=0 ,the stream can't be parse

**Comment by xqq** [comment]
I think more works have to be done for an after-seeking stream which still has FLV header

**Comment by mengshixing** [comment]
thanks
