### ISSUE TITLE
Multipart playback 无法跳过seek操作的中间切片

### ISSUE THREAD

**Issue by dean-river** [Bilibili/flv.js#308]
hi： 
   我用flv.js 播放flv的切片，但是发现我在seek的时候，他不会跳过下载中间的一些切片，而是一个挨着一个下载下来。我翻了一下所有的配置选项也没有找到可以解决这个问题的。请问是flv.js 现在本身不支持，还是需要设置什么选项。如果不支持，后面有支持计划吗？

**Comment by xqq** [comment]
首先 flv.js 是没有这个问题的..

跨越分段首次 seek 到某分段时，只会在第一次时跳到该分段头部拉取 meta 信息，并且会进行缓存.

请检查 MediaDataSource 中 segments 部分是否已填入准确的各分段 duration，
并保证每个分段的 onMetaData 中有正确的 keyframes 表

**Comment by dean-river** [comment]
谢谢回复！
segments 各分段的duration是写了的，但是onMetaData内没有写duration 和 keyframes 信息，这个影响跳过中间完整的切片吗？

**Comment by dean-river** [comment]
我只想做到切片精度的seek。

**Comment by dean-river** [comment]
而且通过debug调试来看，我seek的时候网络根本没有去加载seek到的切片，而是挨着加载的。这个是不是不正常。

**Comment by xqq** [comment]
目前 onMetaData.duration 属于必填字段
如果 seek 打在目标分段中间，而无 keyframes 表导致无法定位目标帧，只能从头加载的话，浏览器也就会一直卡在 seek 目标点上等待数据

**Comment by dean-river** [comment]
好的，谢谢了！
