### ISSUE TITLE
Package on CDN

### ISSUE THREAD

**Issue by ron666** [Bilibili/flv.js#31]
Such an awesome plugin. Is there a way you can put the `dist` package in a CDN or an open URL so it can be used without having to compile it?

**Comment by xqq** [comment]
You can download prebuild dist in https://github.com/Bilibili/flv.js/releases
flv.js dist has been published on public cdnjs https://cdnjs.com/libraries/flv.js

**Comment by ron666** [comment]
Thanks a lot. Looking forward to use this
