### ISSUE TITLE
转码后的flv格式无法播放

### ISSUE THREAD

**Issue by LiwengangK** [Bilibili/flv.js#311]
#我自己用java调ffmpeg将mp4格式转码为flv格式后，播放出错。如下：
flv.min.js:6 [TransmuxingController] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 2
value @ flv.min.js:6
value @ flv.min.js:2
value @ flv.min.js:3
value @ flv.min.js:2
value @ flv.min.js:3
value @ flv.min.js:3
(anonymous) @ flv.min.js:3
Promise.then (async)
value @ flv.min.js:3
(anonymous) @ flv.min.js:3
Promise.then (async)
value @ flv.min.js:3
(anonymous) @ flv.min.js:3
Promise.then (async)
value @ flv.min.js:3
(anonymous) @ flv.min.js:3
Promise.then (async)
value @ flv.min.js:3
(anonymous) @ flv.min.js:3
49flv.min.js:1 Uncaught (in promise) Error: Uncaught, unspecified "error" event. (MediaError)

**Comment by LiwengangK** [comment]
![Uploading TIM图片20180505140435.png…]()

**Comment by xqq** [comment]
视频codec仅支持h264
