### ISSUE TITLE
Play external FLV

### ISSUE THREAD

**Issue by ron666** [Bilibili/flv.js#32]
With Flash there's no issues, but is there a way to play an external FLV resource without facing the issues related to CORS?

As an example: http://www.mediacollege.com/video-gallery/testclips/20051210-w50s.flv

**Comment by xqq** [comment]
No.
Only if in same-origin, or playback in a browser extension.

**Comment by ron666** [comment]
Thanks

**Comment by xqq** [comment]
Cross-origin resource fetching in Flash also needs `crossdomain.xml` on target server, right?

**Comment by ron666** [comment]
yeah but it can be bypassed using some of the Flash libraries. Is not as strict as this plugin
