### ISSUE TITLE
手机端h5页面flv直播

### ISSUE THREAD

**Issue by hangchao** [Bilibili/flv.js#34]
请问支持手机端h5页面flv格式直播吗？

**Comment by xqq** [comment]
支持 Android 5.x+，依赖 [MediaSource](http://caniuse.com/#search=mediasource) 和 [Fetch API](http://caniuse.com/#feat=fetch)
可通过 flvjs.getFeatureList().mseLiveFlvPlayback 检测

**Comment by hangchao** [comment]
返回undefined就是不支持，返回true就是支持吧？

**Comment by xqq** [comment]
Y

**Comment by MfNiu** [comment]
ios Safari 浏览器返回undefind

**Comment by ted-wq-x** [comment]
ios最新的Chrome返回也是undefined

**Comment by xqq** [comment]
因为 iOS 所有能上架的浏览器都是调系统 WebView，和 Safari 无差

**Comment by ted-wq-x** [comment]
这样的话在移动端就无法用flv实现直播了对吗？
