### ISSUE TITLE
flvjs是否限制了直播流的数量？

### ISSUE THREAD

**Issue by ThreeFat** [Bilibili/flv.js#341]
谦谦大神，我想询问一下，flvjs是否对浏览器播放的video数量做了限制，我发现当video数量大于6时，第6个video之后的流就加载不出来了，正常的用video播放视频文件可以播放不止6个，所以我想问一下是否是浏览器限制了直播流的数量吗？还是flvjs？

**Comment by xqq** [comment]
issue区搜
浏览器http1.1同目标服务器的并发连接数限制

**Comment by aute** [comment]
可以通过每 6 路分配一个不同的地址来解决
