### ISSUE TITLE
源码执行 npm run build构建后生成的flv.min.js文件导致webpack内存溢出

### ISSUE THREAD

**Issue by luxueyan** [Bilibili/flv.js#343]
// require('@/vendor/flv.min.js')
源码执行 npm run build构建后生成的flv.min.js文件 导致webpack内存溢出，flv.js 没问题，不知道为什么，感觉像是压缩导致的

**Comment by xqq** [comment]
，，，，

**Comment by luxueyan** [comment]
import flvjs from '@/vendor/flv.js'  这样没问题，但是flvjs是 {esmodule:true} 这个对象
所以只能这样使用
require('@/vendor/flv.js')
const flvjs = window.flvjs
而且如果是用flv.min.js直接导致webpack卡死

**Comment by luxueyan** [comment]
这应该和nodejs的内存控制相关，不添堵了，我已经换成webpack打包commonjs
