### ISSUE TITLE
Please provide ES5 version of module

### ISSUE THREAD

**Issue by joa** [Bilibili/flv.js#346]
A lot of tooling and browsers are not ES6-ready. Please consider compiling to ES5 before publishing to NPM.

ES6 Example: https://github.com/Bilibili/flv.js/blob/master/src/utils/logger.js

More Information: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by xqq** [comment]
The published npm package contains compiled & packaged es5 `flv.js` and `flv.min.js` in the `dist/` folder.
Also provided in https://github.com/Bilibili/flv.js/releases

**Comment by xqq** [comment]
https://github.com/Bilibili/flv.js/blob/master/package.json#L5

I think it has no problem. It has pointed to compiled file.

**Comment by joa** [comment]
Yes, that's exactly what happens and which triggers this issue in Webpack for me.

Steps to reproduce:
1. create-react-app foo
2. cd foo
3. yarn add flv.js
4. echo "import flvjs from 'flv.js'; flvjs.isSupported();" > src/index.js
5. yarn build

**Comment by xqq** [comment]
Oh I think in theory the whole flv.js `src/` should be compiled and packaged together with your app through the webpack pipeline in this situation.

BUT pay attention that the depended `webworkify` package may not be compatible with `webpack`, because it was designed for `browserify`.

**Comment by joa** [comment]
What happens is now: the vanilla ES6 is packaged and then minification fails for ES6. If you want to close this as Won't Fix I can understand.

**Comment by xqq** [comment]
So in my opinion, the flv.js `src/` should be compiled through your own build pipeline, that's all.

**Comment by joa** [comment]
Got it. Thanks for the swift reply!
