### ISSUE TITLE
VUE下打包报错

### ISSUE THREAD

**Issue by Ayhan-Huang** [Bilibili/flv.js#353]
非常感谢作者提供这么优秀的播放器给大家使用。

换了flvjs之后，实测直播延时比起hls有了很大改善，很开心。不过本地开发测试完成后，准备打包上线进行测试时，项目无法build。报错信息如下：
`ERROR in static/js/3.6831a658ccfb7e10c17e.js from UglifyJs
Unexpected token: name (s) [./~/flv.js/src/utils/exception.js:19,0][static/js/3.6831a658ccfb7e10c17e.js:1,2403]`

根据报错信息，找到出错位置：
`
class RuntimeException {

    constructor(message) {
        this._message = message;
    }

    get name() {
        return 'RuntimeException';
    }
`

于是google “uglifyjs unexpected token class”，找到些线索：https://github.com/webpack/webpack/issues/2972
https://swizec.com/blog/fun-surprise-uglifyjs-cant-es6/swizec/7272

参考以上信息，基本定位报错原因是 Uglify 无法解析ES6，而class关键字恰好是ES6中引入的。所以才会抛出上述句法错误的提示。

而Babel的作用就是将JSX/ES6文件转化为普通JS文件，项目中也是有配置的，并且之前build项目都没有问题。于是参考网上的回答：
1.修改项目的babel配置文件：.babelrc ， 增加uglify: true
2.并在项目的webpack中bable-loader加载器中使用以上babel配置：
不过还行不行。
也尝试了网上其他的一些答案进行修改，依然解决不了这个问题。

**Comment by Ayhan-Huang** [comment]
解决了：修改 webpack.base.conf.js 中 babel-loader 加载器配置，手动将flv.js加入babel转换目录，如图：

**Comment by banxia1014** [comment]
> 改 webpack.base.conf.js 中 babel-loader 加载器配置，手动将flv.js加入babel转换目录，如

您好，可以贴下截图么。
