### ISSUE TITLE
chrome直播时卡住恢复后有延时

### ISSUE THREAD

**Issue by xzzh999** [bilibili/flv.js#357]
Hi~ flv.js是一个很不错的http-flv库

我测试的时候发现如下现象(直播、无音频、无缓冲)：

ffplay 播放 rtmp 没有延时；
flv.js 在服务器的源已经拉起来的情况下，http-flv播放没有延时；
flv.js 在按需拉取到时候，http-flv播放有卡顿，然后能恢复，但是有延时；

拉取方式：nginx-http-flv-module 使用 exec_pull 按需拉取 ffmpeg
相关： https://github.com/winshining/nginx-http-flv-module/issues/59

chrome://media-internals:

![](https://raw.githubusercontent.com/xzzh999/markdown-pictures/master/1533810647.png)

chrome版本： 68.0.3440.84（正式版本） （64 位）

flv.js 的日志如下：

    browser support: true
    type: verbose, [MSEController] > MediaSource onSourceOpen
    type: verbose, [FLVDemuxer] > Parsed AVCDecoderConfigurationRecord
    type: verbose, [MSEController] > Received Initialization Segment, mimeType: video/mp4;codecs=avc1.4d001e

请问按需拉取时候，出现卡顿和延迟的原因可能是什么呢？

**Comment by xqq** [comment]
按需拉取是啥？客户端请求flv流时服务端才开始从源站pull？
看日志是没收到音频的 meta header，卡着等待了

**Comment by xzzh999** [comment]
@xqq 感谢答复

按需拉流是 [nginx-http-flv-module](https://github.com/winshining/nginx-http-flv-module) 支持的, 就是有请求的时候服务器才去拉流，否则释放掉流。

我传递的参数是不要音频，只要视频。

奇怪的是，我预先拉好流且不释放流，这样播放就没问题， 按需拉的时候就不行，画面会卡住

**Comment by winshining** [comment]
@xzzh999 按照你说的，使用exec_pull按需拉流，只拉视频流，重复至少10次，并没有卡顿。
下面是我测试的截图，能看出来flv.js正确解析了服务器推过来的流，因为右下角显示了静音标志，并且不可点击：
![no_audio](https://user-images.githubusercontent.com/3250905/44622292-59f66880-a8e8-11e8-8662-6d0e81760d96.png)

**Comment by xzzh999** [comment]
@winshining
我用的是chrome, 你用的是firefox, firefox我没用过。目前尚不清楚原因，但是我换成livego推流之后没问题了，关闭这个issue, 因为跟 flv.js 没关系。
