### ISSUE TITLE
播放直播时容忍RTMP的短暂中断

### ISSUE THREAD

**Issue by Anduin2017** [Bilibili/flv.js#358]
采用了SRS直播平台，转FLV格式。

部署方式
> RTMP向SRS推流，SRS使用FLV向用户分发。
> 使用bilibili/flv.js来在浏览器中为用户解码FLV。

向RTMP推流的程序（ffmpeg）会依次将视频列表推流，但问题在于：推流的过程中，一个视频结束后，会有极小的一段时间中断推流，但很快就会继续。

观察到的现象：
> 即使是很短的时间中断，用户观看到的视频都会卡住不再播放。必须重新加载播放器才能继续播放。

期待的现象：
> 当极短暂的时间里没有推流时，用户应当能够连贯的继续播放。

**Comment by xqq** [comment]
这个是 srs2 本身的问题，推流断过之后，后续推上去的就再也过不来了（不再向客户端推送）

srs3 怎么样不清楚

**Comment by Anduin2017** [comment]
bilibili/flv.js的ERROR事件似乎不会捕获这一错误。

我期待的是：当SRS发生短暂中断后继续，我能够使用flv.js捕获此事件，进而进行其它操作，例如记录日志、重启播放器等。

请问是否是我调用的接口不对，或有其它更好的方案？

**Comment by xqq** [comment]
http连接都没断，没有任何异常信息，无法检测

**Comment by Anduin2017** [comment]
好的。谢谢！

**Comment by Anduin2017** [comment]
其实我本不想打扰作者的……但是我将同样的问题咨询了srs。

他们的回复是：播放器的问题……
https://github.com/ossrs/srs/issues/1199

所以我现在很郁闷，我只是希望在网页上播放直播时，能够容忍信号源的极短暂中断。
但似乎问题无法确定，而我也想不到解决方案。

所以我计划重新开启此问题，寻求方案。

**Comment by weilaihui** [comment]
bilibili网站自己用的播放器是有检测的，bilibili网站用的方案不是该项目方案吧。
