### ISSUE TITLE
safari - Version 10.0 (12602.1.50.0.10) - 

### ISSUE THREAD

**Issue by myhu** [Bilibili/flv.js#36]
hey,

By using flv.min.js released version I have an issue only on Safari Version 10.0 (12602.1.50.0.10)

- the browser try to load 2 time-s load the url
first time safari complaining " an error occurred trying to load resources "
but the second GET is loading, I can see continuously downloaded chunk files, but I cannot see the video

Resources type: XHR 
and the initiator is es6-promise.js:2, where the issue is born

evry other browser is ok, Chrome, Firefox, doing the job, like a charm, but safari...

what gonna be the pitfall...

thx, in advance,

![safari fly js1](https://cloud.githubusercontent.com/assets/7011020/20563259/142cd27a-b188-11e6-8924-daeb7365bbcd.jpg)

**Comment by xqq** [comment]
Any error/warning logcat in Console?

**Comment by myhu** [comment]
no, any error on Console

**Comment by myhu** [comment]
and, forget to mention it was a live flv stream

var element = document.getElementsByName('videoElement')[0];
<------><------>var mediaDataSource = {
<------><------><------><------><------>"type" : "flv",
<------><------><------><------><------>"isLive" : true,
<------><------><------><------><------>"url" : "http://uri:1935/origin/Pubteszt02.flv"
<------><------><------><------><------>}
<------><------>player = flvjs.createPlayer(mediaDataSource, {
                    enableWorker: false,
                    lazyLoadMaxDuration: 3 * 60,
                    seekType: 'range',
                });
                player.attachMediaElement(element);
                player.load();

**Comment by xqq** [comment]
wow.
Because of the missing of fetch+stream API, 
http flv live stream playback is currently unavailable on Safari.

See https://github.com/Bilibili/flv.js/blob/master/docs/livestream.md

**Comment by myhu** [comment]
oooo, sorry, totally forget

is it possible to use fetch library import to flv.js?
https://github.com/github/fetch

**Comment by xqq** [comment]
No. polyfill cannot emulate stream I/O without browser support.
See https://github.com/Bilibili/flv.js/blob/master/src/io/fetch-stream-loader.js

If some feature can be implemented through polyfill, it can be implemented directly by the underlying API.
But unfortunately fetch+stream CAN NOT.

**Comment by myhu** [comment]
ooo, what a pity...

Your stuff is amazing, by the way...go on
I appreciate of your quick answer, and help...thx really
