### ISSUE TITLE
请问当视频播放过程中视频分辨率改变时，如果让播放器适应新的画面大小？

### ISSUE THREAD

**Issue by lin557** [bilibili/flv.js#362]
目前在测试一款车载dvr终端设备，设备支持子码流（分辨率 352 * 288）与主码流（分辨率 928 * 576）的动态切换。使用flv.js播放子码流，播放器正常播放。播放过程中切换成主码流时，播放器只能显示左上角约352 * 288大小的部份图像。有没有办法可以让播放器适应分辨率变化，显示全部图像？

flv采用h264编码，切换码流时 sps pps是同时更新的。

**Comment by xqq** [comment]
浏览器环境是什么？
是否有花屏或者绿屏部分？

如果要监视流分辨率变化可以取 `PlayerEvents.MEDIA_INFO` 事件里的字段
但是正常来说 video 元素内的画面一定是自适应缩放的

**Comment by lin557** [comment]
@xqq win7 x64 + chrome v68.x.x
不会花屏，也不绿屏，显示图像正常，只是显示大小不全。
PlayerEvents.MEDIA_INFO测试过，只有刚连接时获取到一次，中途终端设备切换分辨率后，没有再收到MEDIA_INFO事件。切换过程是在终端完成，前端播放器是不会需要重新连接的。
从播放器表面上看，收到流时从流中读取sps pps中的宽高（如352 * 288），然后创建播放窗口，播放过程中分辨率变化后，还是以这个宽高的比的区域显示图像。
![image](http://118.89.52.73/files/img/temp/error.png)

**Comment by lin557** [comment]
打开时只显示一次日志
type=verbose,log=[MSEController] > MediaSource onSourceOpen
flv.min.js:6 [MSEController] > MediaSource onSourceOpen
VM40172:31 type=verbose,log=[FLVDemuxer] > Parsed onMetaData
flv.min.js:6 [FLVDemuxer] > Parsed onMetaData
VM40172:31 type=verbose,log=[FLVDemuxer] > Parsed AudioSpecificConfig
flv.min.js:6 [FLVDemuxer] > Parsed AudioSpecificConfig
VM40172:31 type=verbose,log=[FLVDemuxer] > Parsed AVCDecoderConfigurationRecord
flv.min.js:6 [FLVDemuxer] > Parsed AVCDecoderConfigurationRecord
VM40172:31 type=verbose,log=[MSEController] > Received Initialization Segment, mimeType: audio/mp4;codecs=mp4a.40.2
flv.min.js:6 [MSEController] > Received Initialization Segment, mimeType: audio/mp4;codecs=mp4a.40.2
VM40172:31 type=verbose,log=[MSEController] > Received Initialization Segment, mimeType: video/mp4;codecs=avc1.64000d
flv.min.js:6 [MSEController] > Received Initialization Segment, mimeType: video/mp4;codecs=avc1.64000d
--------------------
到这里结束，切换分辨率后，没有收到新的日志信息。不清楚会否是我的h264流有问题，每个idr帧前都会新的sps pps。

**Comment by xqq** [comment]
只以收到 AVCDecoderConfigurationRecord 结构为准，由一个特殊的 flv h264 tag 封装，IDR 前的不算话

**Comment by lin557** [comment]
非常感谢 @xqq 的回复，我再找其它办法

**Comment by MiniCrab** [comment]
> 目前在测试一款车载dvr终端设备，设备支持子码流（分辨率352 * 288）与主码流（分辨率928 * 576）的动态切换。使用flv.js播放子码流，播放器正常播放播放过程中切换成主码流时，播放器只能显示左上角约352 * 288大小的部份图像。有没有办法可以让播放器适应分辨率变化，显示全部图像？
> 
> flv采用h264编码，切换码流时sps pps是同时更新的。

你好，最近我也碰到类似问题。
SPS/PPS里面会有分辨率，这个是解码层。
MP4只有在moov里有分辨率的记录，这个是封装层。
浏览器video标签怀疑只会初始化MP4 moov的分辨率，fmp4的moof里也没有分辨率，这就没办法在过程中不切换源的情况下做分辨率检查，onloadedmetadata事件我测试也不会触发。

**Comment by MiniCrab** [comment]
你最近有什么进展吗？
我本身的源是http fmp4的，后来我验证rtmp用flash播放没有问题，所以我想是否可以使用flv.js测试，但是目前看也不行。

**Comment by xqq** [comment]
fmp4 的 moof 里是会存 AVCDecoderConfigurationRecord 或 AudioSpecificConfig 的，怎么可能没有分辨率
而由 moof box 构成的 Initialize Segment 是浏览器认定的需要 reinit 解码器的必要标志和数据

简而言之：
如果切换分辨率，新的 AVCDecoderConfigurationRecord 必须包在 FLV AVCPacketType = 0 单独 tag 发；
切换音轨编码，必须有发新的 AudioSpecificConfig。

详细参考 video_file_format_spec_v10.pdf

**Comment by popomen** [comment]
@lin557 请问最后问题是如何解决的？

**Comment by lin557** [comment]
> @lin557 请问最后问题是如何解决的？

最后是每个idr都加上sps pps解决
