### ISSUE TITLE
"PIPELINE_ERROR_DECODE: video decode error"

### ISSUE THREAD

**Issue by hi-liz** [Bilibili/flv.js#369]
websocket的方式  chrome 下播放一分钟左右 会出现 **"PIPELINE_ERROR_DECODE: video decode error"**
 
然后出现 **MSEController] > Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.**

在 firefox 61.0.2  和 edge 均不会出现,可以正常的播放 
贴图如下，江湖救急

![1536113541 1](https://user-images.githubusercontent.com/16153267/45067134-44591e00-b0f4-11e8-95f0-659297b0c88d.jpg)
![1536113092](https://user-images.githubusercontent.com/16153267/45067137-48853b80-b0f4-11e8-9464-0eed920b329b.jpg)
![1536113405 1](https://user-images.githubusercontent.com/16153267/45067140-4de28600-b0f4-11e8-81ab-adc7c2b9b4f5.jpg)

**Comment by caozhantao** [comment]
我也遇到了这个问题，请问你怎么解决的呢？

**Comment by zhurizhe** [comment]
这个issue关闭了？谁帮忙能解释一下问题的根源是什么？谢谢！
