### ISSUE TITLE
Free sources to test library

### ISSUE THREAD

**Issue by ron666** [Bilibili/flv.js#37]
Can you indicate a list of some FLV files that can actually be played with this package, please? I tried to play and with Flash worked but with the library didn't.

https://www.sit.auckland.ac.nz/wiki/images/9/9f/Sample.flv
http://techslides.com/demos/sample-videos/small.flv

**Comment by xqq** [comment]
[flv.js] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported audio codec idx: 1
[flv.js] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 2
[flv.js] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported audio codec idx: 1
[flv.js] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 2
[flv.js] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported audio codec idx: 1
[flv.js] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 2
[flv.js] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported audio codec idx: 1
[flv.js] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 2

[flv.js] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported audio codec idx: 2
[flv.js] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 2
[flv.js] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported audio codec idx: 2
[flv.js] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 2
[flv.js] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported audio codec idx: 2
[flv.js] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 2
[flv.js] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported audio codec idx: 2
[flv.js] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 2

audio codec idx = 1: ADPCM
audio codec idx = 2: MP3

video codec idx = 2: H263

flv.js only supports H264+AAC codec according to the supported codec of the browser.

**Comment by ron666** [comment]
I see. Can you point then some valid sources I can use to test the library, please? I haven't found good ones

**Comment by xqq** [comment]
http://www.bilibili.com/

Switch to HTML5 player in the top right corner menu of the Flash player.

**Comment by ron666** [comment]
Thanks for the hint

**Comment by ron666** [comment]
Is there a way I can see the original file's URL in that website? I can only see the blob version of them

**Comment by xqq** [comment]
Chrome F12 Panel -> Network
then search `.flv`

**Comment by ron666** [comment]
Thanks

**Comment by KrisRoofe** [comment]
Not H264+AAC

**Comment by huangpeng19970609** [comment]
谢谢
