### ISSUE TITLE
检测支持 live 视频流的 API

### ISSUE THREAD

**Issue by EnixCoda** [bilibili/flv.js#371]
我在 IE 11 for Windows 10 上尝试播放 live 的 flv 视频流，可以看到 flv.js 发出了相关请求并持续产生了视频流量。但播放器无内容，console 没有报错信息。

我通过文档得知 IE 11 应当是不被支持播放 live 的。

但目前这种 不报错、不播放内容却产生请求的表现可能不是很妥当。

希望能 ~开放相关 API 或增强 `Flv.isSupported`~ 并在适时给出错误信息以帮助判断。

谢谢！

**Comment by EnixCoda** [comment]
重新细看了文档发现了相关 API [mseLiveFlvPlayback](https://github.com/Bilibili/flv.js/blob/master/docs/api.md#flvjsgetfeaturelist) 已被提供。

**Comment by xqq** [comment]
不支持 mseLiveFlvPlayback 不止 IE11 一个浏览器，事实上 Chrome Safari Edge 稍早一些的版本全都不支持。

**Comment by EnixCoda** [comment]
@xqq 嗯是的，错误信息里的内容是随手糊的 :D
