### ISSUE TITLE
播放flv出现SourceBuffer Error: [object Event]

### ISSUE THREAD

**Issue by Liu-Lin-Hai** [Bilibili/flv.js#377]
之前公司测试推流的flv能播放，但是app上手机直播出来的流地址，在pc端上就不能用，报错，我刚入行不就，所以不能找到问题所在，后端一直让我用电脑上的播放器试，说播放器能用，就说明没问题，可是我还是不相信，望大神帮忙看下，如下为报错的内容以及截图：
[MSEController] > Received Initialization Segment, mimeType: video/mp4;codecs=avc1.42c01e
[MSEController] > SourceBuffer Error: [object Event]
[MSEController] > MediaSource onSourceEnded
[MSEController] > SourceBuffer Error: [object Event]
[MSEController] > Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.

![image](https://user-images.githubusercontent.com/29696768/45664587-24d3e380-bb3f-11e8-9999-67bb428a69a1.png)

**Comment by Liu-Lin-Hai** [comment]
浏览器为69版本

**Comment by xqq** [comment]
音视频流有问题或不规范，导致浏览器播放器 pipeline 报错并退出
`chrome://media-internals` 下有浏览器提供的更详细 log

浏览器对 html5 MSE 视频有非常严格的规范限制
流问题请使用 ffprobe / FlvBugger 等工具分析问题并自行解决

**Comment by zeng16107** [comment]
视频编码是avc1.42c01e ，播放器flv.js不兼容。换成其他视频编码即可。

**Comment by zhang421755327** [comment]
我的是另外一种编码，一样报错Received Initialization Segment, mimeType: video/mp4;codecs=avc1.4d001f
