### ISSUE TITLE
播放直播流，提示[FLVDemuxer] > Found another onMetaData tag!

### ISSUE THREAD

**Issue by zoofox** [Bilibili/flv.js#378]
![image](https://user-images.githubusercontent.com/23308227/45678314-b6a41680-bb68-11e8-9a4c-b013f48e4687.png)
播放两秒就停止，出现上述错误。请问是怎么出现的，是直播流的问题么
配置参数：
{
                	type:format, 
                	url:url,
                	isLive:true,
                	hasAudio:true,
                	hasVideo:true
  }

**Comment by zoofox** [comment]
![image](https://user-images.githubusercontent.com/23308227/45683376-01785b00-bb76-11e8-9b14-acaf3ca080d2.png)

**Comment by xqq** [comment]
The logcat said that it's just a **Warning**, not a **Error**. Warnings means "ignorable".

For the other problems I don't know any more, and should not be flv.js's fault.
Check the video stream by yourself.
