### ISSUE TITLE
This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.

### ISSUE THREAD

**Issue by MofeLee** [Bilibili/flv.js#38]
`import flv from 'flv.js'`

![image](https://cloud.githubusercontent.com/assets/5069410/20655858/ad742316-b561-11e6-933c-0a6cd3afe60d.png)

使用create-react-app的配置直接引用flv.js发出的警告，可不可以同时release一份未打包的源代码？

类似使用`babel-cli`转换一下源代码，然后使用者可以通过`import flv from 'flv.js/lib/flv'`来使用flv.js
![image](https://cloud.githubusercontent.com/assets/5069410/20655931/5fb295d0-b562-11e6-9946-8360138765bf.png)

**Comment by xqq** [comment]
我不认为直接引用打包版有什么问题，只要能正常运行，无视warning即可。

另外，npm包里是有源码的，尝试引用src目录下的文件

**Comment by MofeLee** [comment]
会有些问题的，直接引用源代码整个项目中polyfill的只会有一份，而使用打包后的会有两份相同的polyfill代码在最终的bundle中

**Comment by xqq** [comment]
为什么会有两份polyfill？

**Comment by MofeLee** [comment]
类似`Object.assign`

搜索源代码时可以发现有这样一段代码
![image](https://cloud.githubusercontent.com/assets/5069410/20656050/7eb29d76-b563-11e6-8f17-86d3bb89df8c.png)

这段代码在使用flv.js的项目也会有一份。

而且npm包直接引用src目录下的文件需要特意为flv.js配置，因为两个项目中使用的babel配置文件可能不同，如果直接用可能导致编译出问题（概率可能不大，但是有可能）

**Comment by xqq** [comment]
Polyfill之前会检测全局是否有，没有不会inject，所以不会互相干扰

你这截图应该是sourcemap文件里的吧

**Comment by MofeLee** [comment]
我的意思是会增加文件的体积。

**Comment by xqq** [comment]
babel 配置仅有 "presets": ["es2015"]，应该没有互兼容问题

dist/flv.js 中只有一份 polyfill 代码

**Comment by MofeLee** [comment]
嗯，我只是提供一个建议。

我认为一个项目里有两套打包程序会有问题，但是现在我无法证明会有问题。这个issue可以放在这里等以后再补充

**Comment by weizhenye** [comment]
polyfill 不应该单独写一个文件 install，而是去依赖第三方库，这样用户如果自己引入了同样的库比如 [object-assign](https://www.npmjs.com/package/object-assign)，最终输出就一份了。单独写成文件都没法 tree-shaking。

JS 库的打包建议使用 [rollup](https://github.com/rollup/rollup)，打包出来的文件又小又好看，可以参考[我的项目](https://github.com/weizhenye/Danmaku/blob/master/package.json#L15)。另外在 package.json 里可以加句 [`"jsnext:main": "src/flv.js"`](https://github.com/rollup/rollup/wiki/jsnext:main)，用户如果自己有构建流程，可以直接引用 `src/flv.js`。

另外看了下 `gulpfile.js`，里面的各个任务基本用 npm scripts 一句话就写完了，可以考虑干掉 gulp。

**Comment by xqq** [comment]
90c179929a7cf2e0c9f5eab599f46e9d59a4bfd8
Added `jsnext:main`, thanks @weizhenye

**Comment by weizhenye** [comment]
@xqq 

For now, `module` is recommended, though `jsnext:main` is still supported by webpack and rollup.

https://github.com/rollup/rollup/wiki/jsnext:main

**Comment by zcoding** [comment]
建议用 rollup 打包
