### ISSUE TITLE
FLV in iOS

### ISSUE THREAD

**Issue by ron666** [Bilibili/flv.js#39]
I tested the library on iOS (specifically iPhone 5s) and the plugin didn't work. Does the plugin support iOS devices?

**Comment by ron666** [comment]
I think it had to do with the file I was using. Is there a FLV I can use from you to put it as a test file that doesn't give me a 403 after a certain period of time? Or point a good one I can use? I haven't been able to find one

**Comment by ron666** [comment]
No I changed it and still didn't work on iOS. Any advise?

**Comment by xqq** [comment]
Requires (Media Source Extensions)[http://caniuse.com/#search=mediasource] API which is missing in iOS Safari.

There's no solution.

**Comment by ron666** [comment]
I see. For other browsers, do you have a flv I can reference that doesn't get me a 403 after a certain period of time? I tried one of yours but eventually it will become unaccessible because of the key in the URL

**Comment by xqq** [comment]
link: http://pan.baidu.com/s/1sl4bJhb
password: wrd2

Upload them to your video server by yourself.

**Comment by ron666** [comment]
Thanks

**Comment by amjadharri** [comment]
Also not working on Chrome on IOS

**Comment by xqq** [comment]
Because Chrome ios is based on the system's webview which is consistent with Safari's underlying core
