### ISSUE TITLE
请问flvjs支持IE 11吗？

### ISSUE THREAD

**Issue by hacker0000** [Bilibili/flv.js#390]
我在根目录下README.md里发现说可以支持ie11

但是在docs/livestream.md里却没有找到兼容ie11的说法

然后实测是没有办法在ie11播放的。。

请问flvjs对ie11究竟支持如何呢？谢谢！

**Comment by xqq** [comment]
http-flv live stream is unsupported under IE11
websocket-flv is ok

**Comment by hacker0000** [comment]
感谢回复！！
