### ISSUE TITLE
目前浏览器似乎采用WebAssembly能解决h265播放问题，请问谦谦有计划做这方面的兼容？ 

### ISSUE THREAD

**Issue by omaiga1231** [Bilibili/flv.js#394]

**Comment by scottMan1001** [comment]
- 目前后台也提出了希望然我前台解析H245。。。

**Comment by omaiga1231** [comment]
@

> * 目前后台也提出了希望然我前台解析H245。。。

**Comment by xqq** [comment]
能，没计划

**Comment by scottMan1001** [comment]
> @ scottMan1001那你们现在有什么比较好的方案？目前我们是后台用ffmepg将H265 H264转为，前端用flv.js播放。但是这样对服务器的CPU消耗特别大，比如普通酷睿i7电脑，源监控视频流是1080的，
> 转码一路视频流就需求消耗百分之10几的CPU，内存占用快200M;如果并发量高点，比如20个，服务器根本抗不住，难道只能靠上硬件了？

我给后台的建议就是让他们把H265转H264- - ，，看来你们走了更快的。。你们现在是如何解决呢

**Comment by omaiga1231** [comment]
@scottMan1001 @scottMan1001 用ffmpeg将rtsp转为rtmp协议，再利用node-media-server转为ws协议，延时大概在1s多点；性能考虑，要注意推流和停止推流的控制。目前方案我觉得还不够理想，云台控制时出现的延时1s多，体验不太好，服务器性能也是问题。

**Comment by omaiga1231** [comment]
@xqq 嗯，谢谢提供硬件加速的思路，现在开发还在windows平台，试了用dxva2加速，但是没效果；后续看看在linux环境试下vaapi，但感觉应该效果不太好；可能要靠VDPAU了。

**Comment by xqq** [comment]
Intel -> VAAPI(linux) / qsv(linux/win)
NVIDIA -> VDPAU(linux)

**Comment by 823639792** [comment]
@omaiga1231 我采用同样的方法，只能做到3秒的延时，能分享下你的ffmpeg命令行和flv.js的设置吗？

**Comment by nanguantong** [comment]
已经支持flv h265，移步至：https://github.com/nanguantong/flv-h265.js

**Comment by SuperChrisliu** [comment]
chrome最新版107已经支持h265喽

**Comment by 823639792** [comment]
有没有比较友好的方法，判断当前浏览器是否支持h265呢？

**Comment by SuperChrisliu** [comment]
> 有没有比较友好的方法，判断当前浏览器是否支持h265呢？

你看上面那个兄弟，已经支持了h265，里面有检测是否支持的代码
