### ISSUE TITLE
safari下播放几分钟画面暂停

### ISSUE THREAD

**Issue by zoofox** [Bilibili/flv.js#399]
环境描述：
safari版本 11.0.3，
http-flv直播流，
config:{
autoCleanupSourceBuffer: true
},
MediaDataSource:{
      type:'flv',
      url: url,
      isLive: true,
      hasAudio: true,
      hasVideo: true,
      cors: true
}
现象：
safari浏览器下播放一段时间后（时长不一定，可能一分钟可能十几分钟），画面自动暂停。console没有打印播放器错误。
每次出现该现象时会先触发video的oncanplay和oncanplaythrough事件。
打印currentTime和buffered.end(0)，显示两者值很接近，是否是没有新的缓存数据进来导致的画面暂停，并且一直暂停不动。

**Comment by zoofox** [comment]
mac safari浏览器下oncanplaythrough后大概率出现播放暂停，目前我这边判断暂停后执行play()恢复播放来处理该问题。猜测是safari下不允许自动播放导致。

**Comment by hacker0000** [comment]
同遇到此问题，来记录一下：
其实是因为Safari在video标签播放直播流的时候
进度点一直会逼近进度条的最终点
当因为网络不稳定导致数据没有及时进来时
进度点到了最终点，并停止了逼近动作
Safari的video就暂停了。。等又来数据后还是什么也不做，造成隐藏controls的时候像画面卡住
临时解决思路大致是注册video标签的onpause回调，然后去执行video.play()，当然可以加些浏览器判断或者setTimeout之类的逻辑，当然加了后用户点暂停按钮就无效了哈哈
