### ISSUE TITLE
能介绍一下再微信内置浏览器的兼容性吗

### ISSUE THREAD

**Issue by shanshuiren** [Bilibili/flv.js#40]
麻烦介绍下iOS和Android平台下在微信内置浏览器使用flv.js播放http-flv的可能性及兼容性，谢谢。

**Comment by xqq** [comment]
Not tested, yet

**Comment by ls84** [comment]
感觉微信用什么内核不是一个很简单的问题，这里有个腾讯员工在知乎上回答了一下[微信浏览器到底是什么内核？](https://www.zhihu.com/question/22082084)曾经测试过iOS上的微信内核是: [Mobile Safari UIWebView 10.1.1 (iOS 10.1.1)]，小米5的微信内核是: [Chrome Mobile 37.0.0 (Android 6.0.1)]（也没有装什么浏览器）。感觉因此这个兼容性只能在不同设备上测试才行。

**Comment by xqq** [comment]
没记错的话，目前的 X5 是一个基于旧版 Chromium 魔改的内核。
总之两个必要条件：Media Source Extensions API 和 fetch+stream API 对 http-flv 是必须的

**Comment by fomenyesu** [comment]
楼主测试了吗？分享一下吧
