### ISSUE TITLE
播放远端存储视频，谷歌console打印内容如下

### ISSUE THREAD

**Issue by scottMan1001** [bilibili/flv.js#405]
flv.min.js:6 [MSEController] > MediaSource onSourceOpen
flv.min.js:6 [FLVDemuxer] > Parsed onMetaData
flv.min.js:6 [FLVDemuxer] > Parsed AVCDecoderConfigurationRecord
flv.min.js:6 [MSEController] > Received Initialization Segment, mimeType: video/mp4;codecs=avc1.42c01e
flv.min.js:6 [MSEController] > MediaSource onSourceEnded     
   页面是一个图片，双击图片会加载远端视频。 问题在于，我加载时打印上面的打印信息，但是页面不显示视频播放界面，除非我再次点击页面。才能播放。。请问有没有人遇见过这样的问题。

**Comment by zxzfcsu** [comment]
我也遇到了这个问题，请问楼主解决了吗？
