### ISSUE TITLE
服务端渲染的页面中使用 flv.js 时 self is not defined (nuxt.js)

### ISSUE THREAD

**Issue by Micanss** [Bilibili/flv.js#416]
项目使用 [nuxt.js](https://github.com/nuxt/nuxt.js) 框架，直播页面使用 flv.js，在组件中引入 flv.js 模块，刷新直播页面时，nuxt 会进行 ssr ，此时页面会报错：self is not defined....，不知道 flv.js 对于服务端渲染是否有处理？还是需要在 nuxt 的配置上做修改？
![image](https://user-images.githubusercontent.com/11270415/50806991-e9e6fd00-1333-11e9-8eba-03aac0957668.png)

**Comment by Micanss** [comment]
@xqq 改代码的方式不太灵活，部署的时候还会有问题。已经通过变通的方式绕过了这个问题，判断 process.client 是否为客户端，然后再 require flv.js 模块，就不会进行服务端渲染。

**Comment by Hxmic** [comment]
你们是怎么解决的了？

**Comment by ACChe** [comment]
> @xqq 改代码的方式不太灵活，部署的时候还会有问题。已经通过变通的方式绕过了这个问题，判断 process.client 是否为客户端，然后再 require flv.js 模块，就不会进行服务端渲染。

给个代码出来学些一下，谢谢

**Comment by eyea** [comment]
这个问题后续是否有更新呢？

> 先手工把 `self.` 去掉试试吧
> 
> 本来是用来在前端主线程(window)和webworker(DedicatedWebWorker)之间用统一名字指代全局对象的

@xqq

**Comment by easy261925** [comment]
同样遇到这个问题

**Comment by galaxy-s10** [comment]
+1

**Comment by ali-fuu** [comment]
> 

时隔4年的回复 😂，类似酱紫。
```
let flvjs
if (process.client) {
  flvjs = require('flv.js').default
}
```

**Comment by galaxy-s10** [comment]
> > 
> 
> 时隔4年的回复 😂，类似酱紫。
> 
> ```
> let flvjs
> if (process.client) {
>   flvjs = require('flv.js').default
> }
> ```

这个倒知道~
