### ISSUE TITLE
在safari下不能播放

### ISSUE THREAD

**Issue by hongweiqu** [Bilibili/flv.js#42]
在MAC air 下的safari不能播放
safari版本： 10.0.1 (12602.2.14.0.7)
系统版本：10.12.1 (16B2657)

错误提示如下：
![play](https://cloud.githubusercontent.com/assets/3480291/21003303/9489ac70-bd65-11e6-85f8-f9aa628e3bca.png)

**Comment by xqq** [comment]
直播还是点播，console里有哪些报错

**Comment by hongweiqu** [comment]
直播，console里没有报错

**Comment by xqq** [comment]
Safari 暂不支持 http-flv
https://github.com/Bilibili/flv.js/blob/master/docs/livestream.md

**Comment by hongweiqu** [comment]
呃 踩坑了 用这个就是来支持mac safari的
有没有交流QQ群，方便沟通

**Comment by xqq** [comment]
没有。
