### ISSUE TITLE
请教了~IE11播放问题

### ISSUE THREAD

**Issue by 37266542** [Bilibili/flv.js#45]
我编译后用此播放srs2.0(http+flv)直播时，firefox等浏览器都可以，就是IE11不行

**Comment by xqq** [comment]
是的，IE11不支持流式IO，Edge也不行

**Comment by 37266542** [comment]
谢谢回答~

**Comment by 37266542** [comment]
还有一个问题，同一个客户端，同一个浏览器（firefox或chrome）是不是只能打开6个直播？

**Comment by xqq** [comment]
理论上没有这样的限制

**Comment by 37266542** [comment]
那就奇怪啦~

**Comment by xqq** [comment]
看看卡加载的那个页面的F12 Network中是不是Pending状态。怀疑可能是同目标服务器并发连接数限制

**Comment by myfreeer** [comment]
http://www.browserscope.org/?category=network&v=top
http://stackoverflow.com/questions/985431/max-parallel-http-connections-in-a-browser
是浏览器的限制

**Comment by dongyang03** [comment]
@myfreeer 
打开6个流是http1.X的限制。http1.x在浏览器上，最多允许同事建立6个链接。
要解决此问题，可以用http2.0。或者多域名。

**Comment by DenySu** [comment]
@dongyang03  目前有没有http2.0的server呢？

**Comment by myfreeer** [comment]
@DenySu HTTP/2的实现： <https://github.com/http2/http2-spec/wiki/Implementations>
