### ISSUE TITLE
这是不再维护了吗，这么多Issues都不处理？

### ISSUE THREAD

**Issue by gd-ldj** [bilibili/flv.js#450]
import flvJs from 'flv.js'; 
有警告
——————
已自行解决

**Comment by zeybar** [comment]
> import flvJs from 'flv.js';
> 有警告
> ——————
> 已自行解决

怎么解决的？我这里直接报error了

**Comment by zeybar** [comment]
@gd-ldj

**Comment by gd-ldj** [comment]
也可能跟自身框架编译有关，导入flv.js后，警告flv.js是编译过的，webpack配置，对这个包不再编译就行了
