### ISSUE TITLE
Cannot play flv file, Codec Unsupport?

### ISSUE THREAD

**Issue by zjsxwc** [Bilibili/flv.js#47]
the flv file i tested is this url: http://www.e0575.com/about/images/e0575.flv  . when i execute the  `flvPlayer.load();`, it throws the exceptions below. how can i fix the problem?

>flvjs.isSupported()
true

>flvPlayer
FlvPlayer {TAG: "FlvPlayer", _type: "FlvPlayer", _emitter: EventEmitter, _config: Object, e: Object…}

>flvPlayer.attachMediaElement(videoElement);
undefined
logger.js:99 [MSEController] > MediaSource onSourceOpen

>flvPlayer.load();
undefined
FLVDemuxer] > Parsed onMetaData
logger.js:32 [TransmuxingController] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported audio codec idx: 2e @ logger.js:32_onDemuxException @ transmuxing-controller.js:333_parseAudioData @ flv-demuxer.js:429parseChunks @ flv-demuxer.js:292_onInitChunkArrival @ transmuxing-controller.js:264_dispatchChunks @ io-controller.js:419_onLoaderChunkArrival @ io-controller.js:503(anonymous function) @ fetch-stream-loader.js:158
logger.js:32 [TransmuxingController] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 2e @ logger.js:32_onDemuxException @ transmuxing-controller.js:333_parseVideoData @ flv-demuxer.js:647parseChunks @ flv-demuxer.js:295_onInitChunkArrival @ transmuxing-controller.js:264_dispatchChunks @ io-controller.js:419_onLoaderChunkArrival @ io-controller.js:503(anonymous function) @ fetch-stream-loader.js:158
2logger.js:32 [TransmuxingController] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported audio codec idx: 2

And here is my html code:
```
<script src="/flv.js"></script>
<video id="videoElement"></video>
<script>
  if (flvjs.isSupported()) {
    var videoElement = document.getElementById('videoElement');
    var flvPlayer = flvjs.createPlayer({
      type: 'flv',
      url: '/e0575.flv'
    });
    flvPlayer.attachMediaElement(videoElement);
    flvPlayer.load();
  }
</script>
```

**Comment by xqq** [comment]
Not H264+AAC

**Comment by zjsxwc** [comment]
solved the problem.
just  use the ffmpeg to convert the video.
```
 ffmpeg -i e0575.flv -vcodec libx264 -c:a aac   converted.flv
```

**Comment by wuliZXF** [comment]
@zjsxwc Thanks!
