### ISSUE TITLE
video element is invalid when running 'flvPlayer.attachMediaElement(videoElement);'

### ISSUE THREAD

**Issue by rocky1001** [Bilibili/flv.js#48]
Hi I noticed there is a problem in README 'Getting Started' part.
When calling 'flvPlayer.attachMediaElement(videoElement);' , the videoElement is not initialized correctly.

The demo code can be changed to:

```javascript
document.addEventListener("DOMContentLoaded", function(event) {
		console.log("DOM fully loaded and parsed");
		if (flvjs.isSupported()) {
			var videoElement = document.getElementById('videoElement');
			console.log(videoElement)
			var flvPlayer = flvjs.createPlayer({
				type: 'flv',
				url: 'http://example.com/flv/video.flv'
			});
			flvPlayer.attachMediaElement(videoElement);
			flvPlayer.load();
			flvPlayer.play();
		}
    });
```

**Comment by xqq** [comment]
You are right. Actually I just want to keep it simple stupid for README, like the demo in hls.js/README.

The full demo in `demo/index.html` initializes the player after `DOMContentLoaded` event.
