### ISSUE TITLE
@xqq 改代码的方式不太灵活，部署的时候还会有问题。已经通过变通的方式绕过了这个问题，判断 process.client 是否为客户端，然后再 require flv.js 模块，就不会进行服务端渲染。

### ISSUE THREAD

**Issue by Erik5169** [bilibili/flv.js#490]
@xqq 改代码的方式不太灵活，部署的时候还会有问题。已经通过变通的方式绕过了这个问题，判断 process.client 是否为客户端，然后再 require flv.js 模块，就不会进行服务端渲染。

_Originally posted by @Micanss in https://github.com/bilibili/flv.js/issues/416#issuecomment-452537264_

我遇到跟你一样的问题了， 你是怎么解决的， 能贴下代码看看吗？

**Comment by eyea** [comment]
nuxt 配置文件  plugins 可以判断 mode: 'client' 即为客户端环境
