### ISSUE TITLE
not supported audio codec mp3

### ISSUE THREAD

**Issue by turbidsoul** [Bilibili/flv.js#51]
Unsupported audio codec idx: 2

**Comment by zjsxwc** [comment]
hi, i think u could convert the video file using audio codec aac,
```
ffmpeg -i your.flv -vcodec libx264 -c:a aac   converted.flv
```

https://github.com/Bilibili/flv.js/issues/47#issuecomment-267544518

**Comment by dimpiax** [comment]
what about without converting? What is the issue to support such files?

**Comment by xqq** [comment]
Among all the implementation of MSE, there's no browser supports fragmented MP4 with MP3 audio track.
Typically, they only support AAC audio track within fragmented MP4.

**Comment by xqq** [comment]
implemented
