### ISSUE TITLE
DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 2

### ISSUE THREAD

**Issue by VariantChan** [bilibili/flv.js#512]
是播放的音频格式不支持的意思吗？
logger.js?7d8e:38 [TransmuxingController] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 2
e @ logger.js?7d8e:38
_onDemuxException @ transmuxing-controller.js?f7c4:362
_parseVideoData @ flv-demuxer.js?f0c4:841
parseChunks @ flv-demuxer.js?f0c4:343
_onInitChunkArrival @ transmuxing-controller.js?f7c4:278
_dispatchChunks @ io-controller.js?85e6:438
_onLoaderChunkArrival @ io-controller.js?85e6:529
logger.js?7d8e:123 [MSEController] > Received Initialization Segment, mimeType: audio/mpeg
38events.js?faa1:135 Uncaught (in promise) Error: Unhandled error. (undefined)
    at EventEmitter.emit (events.js?faa1:135)
    at EventEmitter.eval (flv-player.js?0081:239)
    at EventEmitter.emit (events.js?faa1:146)
    at eval (transmuxer.js?8780:195)

**Comment by QZEming** [comment]
我也遇到这个问题，一直解决不了

**Comment by sunkangchina** [comment]
同样的问题。
Unsupported codec in video frame: 2
有解决方案吗

**Comment by travelhawk** [comment]
I get the same error when trying to play a http flv stream. How to fix this?

**Comment by VariantChan** [comment]
> 我也遇到这个问题，一直解决不了

MP3->ACC

**Comment by VariantChan** [comment]
> 同样的问题。
> Unsupported codec in video frame: 2
> 有解决方案吗

MP3->ACC

**Comment by VariantChan** [comment]
> I get the same error when trying to play a http flv stream. How to fix this?

MP3->ACC

**Comment by travelhawk** [comment]
What if I don't send audio at all?

**Comment by wangjing971030** [comment]
你们解决了吗？

**Comment by qq2575896094** [comment]
@VariantChan  MP3->ACC 如何操作

**Comment by GuaoGuao** [comment]
如果你是自己推流的，指定一个解码器，比如加个参数 -vcodec libx264，或者你自己想用的解码器就好了

**Comment by cuixiren** [comment]
ffmpeg命令加 -an 去除音频

**Comment by yanming0924** [comment]
请问现在解决方案是什么

**Comment by tkkDeveloper** [comment]
如果发现不支持此音频格式，直接可以将hasAudio设置为false;不影响视频的播放；

**Comment by tkkDeveloper** [comment]
如果发现不支持此音频格式，直接可以将hasAudio设置为false;不影响视频的播放；
flvjs.LoggingControl.addLogListener(function(type, str){
    let errorStr = '[TransmuxingController] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported audio';
    if(str.indexOf(errorStr !== -1)){
        // hasAudio 设置为false
   }
   
})

**Comment by songbiaoself** [comment]
我在用javacv对接海康威视，一有音频就卡死，我自己推送的包含音频就可以播放

**Comment by sansan-mei** [comment]
hasAudio setting to false is all right
