### ISSUE TITLE
如何获取websocket实例

### ISSUE THREAD

**Issue by yedajiang44** [bilibili/flv.js#523]
我ws服务端需要鉴权后才能正常通讯，所以我需要ws实例，或者又没有连接相关事件啥的，亦或者可不可以直接将byte[]传给flv.js直接播放

**Comment by xqq** [comment]
https://github.com/Bilibili/flv.js/blob/master/src/config.js#L49
#307

**Comment by yedajiang44** [comment]
> https://github.com/Bilibili/flv.js/blob/master/src/config.js#L49
> #307

代码里具体咋获取啊？

**Comment by xqq** [comment]
意思是自己把字节流拆出来之后，用 customLoader 的形式自己实现一个 loader 把字节流提供给 flv.js。
继承 flvjs.BaseLoader，然后仿照 io/fetch-stream-loader.js 或者 io/xhr-moz-chunked-loader.js 实现一个就行

**Comment by boyyi** [comment]
敢问楼主解决了吗

**Comment by chenjunhuan666** [comment]
> 敢问楼主解决了吗

同问

**Comment by yedajiang44** [comment]
作者说了怎么弄，但是我没做

如果你也是想鉴权后再交互，那完全可以借助`http`去做，比如
```
ws:localhost?token=123456
```
然后在ws服务器端握手时获取`token`参数进行鉴权，最终觉得是否给予建立链接

**Comment by chenjunhuan666** [comment]
let player = flvjs.createPlayer({
                    type: 'flv',
                    url: 'ws://192.168.1.1/live',
                    isLive: true,
                    hasAudio: false,
                    muted: true
                },{
                    // enableStashBuffer: false,
                })
我目前是这么配置我的flvjs，用的websocket，我是在url直接填上ws形式的url，视频流没出来，是还需要其他的配置才可以进行ws流的播放吗？

**Comment by yedajiang44** [comment]
这个要看你服务端是如何处理的
> 正常情况下flv会等待第一帧音频（现在的版本不知道是不是这样）
- 服务端是否有数据发过来
- 返回的数据是否符合flv编码格式
- 符合编码要求的情况下是否包含音频，如果包含音频，确定是否有音频数据过来，过来的情况下确定音频数据编码正确性以及时间戳

**Comment by chenjunhuan666** [comment]
ok， respect bro
