### ISSUE TITLE
支持的音频数据格式有哪些

### ISSUE THREAD

**Issue by yedajiang44** [bilibili/flv.js#528]
```
flv.支持的音频.forEach(x->{
      console.log(x);
}
```
@xqq

**Comment by xqq** [comment]
AAC, MP3

**Comment by yedajiang44** [comment]
> AAC, MP3

如果我直播的时候flvheader里指明没有音频，而过了几分钟后，又需要下发音频数据给播放器，这时候需要服务器重新下发flvheader吗？

**Comment by xqq** [comment]
会仍然没有音频，但不会触发异常，不影响继续播放。
由于相关逻辑的判定较复杂，因此目前的策略是在播放器加载视频时必须可知是否存在音视频轨道（自主提供 hasAudio/hasVideo
或者从视频头信息中可以准确判定是否包含音视频轨道）。
当视频开播后（第一个 Media Segment 被 appendBuffer 之后），MSE 不允许再动态添加新的 SourceBuffer
了，因此不可能做到以无音频初始化开播后，后续动态创建音频轨道

在 2020年1月7日週二 15:06，yedajiang44 <notifications@github.com> 寫道：

**Comment by xqq** [comment]
https://github.com/bilibili/flv.js/blob/master/src/demux/flv-demuxer.js#L476
目前来看没有丢弃后续才来的音频包，不需要也不能重传flvheader，不确定能否正常播放

**Comment by yedajiang44** [comment]
> https://github.com/bilibili/flv.js/blob/master/src/demux/flv-demuxer.js#L476
> 目前来看没有丢弃后续才来的音频包，不需要也不能重传flvheader，不确定能否正常播放

也就是说flvheader可以不用管，那Aac包呢？？

**Comment by xqq** [comment]
AAC 头 AudioSpecificConfig 肯定要

**Comment by yedajiang44** [comment]
> AAC 头 AudioSpecificConfig 肯定要

好的，等会挨个试试看

**Comment by yedajiang44** [comment]
> AAC 头 AudioSpecificConfig 肯定要

说到AudioSpecificConfig，我搞了好久都没搞清楚最后三个字节0x56, 0xe5, 0x00是由什么组成的？？

**Comment by yedajiang44** [comment]
> https://github.com/bilibili/flv.js/blob/master/src/demux/flv-demuxer.js#L476
> 目前来看没有丢弃后续才来的音频包，不需要也不能重传flvheader，不确定能否正常播放

经过尝试，flvheader里指定没有音频，但是在flv文件的中途写入音频后，flv.js是可以播放的，只不过会直接跳过没音频的视频而已
