### ISSUE TITLE
如何播放h264的裸流

### ISSUE THREAD

**Issue by zgy520** [Bilibili/flv.js#56]
我通过websocket将h264的视频流（一帧一帧传递的）传到了前台的js文件中，但是在播放该视频流的时候没有找到合适的解决方案！应该是将h264的裸流转换为flv格式的文件，但是这个转换过程是怎样进行的，是把传递过来的每一针转换为一个flv的文件还是将一段时间内的所有帧转化为flv的视频文件？转换为flv是该如何在js中进行的？研究了几天，都没有进展，希望大家能给个好一点的解决方案！

**Comment by xqq** [comment]
flv-demuxer.js 负责从 flv 里解出 h264 包，所以不应该再将 h264 裸流转换为 flv 格式。

按照 h264 raw stream 的格式（即 0001 startcode 隔开）拆分出 Nalu，修改为 AVC1 (length-header) 格式，
送给 mp4 混流器即可。

**Comment by zgy520** [comment]
@xqq 能否说的详细一点，最近才接触，没看太懂？？

**Comment by 37266542** [comment]
这个裸流如果用IE11来请求的话, 也会发生不支持流式io的情况吗?

**Comment by ilymiao** [comment]
听说从Bilibili走了，特意过来看一下flv.js

**Comment by Moran349** [comment]
@xqq 
分析flv.js代码，在将avc1格式送给mp4混流器之前，flv-demuxer首先解析了flv的AVCDecoderConfigurationRecord，但是对于h264裸流并没有相关的内容，希望作者大大给点建议！
处理aac音频裸流也有相同的问题。。。

**Comment by xqq** [comment]
用SPS PPS Nalu手工打包出AVCDecoderConfigurationRecord结构
如果你所说的aac裸流是指ADTS，那么手工打包为ASC头

**Comment by Moran349** [comment]
@xqq 
在根据sps手工打包出AVCDecoderConfigurationRecord结构后，remuxer将mp4片段喂给mse时，一直在报如下错误：
![image](https://cloud.githubusercontent.com/assets/16449933/22179355/336c3684-e08c-11e6-9257-d814ec3f95df.png)
对于mse相关的内容我了解的不是很多，还请作者大大指点！

**Comment by Moran349** [comment]
chrome://media-internals/ 信息如下：
![image](https://cloud.githubusercontent.com/assets/16449933/22179638/cad061f0-e094-11e6-9f59-799b0ea771d4.png)

**Comment by xqq** [comment]
说明 AVCDecoderConfigurationRecord 结构不对- -

**Comment by Moran349** [comment]
@xqq 
修改AVCDecoderConfigurationRecord结构后，可以播放出视频图像，但是只能显示出 I 帧片段，并不连续
查看chrome://media-internals/出现如下debug信息：
![image](https://cloud.githubusercontent.com/assets/16449933/22189661/e0ab1dca-e158-11e6-92be-ac37acf2d333.png)
而且，想问一下作者大大，对于直播流来说，音视频流的duration该如何处理?

**Comment by xqq** [comment]
DTS 没打对？

每帧的 sample duration 等于后一帧 DTS 减该帧 DTS

**Comment by Moran349** [comment]
@xqq 
的确dts没有打对，更改后可以正常的显示出视频。
但是视频速率明显偏快；而且之前chrome://media-internals的debug信息仍然存在？

**Comment by Moran349** [comment]
@xqq 
上述问题已解决，经测试发现是dts的时间精度问题
感谢作者大大的指导

**Comment by snow2fisher** [comment]
@Moran349  
你好，代码能让我参考一下吗？我也在做websocket传H264码流，用mse播放。但是不知道怎么送mp4remuxer。谢谢

**Comment by Moran349** [comment]
@snow2fisher 
抱歉代码是在公司内开发的，非我个人所有，并不能分享。
如果你有什么问题的话，可以通过邮件联系我

**Comment by losper** [comment]
@Moran349 @xqq  两位大佬，请问实现H264的直播，是否需要先区分I、P、B帧，并按照IPB顺序打上DTS时间？PTS就只需要直接递增？

**Comment by Moran349** [comment]
@losper 对于H264视频直播，不会存在B帧，只需要将获取到的I、P帧按序打上DTS&PTS
DTS/PTS由每一帧的时间戳决定

**Comment by losper** [comment]
@Moran349 你好，谢谢回复，按你所说是否把B帧丢弃？时间戳是否可以由自己按29ms填充？

**Comment by zhubinsheng** [comment]
> @Moran349
> 你好，代码能让我参考一下吗？我也在做websocket传H264码流，用mse播放。但是不知道怎么送mp4remuxer。谢谢

解码后播放 例如Broadway
