### ISSUE TITLE
使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？

### ISSUE THREAD

**Issue by zhgt1997** [bilibili/flv.js#560]
以下是使用 flv 的代码，但就是不管用。。
```
videoFlv(viodeUrl) {
      this.$nextTick(() => {
        if (flvjs.isSupported()) {
          let videoElement = document.getElementById("myVideo");
          // console.log(videoElement)
          let flvPlayer = flvjs.createPlayer({
            type: "flv",
            url: viodeUrl,
            cors: true,
            hasAudio: true,
            hasVideo: true,
            isLive: false
          });
          flvPlayer.attachMediaElement(videoElement);
          flvPlayer.load();
        }
      });
    },
```
以下是报错信息：
![image](https://user-images.githubusercontent.com/39938981/78517043-55956f80-77ee-11ea-94f4-3348285a5013.png)

Access to fetch at 'http://10.255.21.67:8080/file/static/Newfile/2019/2/1553682255355%E8%B5%B0%E5%A5%BD%E4%BA%BA%E7%94%9F%E6%AF%8F%E4%B8%80%E6%AD%A5.flv'  from origin 'http：//10.255.details?id=15&parent...频资源&newsid=210433：1
30.77'  has  been  blocked  by  CORS  policy：No  'Access-Contro1-ALlow-Origin' 
 header  is  present  on  the  requested  resource.  If  an  opaque  response  serves  your  needs， set  the  request's  mode  to  'no-cors'  to  fetch  the  resource  with  CORS  disabled

[IOController] > Loader error, code = -1, msg = Failed to fetch

[TransmuxingController] > IOException: type = Exception, code = -1, msg = Failed to fetch

Uncaught (in promise) Error: Uncaught, unspecified "error" event. (NetworkError)

**Comment by 15956101692** [comment]
请问你这个问题解决了吗？   我现在也遇到同样的问题

**Comment by lzhgo** [comment]
> 请问你这个问题解决了吗？我现在也遇到同样的问题

老哥请问解决了吗

**Comment by mengpeilee** [comment]
不就同源問題嗎...Video Server要設定啊

**Comment by caiyushuang** [comment]
> 不就同源問題嗎...Video Server要設定啊

什么意思啊，大佬能指导下吗

**Comment by Dujiawei555** [comment]
> 说你这个问题解决了吗？我现在也遇到同样的问题

老哥 你的解决了没？

**Comment by 15956101692** [comment]
老姐&nbsp; 没有


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bilibili/flv.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月29日(星期六) 上午10:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560)





  
说你这个问题解决了吗？我现在也遇到同样的问题
  
老哥 你的解决了没？

**Comment by Dujiawei555** [comment]
我丢 心态崩了都&nbsp; 会不会是对面给的视频接口的问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月29日(星期六) 中午11:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560)





 老姐&amp;nbsp; 没有 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "bilibili/flv.js"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年5月29日(星期六) 上午10:56 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560) 
 
 
 
 
 
    
 说你这个问题解决了吗？我现在也遇到同样的问题 
    
 老哥 你的解决了没？

**Comment by 15956101692** [comment]
不排除




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bilibili/flv.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月29日(星期六) 中午11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560)





 我丢 心态崩了都&amp;nbsp; 会不会是对面给的视频接口的问题 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2021年5月29日(星期六) 中午11:15 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560) 
 
 
 
 
 
  老姐&amp;amp;nbsp; 没有  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "bilibili/flv.js"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年5月29日(星期六) 上午10:56  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560)  
   
   
   
   
   
      
  说你这个问题解决了吗？我现在也遇到同样的问题  
      
  老哥 你的解决了没？

**Comment by Dujiawei555** [comment]
我这这个他是有的时候就能加载出来播几秒&nbsp; 感觉又不太像是&nbsp; 服劲




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bilibili/flv.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月29日(星期六) 中午11:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560)





 不排除 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "bilibili/flv.js"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年5月29日(星期六) 中午11:17 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560) 
 
 
 
 
 
  我丢 心态崩了都&amp;amp;nbsp; 会不会是对面给的视频接口的问题  
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2021年5月29日(星期六) 中午11:15  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560)  
   
   
   
   
   
   老姐&amp;amp;amp;nbsp; 没有   
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "bilibili/flv.js"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年5月29日(星期六) 上午10:56   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560)   
     
     
     
     
     
        
   说你这个问题解决了吗？我现在也遇到同样的问题   
        
   老哥 你的解决了没？

**Comment by 15956101692** [comment]
具体报什么错呢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bilibili/flv.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月29日(星期六) 中午11:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560)





 我这这个他是有的时候就能加载出来播几秒&amp;nbsp; 感觉又不太像是&amp;nbsp; 服劲 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "bilibili/flv.js"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年5月29日(星期六) 中午11:19 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560) 
 
 
 
 
 
  不排除  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "bilibili/flv.js"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年5月29日(星期六) 中午11:17  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560)  
   
   
   
   
   
   我丢 心态崩了都&amp;amp;amp;nbsp; 会不会是对面给的视频接口的问题   
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: ***@***.***&amp;amp;amp;gt;;    
   发送时间: 2021年5月29日(星期六) 中午11:15   
   收件人: ***@***.***&amp;amp;amp;gt;;    
   抄送: ***@***.***&amp;amp;amp;gt;; ***@***.***&amp;amp;amp;gt;;    
   主题: Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560)   
     
     
     
     
     
    老姐&amp;amp;amp;amp;nbsp; 没有    
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "bilibili/flv.js"                                                                                    ***@***.***&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2021年5月29日(星期六) 上午10:56    
    ***@***.***&amp;amp;amp;amp;gt;;    
    ***@***.******@***.***&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560)    
       
       
       
       
       
          
    说你这个问题解决了吗？我现在也遇到同样的问题    
          
    老哥 你的解决了没？

**Comment by Dujiawei555** [comment]
就是那几个啊&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bilibili/flv.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月29日(星期六) 中午11:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560)





 具体报什么错呢 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "bilibili/flv.js"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年5月29日(星期六) 中午11:22 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560) 
 
 
 
 
 
  我这这个他是有的时候就能加载出来播几秒&amp;amp;nbsp; 感觉又不太像是&amp;amp;nbsp; 服劲  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "bilibili/flv.js"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年5月29日(星期六) 中午11:19  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560)  
   
   
   
   
   
   不排除   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "bilibili/flv.js"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年5月29日(星期六) 中午11:17   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560)   
     
     
     
     
     
    我丢 心态崩了都&amp;amp;amp;amp;nbsp; 会不会是对面给的视频接口的问题    
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人: ***@***.***&amp;amp;amp;amp;gt;;     
    发送时间: 2021年5月29日(星期六) 中午11:15    
    收件人: ***@***.***&amp;amp;amp;amp;gt;;     
    抄送: ***@***.***&amp;amp;amp;amp;gt;; ***@***.***&amp;amp;amp;amp;gt;;     
    主题: Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560)    
       
       
       
       
       
     老姐&amp;amp;amp;amp;amp;nbsp; 没有     
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------     
     发件人:                                                                                                                        "bilibili/flv.js"                                                                                    ***@***.***&amp;amp;amp;amp;amp;gt;;     
     发送时间:&amp;amp;amp;amp;amp;nbsp;2021年5月29日(星期六) 上午10:56     
     ***@***.***&amp;amp;amp;amp;amp;gt;;     
     ***@***.******@***.***&amp;amp;amp;amp;amp;gt;;     
     主题:&amp;amp;amp;amp;amp;nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560)     
         
         
         
         
         
            
     说你这个问题解决了吗？我现在也遇到同样的问题     
            
     老哥 你的解决了没？

**Comment by Dujiawei555** [comment]
> > 不就同源问题吗...视频服务器要设置啊
> 
> 什么英文啊，大佬能指导下吗

问下 大哥你解决了没？

**Comment by mengpeilee** [comment]
https://github.com/bilibili/flv.js/blob/master/docs/cors.md
文件上都有寫得很清楚，請問有看過 Document 嗎?

**Comment by Dujiawei555** [comment]
能问下在哪里改嘛&nbsp; 看不懂```




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bilibili/flv.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月29日(星期六) 中午12:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560)





 
https://github.com/bilibili/flv.js/blob/master/docs/cors.md
 文件上都有寫得很清楚，請問有看過 Document 嗎?

**Comment by zhtx8090** [comment]
> 我这这个他是有的时候就能加载出来播几秒&nbsp; 感觉又不太像是&nbsp; 服劲
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "bilibili/flv.js" ***@***.***&gt;; 发送时间:&nbsp;2021年5月29日(星期六) 中午11:19 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560) 不排除
> ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "bilibili/flv.js" ***@***.***&amp;gt;; 发送时间:&amp;nbsp;2021年5月29日(星期六) 中午11:17 ***@***.***&amp;gt;; ***@***.******@***.***&amp;gt;; 主题:&amp;nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560) 我丢 心态崩了都&amp;amp;nbsp; 会不会是对面给的视频接口的问题
> ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------ 发件人: ***@***.***&amp;amp;gt;; 发送时间: 2021年5月29日(星期六) 中午11:15 收件人: ***@***.***&amp;amp;gt;; 抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;; 主题: Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560) 老姐&amp;amp;amp;nbsp; 没有
> ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------ 发件人: "bilibili/flv.js" ***@***.***&amp;amp;amp;gt;; 发送时间:&amp;amp;amp;nbsp;2021年5月29日(星期六) 上午10:56 ***@***.***&amp;amp;amp;gt;; ***@***.******@***.***&amp;amp;amp;gt;; 主题:&amp;amp;amp;nbsp;Re: [bilibili/flv.js] 使用 flv.js 出现跨域怎么办，碰到以下报错信息，不知该如何解决？ (#560) 说你这个问题解决了吗？我现在也遇到同样的问题 老哥 你的解决了没？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你那边解决了吗，我这边也存在播放一段时间就报跨域的问题

**Comment by WatcherStar** [comment]
兄弟们找到问题所在了，使用node-media-server本地搭建的，播放后台也是显示跨域问题；后面弄了半天发现是直播码率问题，OBS默认高码率，设置为最低码率后转码成功；跨域问题是因为fetch的问题必须指定具体域名
