### ISSUE TITLE
突然视频播放报错，昨天上午还好好的，怎么回事

### ISSUE THREAD

**Issue by HolyDogs** [bilibili/flv.js#573]
报错信息如下

flv.js:11590 [IOController] > Loader error, code = undefined, msg = Cannot read property 'flushStashedSamples' of null
flv.js:11590 [TransmuxingController] > IOException: type = Exception, code = undefined, msg = Cannot read property 'flushStashedSamples' of null
flv.js:1251 Uncaught (in promise) Error: Uncaught, unspecified "error" event. (NetworkError)
    at EventEmitter.emit (flv.js:1251)
    at EventEmitter.<anonymous> (flv.js:9140)
    at EventEmitter.emit (flv.js:1273)
    at flv.js:3207

**Comment by yh4922** [comment]
大佬 我也遇到这个问题  你解决了么

**Comment by bubblehead121** [comment]
大佬，怎么解决的啊，可以贴出来分享下吗谢谢

**Comment by HolyDogs** [comment]
> 怎么解决的啊，可以贴出来分享下吗谢谢

我也记不清了，太久没用了。。主要还是看视频流的类型吧，当时我好像是后台读流器的属性设置有问题。比如你本地生成的视频流就不能设置TCP协议传输等等，好像我当时报错和flvjs没有多大关系
