### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by lostfordream** [Bilibili/flv.js#58]
对于直播，时间越长，内存耗费越多，怀疑是送入解码器的视频流没有释放

**Comment by xqq** [comment]
最大吃到多少？

**Comment by zgy520** [comment]
@lostfordream 那是播放的视频流吗？

**Comment by lostfordream** [comment]
单路我看到最大的1g多，会一直增大，直到浏览器崩溃提示内存不足，我分析了下应该是mse addbuffer后一直不释放，对于直播只需要保留几秒的视频，所以需要remove不需要的视频

**Comment by lostfordream** [comment]
@zgy520  是视频流，http flv 流

**Comment by xqq** [comment]
浏览器和系统是啥

**Comment by lostfordream** [comment]
系统win10 ，浏览器是chrome

**Comment by xqq** [comment]
指定 isLive: true 没

**Comment by lostfordream** [comment]
chrome 55.0.2883.75 m
OS VERSION Windows NT: 10.0.14393
Tab [127.0.0.1/flvm_h5.html] 323 MB private, 24 MB shared
Browser 37 MB private, 33 MB shared
GPU [] 28 MB private, 21 MB shared
图像720p
islive=true
以上是系统状态，我现在大概测试了2个小时，最开始内存占用约40m，前半个小时内存增长较快，达到200多m，后面内存还在缓慢增加目前323m。

**Comment by xqq** [comment]
300M~400M是可接受的。我没有对MSE的SourceBuffer执行remove，因为MSE本身就自带gc机制，缓冲区满后浏览器会自动清除靠前的数据。Chrome大约150M，FireFox 100M

**Comment by lostfordream** [comment]
长时间live后，提示异常，可能数据有问题 
Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.
value @ flv.min.js:5
value @ flv.min.js:1
value @ flv.min.js:1
(anonymous) @ flv.min.js:4
i.emit @ flv.min.js:1
(anonymous) @ flv.min.js:2
flv.min.js:1 Uncaught (in promise) Error: Uncaught, unspecified "error" event. (MediaError)
    at i.emit (flv.min.js:1)
    at i.<anonymous> (flv.min.js:4)
    at i.emit (flv.min.js:1)
    at e.value (flv.min.js:1)
    at e.value (flv.min.js:1)
    at i.<anonymous> (flv.min.js:4)
    at i.emit (flv.min.js:1)
    at flv.min.js:2
i.emit @ flv.min.js:1
(anonymous) @ flv.min.js:4
i.emit @ flv.min.js:1
value @ flv.min.js:1
value @ flv.min.js:1
(anonymous) @ flv.min.js:4
i.emit @ flv.min.js:1
(anonymous) @ flv.min.js:2
flv.min.js:1 Uncaught (in promise) Error: Uncaught, unspecified "error" event. (MediaError)
    at i.emit (flv.min.js:1)
    at i.<anonymous> (flv.min.js:4)
    at i.emit (flv.min.js:1)
    at e.value (flv.min.js:1)
    at e.value (flv.min.js:1)
    at i.<anonymous> (flv.min.js:4)
    at i.emit (flv.min.js:1)
    at flv.min.js:2
但是内存就狂涨了
Tab [127.0.0.1/flvm_h5.html] 1201 MB private, 25 MB shared

**Comment by jcpwfloi** [comment]
@lostfordream You can check issue #107

**Comment by hj009** [comment]
你好 ，我也是遇到同样的问题，请问你解决了吗？？求顺带

**Comment by sky0014** [comment]
同，几个使用flv.js的直播站如b站、熊猫，经过观察也都有此现象。
