### ISSUE TITLE
Flv.js in safari causes the browser to die.

### ISSUE THREAD

**Issue by number201724** [Bilibili/flv.js#6]
Flv.js in safari causes the browser to die.
At the beginning of the buffer flow will cause playback to pause and the browser page to stop working.

**Comment by xqq** [comment]
#need-more-info

Notice that Safari 9.x is not supported

**Comment by number201724** [comment]
safari 10 in NMB

**Comment by number201724** [comment]
反正就是卡网络IO了 你懂的 之前说过

**Comment by vizee** [comment]
我就是来看你们说英语(逃

**Comment by aolko** [comment]
真，真

**Comment by 872517414** [comment]
来看英语+1（跟着逃）

**Comment by GongT** [comment]
+1

**Comment by AngryPowman** [comment]
我就是来看你们说英语（逃

**Comment by number201724** [comment]
你们洗干净了等着♂

**Comment by Aqours** [comment]
funny

**Comment by AdoBeatTheWorld** [comment]
jixu yong pinyin ba, xiaoxiao qiangpozheng.

**Comment by zapline** [comment]
我就是来看你们说英语（逃

**Comment by liaosiyang** [comment]
我就是来看你们说英语（逃

**Comment by Andself** [comment]
神他妈 NMB（new macbook）

**Comment by Tuzkiss** [comment]
我就是来看你们说英语（From MacBook Pro 2016 15" with Multi-Touch Bar

**Comment by aolko** [comment]
请停止下车主题

**Comment by starInEcust** [comment]
对不起 我也是来看的 in nmb
