### ISSUE TITLE
菜鸟请问怎样使用此工程？

### ISSUE THREAD

**Issue by 9crk** [Bilibili/flv.js#60]
我做了如下事情：
1.将flv.js目录放到/www目录下
2.用chrome或手机QQ浏览器打开http://x.x.x.x/flv.js/demo/index.html
3.在地址栏输入rtmp或hls测试地址
4.点击Load Start等，均不可播放
5.求解。。。。

**Comment by 9crk** [comment]
在线等。。。

**Comment by 9crk** [comment]
找了个小板凳坐着等。。

**Comment by 9crk** [comment]
_(:зつㄥ)_

**Comment by uaio** [comment]
是否安装了依赖，用gulp是否处理了源码，是否有什么报错

**Comment by 9crk** [comment]
我只是在一台干净的Ubuntu上安装了apache，gulp是啥？为何需要使用这个东西？整个过程没有提示任何东西呀。需要依赖什么呢？

**Comment by 9crk** [comment]
貌似这个flv.js并非javascript呀。。是要使用Node.js么？菜鸟表示不会玩Node.js。。。

**Comment by uaio** [comment]
你按照它的readme来操作

**Comment by uaio** [comment]
还得安装nodejs，gulp需要node环境来运行，你看gulpfile.js里面有它的工作流，编译，打包什么的，完成之后它会把你能用的东西放到创建的dist文件里的

**Comment by 9crk** [comment]
sudo apt-get install nodejs npm

zhouhua@xbox:~/work/flv.js/flv.js/src$ npm install --save flv.js 
npm ERR! Not a package /tmp/npm-1482289856718/1482289856718-0.41465674387291074/tmp.tgz
npm ERR! couldn't unpack /tmp/npm-1482289856718/1482289856718-0.41465674387291074/tmp.tgz to /tmp/npm-1482289856718/1482289856718-0.41465674387291074
npm http GET http://registry.npm.taobao.org/flv.js

npm ERR! Error: Invalid protocol
npm ERR!     at Request.init (/usr/lib/nodejs/request/main.js:274:31)
npm ERR!     at new Request (/usr/lib/nodejs/request/main.js:102:8)
npm ERR!     at request (/usr/lib/nodejs/request/main.js:800:11)
npm ERR!     at makeRequest (/usr/share/npm/lib/utils/npm-registry-client/request.js:121:13)
npm ERR!     at regRequest (/usr/share/npm/lib/utils/npm-registry-client/request.js:81:3)
npm ERR!     at GET (/usr/share/npm/lib/utils/npm-registry-client/request.js:214:3)
npm ERR!     at get_ (/usr/share/npm/lib/utils/npm-registry-client/get.js:121:3)
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:44:7
npm ERR!     at [object Object].<anonymous> (fs.js:115:5)
npm ERR!     at [object Object].emit (events.js:64:17)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/zhouhua/work/flv.js/flv.js/src/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.2.0-29-generic-pae
npm ERR! command "node" "/usr/bin/npm" "install" "--save" "flv.js"
npm ERR! cwd /home/zhouhua/work/flv.js/flv.js/src
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message Invalid protocol
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/zhouhua/work/flv.js/flv.js/src/npm-debug.log
npm not ok

**Comment by uaio** [comment]
安装不上nodejs？包名对么，我对Ubuntu这个不了解，或者你去nodejs官网直接下载它的包来安装呢，看看它怎么安装的

**Comment by lianjt** [comment]
个人的一点浅显的理解，首先npm是模块管理器，可以为你的每一个工程或全局或单独安装一些模块，所以你不应该在flv.js/src里面运行。你可以尝试下在别的地方新建一个文件夹，然后运行npm init，初始化一下，然后再运行作者给你的语句

**Comment by lianjt** [comment]
还有一个卡了我两天的小问题就是被测试的flv的格式是有要求的，必须是264 AAC格式。记得转换格式。ffmpeg -i yours.flv -vcodec libx264 -c:a aac   converted.flv

**Comment by dnshi** [comment]
@lianjt 巧遇学弟

**Comment by lianjt** [comment]
@dnshi 哎呦 遭遇野生师哥一枚 option A 扔石子 option B 扔精灵球 option C 对师哥嘿嘿嘿 option D 放师哥走 Answer: AAAAAAAA.....致昏迷...........CCCCCCCCCCCD
