### ISSUE TITLE
flv.js websocket 报错!Non-FLV, Unsupported media type!  

### ISSUE THREAD

**Issue by MasterChenJiaWang** [bilibili/flv.js#603]
Non-FLV, Unsupported media type!
Uncaught (in promise) Error: Uncaught, unspecified "error" event. (MediaError)
Uncaught TypeError: Cannot read property 'currentURL' of null
![image](https://user-images.githubusercontent.com/20539058/91246818-66d21f00-e783-11ea-93b4-79128e38d965.png)
![image](https://user-images.githubusercontent.com/20539058/91246834-75203b00-e783-11ea-8904-5f3bad331209.png)

**Comment by taozywu** [comment]
@MasterChenJiaWang 
Are you sure your url is right? 
```
ws://127.0.0.1/xxxx
```
this url means localhost ip

**Comment by MasterChenJiaWang** [comment]
thinks  Problem has been solved

**Comment by elva2596** [comment]
> thinks Problem has been solved

how to solve?

**Comment by daicongwei** [comment]
How to solve this problem? I've met it now. I haven't found a solution. Please give me some advice
