### ISSUE TITLE
flv.js只播放实时音频，但是延迟太高

### ISSUE THREAD

**Issue by keDaYao** [bilibili/flv.js#607]
背景：后端将PCM转为mp3最后封装到了flv里，采用webSocket传输实时音频
问题：通过flv.js 指定了ws的url，设置了 hasVideo: false，点击开始播放后，要等10多秒才能播出声音。
请问这种情况如何解决？可以让flv.js收到音频就直接播放吗？

**Comment by xqq** [comment]
config里面 enableStashBuffer: false 关掉缓冲试试

Tai <notifications@github.com> 于2020年9月4日周五 下午4:33写道：

**Comment by xqq** [comment]
或者把 stashInitialSize 初始缓冲大小调小，默认有 384KB，不缓冲满不会开播
