### ISSUE TITLE
rstp直播. 第一次加载后, 10秒左右后会缓冲一次, 然后画面frozen,  buffered.end(0)数值就异常了

### ISSUE THREAD

**Issue by caperso** [bilibili/flv.js#624]
![image](https://user-images.githubusercontent.com/34877623/99652305-9ea2e700-2a92-11eb-94d7-dea40a73a58d.png)

**Comment by caperso** [comment]
这是推流的问题吗

**Comment by caperso** [comment]
后端用fluent-ffmpeg转码express-ws服务

**Comment by myseemylife** [comment]
检查时间戳。

**Comment by caperso** [comment]
update

无法校验无信号推流时间戳
但恢复直播流时候时间戳正常. 
关闭了
