### ISSUE TITLE
移动端报错问题，调试window.MediaSource undefined

### ISSUE THREAD

**Issue by chaytang** [Bilibili/flv.js#64]
作者大大，发现了这么个神奇的东西，初步弄了pc端没有问题，但是在移动端、微信、ios、安卓调试后发现是 window.MediaSource为undefined引起的，不知道作者大大有没有研究过。

**Comment by xqq** [comment]
那就是不支持。执行前务必通过 flvjs.getFeatureList() 检测环境支持度

**Comment by cytGitHub** [comment]
@xqq  在微信里面，`mseFlvPlayback` , `mseLiveFlvPlayback`  这两项的检测都为undefined  也就说微信不支持？

**Comment by cytGitHub** [comment]
@xqq  这在pc的chrome浏览器下边 性能真牛逼，几乎是秒开视频

**Comment by cytGitHub** [comment]
@xqq  只有 flvjs.getFeatureList() 这个对象中的每个属性值都为true 才能播放这个视频吧？ 我测试个别手机 有一项为false 都不能播放视频。

**Comment by xqq** [comment]
@cytGitHub mseFlvPlayback为true即可播放点播视频，mseLiveFlvPlayback为true才可播放httpflv直播流
