### ISSUE TITLE
本地运行demo报错，无法播放flv文件

### ISSUE THREAD

**Issue by zhuyimiao** [Bilibili/flv.js#65]
var mediaDataSource = {"type":"flv","url":"vedio2.flv"};

同目录下放了个vedio2.flv 的文件，运行demo里的index.html,
浏览器报错：
index.html:1 Not allowed to load local resource: blob:null/f50df6a4-3cd2-4297-8903-95a6ceef65f7

作者大大，这是什么原因？需要怎么改？同样的方法，播放mp4文件就可以

使用README.md里给的代码：
if (flvjs.isSupported()) {
        var videoElement = document.getElementById('videoElement');
        var flvPlayer = flvjs.createPlayer({
            type: 'flv',
            url: 'http://example.com/flv/video.flv'
        });
        flvPlayer.attachMediaElement(videoElement);
        flvPlayer.load();
        flvPlayer.play();
    }

也是报同样的错误

**Comment by zhuyimiao** [comment]
我是直接在浏览器里打开了index.html文件

**Comment by Riricho** [comment]
刚刚开了apache试了试，chrome和edge都可以顺利播放了。
你可以尝试在web service里用127.0.0.1运行下页面试试╰(*°▽°*)╯

**Comment by cyfour** [comment]
用Apache 也是报错[MSEController] > MediaSource onSourceOpen
2flv.min.js:3 GET http://example.com/flv/video.flv value @ flv.min.js:3value @ flv.min.js:3value @ flv.min.js:2value @ flv.min.js:2value @ flv.min.js:1value @ flv.min.js:4(anonymous function) @ flv.min.js:4i.emit @ flv.min.js:1value @ flv.min.js:1
(index):1 Fetch API cannot load http://example.com/flv/video.flv. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access. The response had HTTP status code 500. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
flv.min.js:5 [IOController] > Loader error, code = -1, msg = Failed to fetchvalue @ flv.min.js:5value @ flv.min.js:3(anonymous function) @ flv.min.js:3
flv.min.js:5 [TransmuxingController] > IOException: type = Exception, code = -1, msg = Failed to fetchvalue @ flv.min.js:5value @ flv.min.js:2value @ flv.min.js:3(anonymous function) @ flv.min.js:3
flv.min.js:1 Uncaught (in promise) Error: Uncaught, unspecified "error" event. (NetworkError)(…)

**Comment by Riricho** [comment]
@cyfour
你需要把url: 'http://example.com/flv/video.flv'这里的地址换成一个有效的flv地址
我是直接去bilibili下了一段flv放在本地里加载的
所以我这里的代码是url: 'flv/video.flv'
我的目录结构是：
--js
--css
--flv
----index.html

完整的代码是：
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="google" value="notranslate">
    <meta name="robots" content="index,follow">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no,shrink-to-fit=no,minimal-ui">
    <meta name="format-detection" content="telephone=no,email=no,address=no,date=no">
    <meta name="msapplication-tap-highlight" content="no">
    <title>flvJs demo</title>
    <link rel="stylesheet" type="text/css" href="css/Mo.css">
    <link rel="stylesheet" type="text/css" href="css/styleMo.css">
</head>
<body>
	<div class="mo-wrap">
        <div class="mo-box">
            <div class="mo-video">
                <video id="videoElement"></video>
            </div>
        </div>
	</div>
<script type="text/javascript" src="js/flv.js"></script>    
<script>
    if (flvjs.isSupported()) {
        var videoElement = document.getElementById('videoElement');
        var flvPlayer = flvjs.createPlayer({
            type: 'flv',
            url: 'flv/video.flv'
        });
        flvPlayer.attachMediaElement(videoElement);
        flvPlayer.load();
        flvPlayer.play();
    }
</script>
</body>
</html>
你可以参考下
移动端的meta可以直接无视╰(*°▽°*)╯

**Comment by cyfour** [comment]
改了本地的 Uncaught (in promise) Error: Uncaught, unspecified "error" event. (MediaError)(…)
flv.min.js:1 Uncaught (in promise) Error: Uncaught, unspecified "error" event. (MediaError)(…) 一直报这个错。。。

**Comment by cyfour** [comment]
换了另外的FLV 又出现不同的报错 [FLVDemuxer] > Parsed onMetaData
2flv.min.js:5 [TransmuxingController] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported audio codec idx: 2value @ flv.min.js:5value @ flv.min.js:2value @ flv.min.js:2value @ flv.min.js:2value @ flv.min.js:2value @ flv.min.js:3value @ flv.min.js:3(anonymous function) @ flv.min.js:3
flv.min.js:5 [TransmuxingController] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 4value @ flv.min.js:5value @ flv.min.js:2value @ flv.min.js:2value @ flv.min.js:2value @ flv.min.js:2value @ flv.min.js:3value @ flv.min.js:3(anonymous function) @ flv.min.js:3
flv.min.js:5 [TransmuxingController] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported audio codec idx: 2value @ flv.min.js:5value @ flv.min.js:2value @ flv.min.js:2value @ flv.min.js:2value @ flv.min.js:2value @ flv.min.js:3value @ flv.min.js:3(anonymous function) @ flv.min.js:3
flv.min.js:5 [TransmuxingController] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 4value @ flv.min.js:5value @ flv.min.js:2value @ flv.min.js:2value @ flv.min.js:2value @ flv.min.js:2value @ flv.min.js:3value @ flv.min.js:3(anonymous function) @ flv.min.js:3
7flv.min.js:5 [TransmuxingController] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported audio codec idx: 2value @ flv.min.js:5value @ flv.min.js:2value @ flv.min.js:2value @ flv.min.js:2value @ flv.min.js:2value @ flv.min.js:3value @ flv.min.js:3(anonymous function) @ flv.min.js:3
flv.min.js:5 [TransmuxingController] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 4

**Comment by kore-tao** [comment]
哪里有flv.min.js?

**Comment by shunzizhan** [comment]
我现在也是各种报错，本地跑，也是提示错误
![image](https://cloud.githubusercontent.com/assets/7811369/21478726/18fa19b4-cb89-11e6-9ea4-dcdffa3f9430.png)
使用线上的flv文件，则提示跨域，让运维配nginx转跳，还是报错
![image](https://cloud.githubusercontent.com/assets/7811369/21478742/383d78de-cb89-11e6-8068-1f1b64aa1489.png)

哪位用完好的demo，能不能发我一份？

**Comment by xqq** [comment]
仅支持H264+AAC

**Comment by shunzizhan** [comment]
1.我不是很明白你的意思 @xqq  仅支持H264+AAC
2.我目前需要在移动端播放视频，需要同时兼容Android和ios版本，flv.js能不能够支持？

**Comment by xqq** [comment]
1. 从错误logcat看，输入文件是不受支持的H263+MP3编码。
2. Android 支持，ios 不支持

**Comment by cyfour** [comment]
求一个 H264+AAC 的FLV 我这边只能用格式工厂转化成H264+AAC 的MP4。

**Comment by Riricho** [comment]
@cyfour 
你可以直接去B站上抓一段flv下来测试 B站的视频都是一段一段的flv拼起来的

**Comment by cyfour** [comment]
Uncaught (in promise) Error: Uncaught, unspecified "error" event. (MediaError)(…)
flv.min.js:1 Uncaught (in promise) Error: Uncaught, unspecified "error" event. (MediaError)(…)   谷歌提示这个 360浏览器可以播放

**Comment by cyfour** [comment]
flv.min.js:5 [TransmuxingController] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported codec in video frame: 2谷歌提示这个 360浏览器可以播放

**Comment by Riricho** [comment]
@shunzizhan 
我邮件发了一份我的demo给你了，PC和IOS上测试是没问题的，安卓因为没有安卓机暂时还没测试过_(:з)∠)_

**Comment by cyfour** [comment]
@Riricho 也发一份给我哈~谢谢。

**Comment by Riricho** [comment]
@cyfour 我没找到你邮箱_(:з)∠)_
完整的Demo我直接丢在我服务器上了，需要的可以去自取。
http://www.riricho.com/flvJs.zip
放在web service环境下等页面加载完 点击下面的load才会加载视频资源
Start和Pause是播放和暂停，seekTo有bug不要点_(:з)∠)_

**Comment by TianYongwei** [comment]
sigh

**Comment by tenglongwentian** [comment]
@Riricho 请问ios您是选择的测试版本是什么，我这里用ipad air测试失败，无法播放

**Comment by xqq** [comment]
不支持ios

**Comment by Riricho** [comment]
@tenglongwentian 5s/ios10/safari.

**Comment by tenglongwentian** [comment]
2017年3月8日测试，chrome内核浏览器，奇数版本号不支持，偶数版本号支持，Android端；网上搜索称：奇数版本号是beta版，偶数版本号是stable版 @Riricho ，目前正在寻求IOS能够播放之道

**Comment by VIRGIL-YAN** [comment]
@Riricho 能不能也发我一份

**Comment by opewwe** [comment]
> @shunzizhan 我邮件发了一份我的demo给你了，PC和IOS上测试是没问题的，安卓因为没有安卓机暂时还没测试过_(:з)∠)大佬能发给我一份吗 最近在做flv的项目 本地一直报错

**Comment by wangxiaohuiboy** [comment]
> 我现在也是报各种错误，本地跑，也是提示错误 使用线上的flv文件，则提示跨域，让运维配nginx转跳，还是报错 ![图片](https://cloud.githubusercontent.com/assets/7811369/21478726/18fa19b4-cb89-11e6-9ea4-dcdffa3f9430.png) ![图片](https://cloud.githubusercontent.com/assets/7811369/21478742/383d78de-cb89-11e6-8068-1f1b64aa1489.png)
> 
> 哪位用发我的demo，能不能？

请问大佬，你这个问题解决了吗

**Comment by wei13030206499** [comment]
大佬，我也遇到这个问题，有办法解决吗
