### ISSUE TITLE
播放一个flv视频文件问题

### ISSUE THREAD

**Issue by songguangyu** [Bilibili/flv.js#66]
初次加载视频 没有range呢？

**Comment by songguangyu** [comment]
请求第二片之后 会导致整个视频时间错乱

**Comment by xqq** [comment]
初次加载视频要 Range 干啥？
你可能需要 rangeLoadZeroStart 参数

**Comment by songguangyu** [comment]
我在请求一个 2个G 的文件 之后播放几分钟后就会错乱。meta 信息都不对了
