### ISSUE TITLE
无法关闭http-flv连接

### ISSUE THREAD

**Issue by Sshhcc** [bilibili/flv.js#663]
![image](https://user-images.githubusercontent.com/17444344/118936356-0e7d2600-b97f-11eb-84b6-4f8db1834cd6.png)
我使用flv.js播放设备的监控画面，当http-flv的连接没有数据推送过来时，我使用以下代码关闭当前播放，http的连接也不会被关闭
![image](https://user-images.githubusercontent.com/17444344/118936906-8ea38b80-b97f-11eb-9664-9d1c210d82aa.png)

**Comment by xqq** [comment]
https://github.com/xqq/mpegts.js/commit/d92c189248da8eb6e4bcc5db6d953a3f4fe34eb9

试试

**Comment by Sshhcc** [comment]
测试了下，完全没问题，谢谢大佬
