### ISSUE TITLE
怎么没有aspectRatio参数设置

### ISSUE THREAD

**Issue by sunlili810** [bilibili/flv.js#669]
flv想设置视频长宽比例，怎么没有aspectRatio参数设置为4:3或者16:9的

**Comment by SnuggleE** [comment]
解决了吗

**Comment by sunlili810** [comment]
> 解决了吗

可以设置其父元素的宽高，让video填充满父元素。只要给video标签加上style="width= 100%; height=100%; object-fit: fill"即可。
