### ISSUE TITLE
启用enableWorker异常(v1.6.0)

### ISSUE THREAD

**Issue by MeloQi** [bilibili/flv.js#675]
在transmuxing-worker.js中加载其他js报错，报错如下：
![无标题](https://user-images.githubusercontent.com/6103069/126760218-24033fcf-3eba-40f0-85d7-fad65da2c942.png)

**Comment by MeloQi** [comment]
已解决，单独打包webworker

**Comment by xlsky0713** [comment]
你好，怎么单独打包？

**Comment by zzzzzzdk** [comment]
> 已解决，单独打包webworker

你好，怎么单独打包....
