### ISSUE TITLE
flvjs播放器播放http-flv流直播视频，会一直显示警告[FLVDemuxer] > Malformed Nalu near timestamp...

### ISSUE THREAD

**Issue by turtleOrange** [bilibili/flv.js#689]
以下是警告的内容
...
[FLVDemuxer] > Malformed Nalu near timestamp 158240, offset = 45, dataSize = 49
...
请问有办法消除掉这类的警告么？
![image](https://user-images.githubusercontent.com/38777427/129173040-9feb7b89-b578-445c-9d07-98b13b678123.png)

**Comment by zhang421755327** [comment]
fixAudioTimestampGap: false就好了

**Comment by turtleOrange** [comment]
> fixAudioTimestampGap
加上了，控制台还是一直报警告

![image](https://user-images.githubusercontent.com/38777427/129851846-3a244b13-273a-44c0-9320-c51ebb235c81.png)

**Comment by turtleOrange** [comment]
fixAudioTimestampGap设置了true或false都一样，控制台一直报错

**Comment by turtleOrange** [comment]
fixAudioTimestampGap设置了true或false都一样，控制台一直报错

**Comment by zhang421755327** [comment]
用这个试试flv.LoggingControl.enableWarn = false，把fixAudioTimestampGap: false去掉

**Comment by turtleOrange** [comment]
全局使用this.$flvjs.LoggingControl.enableWarn = false可行
