### ISSUE TITLE
大部分移动端无法播放

### ISSUE THREAD

**Issue by songguangyu** [Bilibili/flv.js#69]
请问 http://www.bilibili.com/html/html5player.html
和flv.js 是什么关系呀 我测试过 iphone6 都无法播放 因为没有Mediasource 这个怎么解决呢 还是得用m3u8播放吗？

**Comment by xqq** [comment]
没有 MediaSource，去问苹果啊

**Comment by songguangyu** [comment]
很多安卓版本比如安卓4.4版本 都无法播放，因为没有Mediasource  感觉flv.js 是一个面向未来的框架，因为现在都不支持。。。

**Comment by xqq** [comment]
Android 4.4.4+ 就支持了。并且 PC 端主流浏览器全支持了。
所以不是 flv.js 面向未来，而是你国终端系统太落后了。。。

**Comment by ghostgzt** [comment]
然而未来是MP4的世界，这工具是一个过度产物，但是炒作一番，可以让作者身价大涨~

**Comment by xqq** [comment]
@ghostgzt 

就点播而言，flv.js 某种程度上可以算是过度产物，但除了解决历史遗留，相比 mp4 也有其它优势，比如原生 html5 不支持的多段视频无缝播放等。
但对于直播领域，应该是目前较好的 solution 吧？

开源的目的是发挥价值并使项目延续下去。如果你认为是炒作的话，请便

**Comment by DricHao** [comment]
> 然而未来是MP4的世界，这工具是一个过度产物，但是炒作一番，可以让作者身价大涨~

饭圈真恶心
