### ISSUE TITLE
Low latency ?

### ISSUE THREAD

**Issue by nums** [Bilibili/flv.js#7]
Hello,

Thanks for your work, I tested a HTTP FLV livestream and it's working great !
Now I'm focusing on live low latency, Do you have more informations about HTTP FLV low latency or WebSocket FLV livestreaming ?
I didn't find anything about that except this repo : https://github.com/winlinvip/videojs-flow

Thanks

**Comment by xqq** [comment]
Unlike segments-based protocol (HLS, DASH, ...), HTTP FLV provides a continuous realtime stream, which has similiar characteristics like RTMP. It can be considered as a simplified and simplex RTMP which is enough for playback. 

For HTTP FLV, please refer to https://github.com/ossrs/srs/wiki/v2_EN_DeliveryHttpStream#why-http-flv

For WebSocket FLV livestreaming, server side support is needed however there're no server supported yet. This is also a reliable way for low latency livestream transmitting.

**Comment by nums** [comment]
Ok, thanks for your quick reply.
I made my test with ossrs and my HTTP FLV livestreaming delays was about 10 seconds.
I will investigate setup of ossrs and I let you know
