### ISSUE TITLE
出现Not allowed to load local resource这样的错误

### ISSUE THREAD

**Issue by tifentan** [Bilibili/flv.js#70]
首先感谢你无私的分享。
我在调试 getting started给出的例子时在chrome出现
Not allowed to load local resource 这样的错误。
请问原因是什么，谢谢啦。
Ps：在火狐上没问题。

**Comment by lianjt** [comment]
chrome 基于安全问题不允许读取本地文件。 http://stackoverflow.com/questions/34901523/file-url-not-allowed-to-load-local-resource-in-the-internet-browser 这个说不定可以帮助你
