### ISSUE TITLE
直播播放过程中，画面中断，播放结束，提示77394 bytes unconsumed data remain when flush buffer, dropped

### ISSUE THREAD

**Issue by blak0001111** [Bilibili/flv.js#704]
![ECT)RE 8){7D~~~U`)AQ7UQ](https://user-images.githubusercontent.com/28420734/138420019-c6f4c323-8f23-499e-94fd-54bbcba23e06.png)

**Comment by blak0001111** [comment]
这个是啥原因，是推流中断了吗

**Comment by Damon-start** [comment]
请问这是什么问题？
