### ISSUE TITLE
本人菜鸟一个，在Ubuntu上怎么使用该工程

### ISSUE THREAD

**Issue by foreverflame** [Bilibili/flv.js#72]

**Comment by foreverflame** [comment]
我在unbuntu上按照readme上的操作，npm install --save flv.js这个命令是在哪个目录下操作呢

**Comment by xqq** [comment]
npm install 仅在你自己项目里引用 flv.js 时使用。
如果要测试 demo，按照 build 流程编译或者从 github release 下载预编译好的 js。

**Comment by 9crk** [comment]
同问。。无node.js经验。。

**Comment by XiaoyingZhao** [comment]
我在github上下载安装之后也不能用，起中一个json文件缺失，总是报错，求问这个json文件是什么


原始邮件
发件人:周华notifications@github.com
收件人:Bilibili/flv.jsflv.js@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2016年12月26日(周一) 10:58
主题:Re: [Bilibili/flv.js] 本人菜鸟一个，在Ubuntu上怎么使用该工程 (#72)


同问。。无node.js经验。。
