### ISSUE TITLE
作者大大，请问一下，我在谷歌浏览器上的话，是秒开视频，但是到了Safari，手机上就都不行了，请问是为啥？

### ISSUE THREAD

**Issue by CCYQ1995** [Bilibili/flv.js#73]
如题，我是个菜鸟，这两天一直遇到这种问题，所以想请教一下到底是啥情况，我在Safari上使用你提供的console.log(flvjs.getFeatureList());发现输出了这一堆，表示我看不懂，你能跟我说一下我该怎么弄么？

`mseFlvPlayback: true

mseLiveFlvPlayback: false

nativeMP4H264Playback: true

nativeWebmVP8Playback: false

nativeWebmVP9Playback: false

networkLoaderName: "xhr-range-loader"

networkStreamIO: false`

**Comment by xqq** [comment]
1. Mac Safari 要求版本 > 10，并且 Mac Safari 暂不支持 http-flv 直播流
2. iOS Safari 不支持 Media Source Extensions 因此无法使用 flv.js

**Comment by CCYQ1995** [comment]
哦，原来是这样啊，好的 ，谢谢你

**Comment by cytGitHub** [comment]
安卓移动端可以使用flv么？

**Comment by cytGitHub** [comment]
@xqq  我用微信浏览器测试了 发现微信浏览器不能播放  我用的是三星s6曲面手机  请问 有什么改进方法么？

**Comment by xqq** [comment]
@cytGitHub 
腾讯 X5 内核砍掉了 MediaSource 支持。你需要可以给 http://x5.tencent.com/tbs/ 提 feature request
