### ISSUE TITLE
flvjs怎么判断这个文件的流存不存在

### ISSUE THREAD

**Issue by littehao** [Bilibili/flv.js#74]
我找了很久没都找到

**Comment by xqq** [comment]
存不存在是啥？404？

**Comment by littehao** [comment]
不是，我就是想让这个流如果不存在，返回一个状态

**Comment by xqq** [comment]
监听 ERROR 事件，errorDetails 为 NETWORK_STATUS_CODE_INVALID，info 中的 code 即为 http 状态码。

当请求为跨域请求时，仅当通过跨域验证时才能拿到 http 状态码，否则即为 NETWORK_EXCEPTION。

**Comment by xqq** [comment]
最后，判断流是否存在应该在业务层做，不是 flv.js 的职责。播放器出现 404 已经属于播放错误了。

**Comment by lyt8384** [comment]
其实为啥clone掉这个了。这个确实有时候会遇到这样的需求。例如某直播云。在正常推流的时候是正常的。停止推流的时候是403，然后会有一个json。虽然可以在业务层去在每次请求的时候判断是否正在推流。但是那样的延时会很大(对方30秒才close连接返回403的)，而这块做成异步去，后端开销又很大。所以会有想发把这个成本转给用户去。类似：

- 先统一用flv.js载入直播流
- 如果加载异常触发事件
- 业务上去改变UI或者其他操作等

**Comment by xqq** [comment]
目前这样做没什么问题，如果出 403/404，flv.js 会抛出 HttpStatusCodeInvalid 错误并提供状态码

**Comment by hu-lielie** [comment]
出现这样的情况，直播过程中由于某种原因突然 停止推流，然后就卡住了。
怎么能够尝试重连，然后获得状态码？
