### ISSUE TITLE
有没有http-flv转websocket flv的方案

### ISSUE THREAD

**Issue by hongweiqu** [Bilibili/flv.js#75]
有没有http-flv转websocket flv的方案

**Comment by xqq** [comment]
自己写server

**Comment by hongweiqu** [comment]
没找到server的实现方式，有nodejs的实现方式吗

**Comment by xqq** [comment]
没写过，不过 nodejs 天然自带 websocket 支持、或使用 socket.io 等应该很容易实现

**Comment by hj009** [comment]
兄弟搞定没   指点下     用ws  后台该给前端传什么格式的数据 是否需要特殊字节   怎么传        前端就输一个url：ws//....   感觉对接的莫名其妙

**Comment by xqq** [comment]
websocket里直接传flv文件字节流

**Comment by hj009** [comment]
作者大大   有一个ws 的测试demo吗

**Comment by xqq** [comment]
没有

**Comment by hj009** [comment]
那么  http 和 ws   是否是同样的方式给前端传流呢
