### ISSUE TITLE
flv.js是否支持https 2.0

### ISSUE THREAD

**Issue by XiaotaoTTTtian** [Bilibili/flv.js#755]
由于浏览器同源并发策略，想要升级http到2.0。

**Comment by Echo365** [comment]
可以的。

**Comment by geminit2011** [comment]
你好，问一下加上https之后，实时摄像机码流加载需要1分多钟。不加https是正常的，这种现象有没有解决思路。
采用nginx配置的，看配置也没啥特别的地方，类似这种：
server {
        listen 443 ssl;  # 1.1版本后这样写
        server_name www.xxx.cn; #填写绑定证书的域名
        ssl_certificate ..//ssl//cuijiecheng.crt;  # 指定证书的位置，绝对路径
        ssl_certificate_key ..//ssl//cuijiecheng.key;  # 绝对路径，同上
        ssl_session_timeout 5m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2; #按照这个协议配置
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;#按照这个套件配置
        ssl_prefer_server_ciphers on;
        location / {
            root   www; #站点目录，绝对路径
            index  index.html index.htm;
        }
		location /stat {
            #推流播放和录制统计数据的配置
 
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
        }
        location /stat.xsl {
            root www; #指定stat.xsl的位置
        }
		location /flv_live {
            flv_live on; #打开HTTP播放FLV直播流功能
            chunked_transfer_encoding on; #支持'Transfer-Encoding: chunked'方式回复
 
            add_header 'Access-Control-Allow-Origin' '*'; #添加额外的HTTP头
            add_header 'Access-Control-Allow-Credentials' 'true'; #添加额外的HTTP头
        }
    }
