### ISSUE TITLE
在安卓和ios上做视频直播

### ISSUE THREAD

**Issue by cytGitHub** [Bilibili/flv.js#76]
可以用这个做web版本的直播么？会不会遇到好多坑啊？ 这个库兼容ios和android “最低” 多少版本

**Comment by cytGitHub** [comment]
`Fetch API cannot load http://hlsws.sinashow.com/live/88960543_1482892528.flv. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access. The response had HTTP status code 404. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
flv.js:10580 [IOController] > Loader error, code = -1, msg = Failed to fetche @ flv.js:10580_onLoaderError @ flv.js:6466(anonymous function) @ flv.js:5818
flv.js:10580 [TransmuxingController] > IOException: type = Exception, code = -1, msg = Failed to fetche @ flv.js:10580_onIOException @ flv.js:3473_onLoaderError @ flv.js:6504(anonymous function) @ flv.js:5818
flv.js:1224 Uncaught (in promise) Error: Uncaught, unspecified "error" event. (NetworkError)(…)`

IOException: type = Exception, code = -1, msg = Failed to fetch 这个报错是什么意思啊

**Comment by xqq** [comment]
404

**Comment by cytGitHub** [comment]
要是通过 ES6 导入的话 可以这样么 `import flv from 'flv.js'`  或者  `require('flv.js')`

**Comment by cytGitHub** [comment]
@xqq 我在react中使用flv，每次从后台获取的视频地址 我用播放器是可以播放的，但是把地址放到程序中就会出问题。
                  `componentDidMount() {
			this.setState({ url: this.props.location.query.url });
			if (flvjs.isSupported()) {
		        var videoElement = document.getElementById('videoElement');
		        var flvPlayer = flvjs.createPlayer({
		            type: 'flv',
		            url: this.state.url    --->重点在这里，设置了url 之后也不可以播放
		        });
		        flvPlayer.attachMediaElement(videoElement);
		        function flv_load () {
		            flvPlayer.load();
		        }
		        function flv_start () {
		            flvPlayer.play();
		        }

		        flv_load();
		        flv_start();
    		}	
		},`

**Comment by cytGitHub** [comment]
@xqq  视频url 格式类似于这样 ` http://hdlws.baidu/live/89073809_1482904514.flv`  ， 但是我通过chrome发现  video的标签中src 的属性是这样  `src="blob:http://127.0.0.1:8080/4e9945a9-b619-4965-96ce-e6ca3ae96298"`     为什么video标签中src的属性 不是我后台获取的url地址呢？

**Comment by xqq** [comment]
因为 video 标签的数据源是 MediaSource

**Comment by xqq** [comment]
这个 blob 地址实际上是对某个 MediaSource 对象的引用
