### ISSUE TITLE
Can't play video on LG tv's browser (webOS)

### ISSUE THREAD

**Issue by wawahuy** [Bilibili/flv.js#768]
It's smart Tv LG 2019 (webOS),
I use default browser but it doesn't work, also play on chrome,
I can't see the console log or any other.

**Comment by heydayle** [comment]
can your TV was very old :))

**Comment by wawahuy** [comment]
I think the problem lies somewhere, I see BE downloading but black screen.
Recently I found a new solution to this video streaming problem is to replace flv with fragmented mp4 tape, play perfectly with videojs library on ffmpeg with -movflags frag_keyframe+empty_moov
