### ISSUE TITLE
祝倒闭

### ISSUE THREAD

**Issue by hebiao6446** [Bilibili/flv.js#77]
你们公司这么牛，程序猿都知道吗 ？

**Comment by yegao** [comment]
怎么了？

**Comment by zhuochenming** [comment]
没有韩红的命 却有韩红的病 哈哈哈

**Comment by hebiao6446** [comment]
写这个项目的程序猿月薪5K， 我算日了狗！

**Comment by DieMoe233** [comment]
修正，是不到5k。

**Comment by cytGitHub** [comment]
这也说明了 现在的互联网行业


原始邮件
发件人:DieMoe233notifications@github.com
收件人:Bilibili/flv.jsflv.js@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2016年12月29日(周四) 09:53
主题:Re: [Bilibili/flv.js] 祝倒闭 (#77)


修正，是不到5k。

**Comment by hanasakari** [comment]
正常的啦，这种奇葩事只能去习惯，大不了换一家嘛，不重视技术的后果看看AVfan的问题吧

**Comment by yegao** [comment]
早在知乎上有听说...

**Comment by cytGitHub** [comment]
恩呢


原始邮件
发件人:叶锆锆notifications@github.com
收件人:Bilibili/flv.jsflv.js@noreply.github.com
抄送:常运涛_Yesssh_github@163.com; Commentcomment@noreply.github.com
发送时间:2016年12月29日(周四) 11:41
主题:Re: [Bilibili/flv.js] 祝倒闭 (#77)


早在知乎上有听说...

**Comment by xqq** [comment]
请勿发表技术无关issue
