### ISSUE TITLE
Custom HTML5 video player for bilibili.com/bilibili.tv

### ISSUE THREAD

**Issue by vogdb** [Bilibili/flv.js#785]
Hi! Sorry for asking it here. I want to embed videos from bilibili.com in my custom video player (plyr.js or flv.js). Can you please advice how can I do that?

**Comment by anmancontent** [comment]
did you got any thing about it ?

**Comment by vogdb** [comment]
Unfortunately not. Had to abandon this idea. Used only Youtube and Vimeo
