### ISSUE TITLE
有一条flv直播流显示绿屏，有声音

### ISSUE THREAD

**Issue by hongweiqu** [Bilibili/flv.js#83]
![default](https://cloud.githubusercontent.com/assets/3480291/22017476/7e406d9c-dce5-11e6-814b-7e1c4791d587.png)

请教下什么原因

**Comment by xqq** [comment]
啥？腾讯X5支持MSE了，太阳打西边出来了？

**Comment by hongweiqu** [comment]
这个测试是用的系统内核
