### ISSUE TITLE
Open URL request

### ISSUE THREAD

**Issue by ron666** [Bilibili/flv.js#85]
Hi,

I'd like to know if you have a URL I can use for the http://www.mediaelementjs.com project. We support FLV files natively through your plugin. But I don't have the possibility to host it anywhere; do you have a URL I can use to demonstrate its use, please?

**Comment by xqq** [comment]
There's no online demo page for now.
If you're saying about bundled js file, here -> https://cdnjs.cloudflare.com/ajax/libs/flv.js/1.1.0/flv.min.js

**Comment by ron666** [comment]
No I'm talking about a demo file. Do you expect to have one soon?

**Comment by xqq** [comment]
I have no administrator's permission of this repo to build a ghpages site.

You'd better to set up the `demo/index.html` on your own.

**Comment by ron666** [comment]
Oh I'm sorry I didn't make myself understood. I mean if you don't have a public URL for an FLV file I can use as a showcase (like http://yoursite.com/example.flv)

**Comment by xqq** [comment]
Sorry... I have no public flv file on my site.

If you need a url for testing, open a video in http://www.bilibili.com then search `.flv` in F12 Network.

for example https://ws.acgvideo.com/1/ab/13316781-1.flv?wsTime=1484983314&wsSecret2=4703557e24bc2703798a55873569f2c0&oi=2111831551&rate=1500

Notice: This URL has limited valid time.

**Comment by ron666** [comment]
All of them have time limit? I need a persistent one
