### ISSUE TITLE
执行gulp release的时候ESLint报错，求教？

### ISSUE THREAD

**Issue by PengSihang** [Bilibili/flv.js#89]
...
16:808    error  Strings must use singlequote                                    quotes
16:821    error  Missing whitespace after semicolon                              semi-spacing
16:822    error  Unexpected var, use let or const instead                        no-var
16:838    error  Infix operators must be spaced                                  space-infix-ops
16:846    error  Strings must use singlequote                                    quotes
16:861    error  Infix operators must be spaced                                  space-infix-ops
16:866    error  Strings must use singlequote                                    quotes
16:881    error  Missing whitespace after semicolon                              semi-spacing
16:882    error  Unexpected var, use let or const instead                        no-var
16:900    error  Infix operators must be spaced                                  space-infix-ops
...

✖ 77017 problems (77017 errors, 0 warnings)

[17:19:24] 'lint' errored after 9.23 s
[17:19:24] ESLintError in plugin 'gulp-eslint'
Message:
    Failed with 77017 errors

执行gulp release命令的时候总是报这个错。请问下是什么原因？

**Comment by Moran349** [comment]
错误日志已经说明的很清楚了
字符串使用单引号
分号后缺少空白字符
使用let或者const代替var 。。。。

eslint中有定义js的编码规范，不符合规范的编译时会报错
从日志上来看，你可能将代码的换行符、单引号等进行了更改，所以会出错

**Comment by PengSihang** [comment]
@Moran349 谢谢，本来我问的不是这个问题本身的。

原因查明了，结果是我在src包里面加入了一个自己另外编的js，才导致gulp release时候报错。
把自己编的js删掉之后，就通过了
谢谢
