### ISSUE TITLE
Is it good attaching flv Object to window?

### ISSUE THREAD

**Issue by p2227** [Bilibili/flv.js#9]
https://github.com/Bilibili/flv.js/blob/5176f5d935c41a1ee8dbd9eca65b3a6fe7df6b9e/src/flv.js#L81

I think this code should only appearance in dist code and produced by “gulp build” or similar task.

use this: https://www.npmjs.com/package/babel-plugin-transform-es2015-modules-umd

**Comment by xqq** [comment]
Fixed in https://github.com/Bilibili/flv.js/commit/190a5975a8e46328206f89b6555922cc72a6c4bf
I think `babel-plugin-transform-es2015-modules-umd` may cause each js file to be wrapped by a umd wrapper. Then I found browserify can do this easily.

Thank you.
