### ISSUE TITLE
youku的高清流只能播前面一部分

### ISSUE THREAD

**Issue by smovie** [Bilibili/flv.js#90]
日志显示 [FlvPlayer] > Maximum buffering duration exceeded, suspend transmuxing task
其他1080P、超清、普清都正常

**Comment by xqq** [comment]
没有测试过youku的流，需要更多信息

**Comment by smovie** [comment]
之前想当然的认为是flv文件，后来发现高清流是分段的mp4，但是type设为mp4后控制台只有一个ERROR信息

**Comment by xqq** [comment]
不支持多段mp4
