### ISSUE TITLE
how to play multi-audio-tracks with flv.js

### ISSUE THREAD

**Issue by woshishuxiong** [Bilibili/flv.js#91]
flv.js supports converting AAC raw data to mp4 and play it. Assume that there are more than one AAC audio tracks. How to play these tracks at the same time. 
Thanks a lot.

**Comment by xqq** [comment]
How do you storage multiple audio tracks in an flv file?

**Comment by woshishuxiong** [comment]
For example, loader fetch two FLV streams at the same time, which only contain audio data. What Can I do to mixing these two streams and play them with flv.js?

**Comment by xqq** [comment]
If you want to mixing up two audio track to playback, the existing logic of flv.js can not help.

You may need to decode aac packet manually using Web Audio API or FFmpeg,
Mix up the decode result (PCM) manually, then render PCM samples by Web Audio API.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API

**Comment by woshishuxiong** [comment]
That helps a lot. Thanks.
