### ISSUE TITLE
chrome下直播出现延时很高的情况，firefox却没有

### ISSUE THREAD

**Issue by Jiang21** [Bilibili/flv.js#94]
在chrome://media-internals/中log 显示

render_id: 46
player_id: 1
pipeline_state: kStopped
event: WEBMEDIAPLAYER_DESTROYED
url: blob:http://localhost:63342/a9c2678f-ab5f-4e11-92b4-954dc1ae5e1e
info: Audio codec: mp4a.40.2. Sampling frequency: 48000Hz. Sampling frequency(Extension): 48000Hz. Channel layout: 3.
found_video_stream: true
video_codec_name: h264
duration: unknown
found_audio_stream: true
audio_codec_name: aac
audio_dds: false
audio_decoder: FFmpegAudioDecoder
debug: Video rendering in low delay mode.
video_dds: false
video_decoder: FFmpegVideoDecoder
error: Failed to reconcile encoded audio times with decoded output.

**Comment by zgy520** [comment]
你好，是是如何实现直播的？你的流是如何进行传播的？

**Comment by wy513222130** [comment]
你是怎么做到直播的，我这边也用这个做直播，但是发现直播时间经过30分钟左右，mscontrol类里面的_doAppendSegments中的appendBuffer方法会报错，error.code === 22这样的错误。不知道你遇到了没有。都是在用直播可以加个QQ方便联系一下。749272206 或者发这个wy297@163.com邮件。
